Repository E3SM-Project/scream, pull requests merged in 2019-12, with the labels that each got.

#181 Test scripts upgrades
  components/scream/cmake/ctest_script.cmake
  components/scream/cmake/machine-files/generic-desktop.cmake
  components/scream/scripts/test-all-scream
  components/scream/scripts/test_all_scream.py
Labels: B4B, enhancement, testing

#186 Some modifications to testing scripts, and removing travis/codecov files
  .codacy.yml
  .codecov.yml
  .travis.yml
  components/scream/cmake/ctest_script.cmake
  components/scream/cmake/machine-files/generic-desktop-serial.cmake
  components/scream/scripts/test-all-scream
  components/scream/scripts/test_all_scream.py
Labels: AT: AUTOMERGE, B4B, testing

#191 Integrate scream into E3SM/CIME
  cime/config/e3sm/allactive/config_compsets.xml
  cime/config/e3sm/config_files.xml
  components/CMakeLists.txt
  components/cmake/build_scream.cmake
  components/scream/CMakeLists.txt
  components/scream/cime_config/buildlib
  components/scream/cime_config/buildlib_cmake
  components/scream/cime_config/buildnml
  components/scream/cime_config/config_component.xml
  components/scream/cime_config/config_compsets.xml
  components/scream/cime_config/config_pes.xml
  components/scream/cime_config/user_nl_scream
  components/scream/cmake/Kokkos.cmake
  components/scream/cmake/SetMpiCxxBackendCompilerVarName.cmake
  components/scream/src/CMakeLists.txt
  components/scream/src/interface/CMakeLists.txt
  components/scream/src/interface/atm_comp_mct.F90
  components/scream/src/physics/p3/CMakeLists.txt
Labels: B4B, Machine File, cmake

#192 gather-all-data: skip threading if only one thing to run
  components/scream/scripts/gather_all_data.py
Labels: AT: AUTOMERGE, B4B

#195 Change the parameters for p3_run_and_cmp test.
  components/scream/src/physics/p3/tests/p3_run_and_cmp.cpp
Labels: Non-B4B, p3, testing
