Repository E3SM-Project/scream, pull requests merged in 2019-04, with the labels that each got.

#76 Kylepressel/activation
  components/cam/src/physics/cam/micro_p3.F90
  components/cam/src/physics/cam/micro_p3_interface.F90
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/p3_f90.cpp
  components/scream/src/physics/p3/p3_f90.hpp
  components/scream/src/physics/p3/tests/p3_tests.cpp
Labels: Non-B4B, enhancement

#77 Homme atmosphere process
  components/homme/CMakeLists.txt
  components/homme/src/preqx_kokkos/prim_driver_mod.F90
  components/homme/src/share/cxx/ErrorDefs.cpp
  components/homme/src/share/cxx/Hommexx_Session.cpp
  components/homme/src/share/cxx/Hommexx_Session.hpp
  components/homme/src/share/parallel_mod.F90
  components/scream/cmake/ScreamUtils.cmake
  components/scream/src/control/atmosphere_driver.cpp
  components/scream/src/control/surface_coupling.cpp
  components/scream/src/control/surface_coupling.hpp
  components/scream/src/control/tests/ping_pong_test.cpp
  components/scream/src/dynamics/homme/CMakeLists.txt
  components/scream/src/dynamics/homme/atmosphere_dynamics.cpp
  components/scream/src/dynamics/homme/atmosphere_dynamics.hpp
  components/scream/src/dynamics/homme/dynamics_driven_grids_manager.cpp
  components/scream/src/dynamics/homme/dynamics_driven_grids_manager.hpp
  components/scream/src/dynamics/homme/homme_dynamics.cpp
  components/scream/src/dynamics/homme/hommexx_dimensions.hpp
  components/scream/src/dynamics/homme/scream_homme_interface.F90
  components/scream/src/dynamics/homme/scream_homme_interface.hpp
  components/scream/src/share/atmosphere_process.hpp
  components/scream/src/share/atmosphere_process_group.cpp
  components/scream/src/share/atmosphere_process_group.hpp
  components/scream/src/share/field/field_identifier.hpp
  components/scream/src/share/grid/abstract_grid.hpp
  components/scream/src/share/grid/default_grid.hpp
  components/scream/src/share/grid/grids_manager.hpp
  components/scream/src/share/grid/user_provided_grids_manager.hpp
  components/scream/src/share/tests/atm_process_tests.cpp
  components/scream/src/share/util/factory.hpp
  components/scream/tests/CMakeLists.txt
  components/scream/tests/scream_homme_dyn_ut_nlev72_qsize4/CMakeLists.txt
  components/scream/tests/scream_homme_dyn_ut_nlev72_qsize4/homme_stand_alone.cpp
Labels: homme

#81 Fixes bug in parallel_mod that broke fortran version during init.
  components/homme/src/share/parallel_mod.F90
Labels: B4B, bug

#78 Enable checks for snow in radiation
  components/cam/src/physics/rrtmgp/cam_optics.F90
Labels: B4B
