Repository E3SM-Project/scream, pull requests merged in 2019-11, with the labels that each got.

#168 SHOC updates (lower boundary convergence and bugs)
  components/cam/src/physics/cam/shoc.F90
  components/cam/src/physics/cam/shoc_intr.F90
Labels: bug, shoc

#180 convert calc bulk rho rime
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_constants.hpp
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_functions_ice_sed.cpp
  components/scream/src/physics/p3/p3_functions_ice_sed_impl.hpp
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_dsd2_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_ice_sed_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: B4B, p3

#156 Autoconversion port to C++/Kokkos.
  components/cam/src/physics/cam/micro_p3.F90
  components/cam/src/physics/cam/micro_p3_utils.F90
  components/scream/scripts/const-maker
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_constants.hpp
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_autoconversion.cpp
  components/scream/src/physics/p3/p3_functions_autoconversion_impl.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/tests/p3_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: Non-B4B, p3
