Repository E3SM-Project/scream, pull requests merged in 2019-10, with the labels that each got.

#152 Updated catch.hpp to v2.9.2.
  components/scream/extern/catch2/include/catch2/catch.hpp
Labels: B4B, infrastructure

#165 Fix for bfb_pow macro in P3
  components/cam/src/physics/cam/micro_p3.F90
Labels: bug, p3

#167 Correct a bug in the calculation of the rain area cloud fraction for P3 microphysics.
  components/cam/src/physics/cam/micro_p3_interface.F90
Labels: Non-B4B, bug, p3

#166 Add scream machine files for the LC machine: Lassen
  components/scream/cmake/machine-files/lassen.cmake
  components/scream/scripts/gather_all_data.py
Labels: Machine File

#169 Aarondonahue/precip frac speedup
  components/cam/src/physics/cam/micro_p3_interface.F90
Labels: B4B, code quality, p3

#170 simple fix to workspace tests to remove any dependency on openMP.
  components/scream/src/share/tests/workspace_tests.cpp
Labels: bug

#171 Add machine files for the Livermore Computing clusters quartz and syrah
  components/scream/cmake/machine-files/quartz.cmake
  components/scream/cmake/machine-files/syrah.cmake
  components/scream/scripts/gather_all_data.py
Labels: Machine File
