Repository E3SM-Project/scream, pull requests merged in 2020-07, with the labels that each got.

#441 Shoc TKE refactor -Part 2
  components/cam/src/physics/cam/shoc.F90
Labels: AT: AUTOMERGE, B4B, shoc

#440 Added isnan overload for packs, plus couple of fixes for testing
  components/scream/ekat/src/ekat/scream_pack.hpp
  components/scream/ekat/src/ekat/util/scream_utils.hpp
  components/scream/ekat/tests/pack/pack_tests.cpp
  components/scream/scripts/machines_specs.py
  components/scream/scripts/test_all_scream.py
Labels: AT: AUTOMERGE, EKAT, bugfix, enhancement, testing

#442 Enforce type=int for integer inputs of test-all-scream
  components/scream/scripts/test-all-scream
  components/scream/scripts/test_all_scream.py
Labels: AT: AUTOMERGE, testing

#443 Cdash cleanup branch
  components/scream/cime_config/config_component.xml
  components/scream/cmake/ctest_script.cmake
  components/scream/ekat/CMakeLists.txt
  components/scream/ekat/cmake/EkatUtils.cmake
  components/scream/ekat/cmake/Kokkos.cmake
  components/scream/ekat/cmake/YamlCpp.cmake
  components/scream/scripts/jenkins/jenkins_common.sh
  components/scream/scripts/test_all_scream.py
  components/scream/scripts/utils.py
Labels: AT: AUTOMERGE, cmake, testing

#434 SHOC grid property tests.
  components/cam/src/physics/cam/shoc.F90
  components/scream/src/physics/shoc/shoc_functions_f90.cpp
  components/scream/src/physics/shoc/shoc_functions_f90.hpp
  components/scream/src/physics/shoc/shoc_iso_c.f90
  components/scream/src/physics/shoc/tests/CMakeLists.txt
  components/scream/src/physics/shoc/tests/shoc_grid_tests.cpp
Labels: AT: AUTOMERGE, B4B, shoc, testing

#447 Scorpio integration interface phase2
  components/scream/CMakeLists.txt
  components/scream/cmake/GPTL.cmake
  components/scream/cmake/Scorpio.cmake
  components/scream/data/scorpio_output_baseline.nc
  components/scream/ekat/src/ekat/util/ekat_md_array.hpp
  components/scream/src/mct_coupling/CMakeLists.txt
  components/scream/src/mct_coupling/atm_comp_mct.F90
  components/scream/src/mct_coupling/scream_cxx_f90_interface.cpp
  components/scream/src/mct_coupling/scream_scorpio_interface.F90
  components/scream/src/mct_coupling/scream_scorpio_interface.cpp
  components/scream/src/mct_coupling/scream_scorpio_interface.hpp
  components/scream/src/mct_coupling/scream_scorpio_interface_iso_c.F90
  components/scream/src/mct_coupling/tests/CMakeLists.txt
  components/scream/src/mct_coupling/tests/scorpio_tests.cpp
Labels: AT: AUTOMERGE, Atmosphere Driver, B4B, enhancement, testing

#444 Refactor of shoc_assumed_pdf.
  components/cam/src/physics/cam/shoc.F90
Labels: AT: AUTOMERGE, B4B, shoc

#451 Aarondonahue/scorpio integration interface phase2 input
  components/scream/src/mct_coupling/scream_scorpio_interface.F90
  components/scream/src/mct_coupling/scream_scorpio_interface.cpp
  components/scream/src/mct_coupling/scream_scorpio_interface.hpp
  components/scream/src/mct_coupling/scream_scorpio_interface_iso_c.F90
  components/scream/src/mct_coupling/tests/CMakeLists.txt
  components/scream/src/mct_coupling/tests/scorpio_tests.cpp
Labels: AT: AUTOMERGE, Atmosphere Driver, B4B, enhancement, testing

#449 Better handling of Kokkos_ENABLE_Debug
  components/scream/cmake/machine-files/blake.cmake
  components/scream/cmake/machine-files/bowman.cmake
  components/scream/cmake/machine-files/compy.cmake
  components/scream/cmake/machine-files/lassen.cmake
  components/scream/cmake/machine-files/linux-generic-debug.cmake
  components/scream/cmake/machine-files/linux-generic-serial.cmake
  components/scream/cmake/machine-files/linux-generic.cmake
  components/scream/cmake/machine-files/quartz.cmake
  components/scream/cmake/machine-files/summit.cmake
  components/scream/cmake/machine-files/syrah.cmake
  components/scream/cmake/machine-files/waterman.cmake
  components/scream/cmake/machine-files/white.cmake
  components/scream/ekat/cmake/Kokkos.cmake
  components/scream/scripts/test_all_scream.py
  components/scream/src/physics/p3/p3_functions_main_impl.hpp
  components/scream/src/physics/p3/p3_functions_rain_sed_impl.hpp
Labels: AT: AUTOMERGE, B4B, bugfix, cmake

#446 Adds a light weight utility to print simulation parameters
  components/cam/src/physics/cam/debug_info.F90
  components/cam/src/physics/cam/micro_p3.F90
  components/cam/src/physics/cam/physpkg.F90
  components/scream/src/physics/p3/CMakeLists.txt
Labels: AT: AUTOMERGE, enhancement, p3

#454 Further refactor of the refactored compute_diag_third_shoc_moment subroutine
  components/cam/src/physics/cam/shoc.F90
Labels: AT: AUTOMERGE, B4B, shoc

#450 Add endrun command when SHOC diagnoses a negative temperature
  components/cam/src/physics/cam/shoc.F90
  components/scream/src/physics/common/CMakeLists.txt
  components/scream/src/physics/p3/CMakeLists.txt
Labels: AT: AUTOMERGE, B4B, shoc

#452 Improve SHOC numerical stability in stable PBL (and bug fix)
  components/cam/src/physics/cam/shoc.F90
Labels: Non-B4B, bugfix, enhancement, shoc

#456 Make run_and_cmp output more intuitive
  components/scream/src/physics/p3/tests/p3_run_and_cmp.cpp
  components/scream/src/physics/shoc/tests/shoc_run_and_cmp.cpp
Labels: AT: AUTOMERGE, B4B, testing

#457 Minor updates for local builds.
  components/scream/docs/build.md
  components/scream/src/physics/p3/p3_functions_f90.cpp
Labels: bug, documentation

#420 Update SCREAM compsets to use CMIP6 2010 tunings
  cime/config/e3sm/tests.py
  components/cam/bld/namelist_files/use_cases/2000_scream_hr.xml
  components/cam/bld/namelist_files/use_cases/2000_scream_lr.xml
  components/cam/bld/namelist_files/use_cases/2010_scream_hr.xml
  components/cam/bld/namelist_files/use_cases/2010_scream_lr.xml
  components/cam/cime_config/config_component.xml
  components/cam/cime_config/config_compsets.xml
  components/scream/cime_config/config_compsets.xml
Labels: AT: AUTOMERGE, Non-B4B

#461 SCREAM: renamed machine file for cori-knl to match CIME's mach name
  components/scream/cmake/machine-files/cori-knl.cmake
Labels: AT: AUTOMERGE, CI: Integrate Without Testing, testing

#460 some minor modifications
  components/scream/docs/build.md
Labels: CI: Integrate Without Testing, documentation

#430 Implements murphy and Koop formulation for computing saturation vapor pressure
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/ekat/src/ekat/scream_pack.hpp
  components/scream/src/physics/common/physics_functions.hpp
  components/scream/src/physics/common/physics_saturation_impl.hpp
  components/scream/src/physics/p3/tests/p3_saturation_unit_tests.cpp
Labels: AT: AUTOMERGE, Non-B4B, p3

#462 SHOC post refactor cleanup
  components/cam/src/physics/cam/shoc.F90
Labels: AT: AUTOMERGE, B4B, shoc

#468 CMAKE Fixes
  components/scream/CMakeLists.txt
  components/scream/cmake/CsmShare.cmake
  components/scream/cmake/GPTL.cmake
  components/scream/cmake/GetNetcdfLibs.cmake
  components/scream/cmake/Scorpio.cmake
  components/scream/ekat/cmake/Ekat.cmake
  components/scream/ekat/src/ekat/util/ekat_md_array.hpp
  components/scream/src/mct_coupling/CMakeLists.txt
  components/scream/src/mct_coupling/scream_scorpio_interface.F90
  components/scream/src/mct_coupling/tests/CMakeLists.txt
Labels: AT: AUTOMERGE, B4B, cmake, testing

#470 Renamed src/physics/common -> src/physics/share, moved saturation tests to src/physics/share/tests
  components/cam/src/physics/cam/bfb_math.inc
  components/cam/src/physics/cam/micro_p3.F90
  components/cam/src/physics/cam/shoc.F90
  components/scream/src/physics/CMakeLists.txt
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/register_physics.hpp
  components/scream/src/physics/rrtmgp/CMakeLists.txt
  components/scream/src/physics/share/CMakeLists.txt
  components/scream/src/physics/share/physics_constants.hpp
  components/scream/src/physics/share/physics_functions.hpp
  components/scream/src/physics/share/physics_only_grids_manager.cpp
  components/scream/src/physics/share/physics_only_grids_manager.hpp
  components/scream/src/physics/share/physics_saturation.cpp
  components/scream/src/physics/share/physics_saturation_impl.hpp
  components/scream/src/physics/share/physics_share.cpp
  components/scream/src/physics/share/physics_share.hpp
  components/scream/src/physics/share/physics_share_f2c.F90
  components/scream/src/physics/share/tests/CMakeLists.txt
  components/scream/src/physics/share/tests/physics_saturation_unit_tests.cpp
  components/scream/src/physics/share/tests/physics_unit_tests_common.hpp
  components/scream/src/physics/shoc/CMakeLists.txt
  components/scream/src/physics/shoc/tests/CMakeLists.txt
  components/scream/src/physics/shoc/tests/shoc_grid_tests.cpp
Labels: AT: AUTOMERGE, B4B, code quality, p3, testing

#463 Bugfix: fall speed uses incld quantities which aren't updated during sedimentation
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/p3_cloud_sed_impl.hpp
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_ice_sed_impl.hpp
  components/scream/src/physics/p3/p3_rain_sed_impl.hpp
Labels: Non-B4B, bugfix, p3

#472 rename p3_main functions
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_main_impl.hpp
  components/scream/src/physics/p3/tests/p3_main_unit_tests.cpp
Labels: AT: AUTOMERGE, B4B, p3

#480 Quick fix for a bug in gather_all_data.py with CTEST_PARALLEL_LEVEL
  components/scream/scripts/gather_all_data.py
Labels: AT: AUTOMERGE, B4B, bug, testing

#471 Make our testing infrastructure resource-aware
  components/scream/ekat/cmake/EkatCreateUnitTest.cmake
  components/scream/ekat/cmake/EkatSetNvccWrapper.cmake
  components/scream/ekat/src/ekat/CMakeLists.txt
  components/scream/ekat/src/ekat/util/ekat_catch_main.cpp
  components/scream/ekat/src/ekat/util/ekat_string_utils.cpp
  components/scream/ekat/src/ekat/util/ekat_string_utils.hpp
  components/scream/ekat/src/ekat/util/scream_test_utils.cpp
  components/scream/ekat/src/ekat/util/scream_test_utils.hpp
  components/scream/ekat/src/ekat/util/scream_units.hpp
  components/scream/ekat/src/ekat/util/string_utils.hpp
  components/scream/ekat/tests/utils/util_tests.cpp
  components/scream/scripts/machines_specs.py
  components/scream/scripts/test_all_scream.py
  components/scream/src/control/atmosphere_driver.cpp
  components/scream/src/share/atm_process/atmosphere_process.hpp
  components/scream/src/share/atm_process/atmosphere_process_group.cpp
  components/scream/src/share/field/field_identifier.hpp
  components/scream/src/share/field/field_repository.hpp
  components/scream/src/share/field/field_tracking.hpp
  components/scream/src/share/grid/grids_manager.hpp
  components/scream/src/share/grid/remap/abstract_remapper.hpp
Labels: AT: AUTOMERGE, testing

#479 bugfix^2: update nc and nr after get_dsd2
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/p3_cloud_sed_impl.hpp
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_rain_sed_impl.hpp
  components/scream/src/physics/p3/tests/p3_rain_sed_unit_tests.cpp
Labels: Non-B4B, bugfix, p3

#476 Fix read/write routines to allow for # mpi rank > 1 in scorpio_interface
  components/scream/src/mct_coupling/CMakeLists.txt
  components/scream/src/mct_coupling/scream_scorpio_interface.F90
  components/scream/src/mct_coupling/scream_scorpio_interface.cpp
  components/scream/src/mct_coupling/scream_scorpio_interface.hpp
  components/scream/src/mct_coupling/scream_scorpio_interface_iso_c2f.F90
  components/scream/src/mct_coupling/tests/scorpio_tests.cpp
Labels: AT: AUTOMERGE, Atmosphere Driver, I/O, testing

#473 Break F90 lines longer than 132 chars into 2 lines
  components/cam/src/physics/cam/micro_p3.F90
  components/cam/src/physics/cam/micro_p3_utils.F90
Labels: AT: AUTOMERGE, B4B, p3

#477 Introduce structs to high-level P3 interface
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/p3_f90.cpp
  components/scream/src/physics/p3/p3_f90.hpp
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_main_impl.hpp
  components/scream/src/physics/p3/scream_p3_interface.F90
  components/scream/src/physics/p3/tests/p3_main_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_tests.cpp
Labels: Non-B4B, code quality, p3

#482 Quick fix to the Livermore Computing machine specs machine entries.
  components/scream/scripts/machines_specs.py
Labels: AT: AUTOMERGE, B4B, CI: Integrate Without Testing, Machine File, testing
