Repository E3SM-Project/scream, pull requests merged in 2020-06, with the labels that each got.

#389 Fix for unset isotropy term for stable PBL
  components/cam/src/physics/cam/shoc.F90
Labels: AT: AUTOMERGE, Non-B4B, bug, shoc

#391 refactor energy_fixer subroutine
  components/cam/src/physics/cam/shoc.F90
Labels: AT: AUTOMERGE, B4B, shoc

#375 Kylepressel/shoc third moments
  components/cam/src/physics/cam/shoc.F90
Labels: AT: AUTOMERGE, B4B, shoc

#395 Minor mods to test-all-scream
  components/scream/scripts/test_all_scream.py
  components/scream/scripts/utils.py
Labels: AT: AUTOMERGE, B4B, testing

#392 Made property test tol bigger; make relvar3 test better for GPU
  components/scream/src/physics/p3/tests/p3_subgrid_variance_scaling_unit_tests.cpp
Labels: AT: AUTOMERGE, B4B, bug, p3

#399 Add a user-specific test with double the memleak tolerance
  cime/config/e3sm/tests.py
  components/cam/cime_config/testdefs/testmods_dirs/cam/double_memleak_tol/memleak_tol.sh
  components/cam/cime_config/testdefs/testmods_dirs/cam/double_memleak_tol/shell_commands
Labels: AT: AUTOMERGE, testing

#398 Factor-out main p3 loop in micro_p3
  components/cam/src/physics/cam/micro_p3.F90
Labels: AT: AUTOMERGE

#396 better testing for small pack size
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_main_impl.hpp
  components/scream/src/physics/p3/p3_functions_rain_sed_impl.hpp
  components/scream/src/physics/p3/p3_functions_rain_self_collection_impl.hpp
  components/scream/src/physics/p3/p3_functions_table_ice_impl.hpp
  components/scream/src/physics/p3/tests/p3_autoconversion_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_calc_liq_relaxation_timescale_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_calc_rime_density_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_cldliq_imm_freezing_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_cloud_rain_acc_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_droplet_activation_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_droplet_self_coll_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_dsd2_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_ice_cldliq_wet_growth_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_ice_collection_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_ice_melting_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_ice_nucleation_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_ice_relaxation_timescale_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_ice_sed_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_ice_tables_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_incloud_mixingratios_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_prevent_ice_overdepletion_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_rain_imm_freezing_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_rain_sed_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_rain_self_collection_tests.cpp
  components/scream/src/physics/p3/tests/p3_subgrid_variance_scaling_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: AT: AUTOMERGE

#402 Fix out of bounds bug.
  components/cam/src/physics/cam/shoc.F90
Labels: AT: AUTOMERGE, bug, shoc

#403 SCREAM: Wiping CMakeCache.txt and CMakeFiles before running tests
  components/scream/scripts/test_all_scream.py
Labels: AT: AUTOMERGE, B4B, bugfix, infrastructure, testing

#397 [WIP] First stab at source tree guide in docs/ directory.
  components/scream/README.md
  components/scream/docs/build.md
  components/scream/docs/source-tree.md
Labels: documentation

#405 Do not add p3_tend_out stuff to baselines
  components/scream/src/physics/p3/p3_f90.cpp
  components/scream/src/physics/p3/tests/p3_tests.cpp
Labels: Non-B4B

#406 SCREAM: fixing cmake-bug in CreateUnitTest
  components/scream/cmake/ScreamUtils.cmake
  components/scream/ekat/cmake/EkatSetCompilerFlags.cmake
  components/scream/src/physics/p3/tests/p3_subgrid_variance_scaling_unit_tests.cpp
Labels: AT: AUTOMERGE, cmake, testing

#409 SCREAM: first stab at using new AT feature
  components/scream/scripts/jenkins/jenkins_common.sh
Labels: AT: AUTOMERGE, CI: Integrate Without Testing

#407 Port p3 main main loop and get tests working
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_autoconversion_impl.hpp
  components/scream/src/physics/p3/p3_functions_back_to_cell_average_impl.hpp
  components/scream/src/physics/p3/p3_functions_calc_liq_relaxation_timescale_impl.hpp
  components/scream/src/physics/p3/p3_functions_calc_rime_density_impl.hpp
  components/scream/src/physics/p3/p3_functions_cldliq_imm_freezing_impl.hpp
  components/scream/src/physics/p3/p3_functions_cloud_rain_acc_impl.hpp
  components/scream/src/physics/p3/p3_functions_cloud_sed_impl.hpp
  components/scream/src/physics/p3/p3_functions_conservation_impl.hpp
  components/scream/src/physics/p3/p3_functions_droplet_self_coll_impl.hpp
  components/scream/src/physics/p3/p3_functions_dsd2.cpp
  components/scream/src/physics/p3/p3_functions_dsd2_impl.hpp
  components/scream/src/physics/p3/p3_functions_evaporate_sublimate_precip_impl.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_functions_get_time_space_phys_variables_impl.hpp
  components/scream/src/physics/p3/p3_functions_ice_cldliq_wet_growth_impl.hpp
  components/scream/src/physics/p3/p3_functions_ice_collection_impl.hpp
  components/scream/src/physics/p3/p3_functions_ice_deposition_sublimation_impl.hpp
  components/scream/src/physics/p3/p3_functions_ice_melting_impl.hpp
  components/scream/src/physics/p3/p3_functions_ice_nucleation_impl.hpp
  components/scream/src/physics/p3/p3_functions_ice_relaxation_timescale_impl.hpp
  components/scream/src/physics/p3/p3_functions_ice_sed_impl.hpp
  components/scream/src/physics/p3/p3_functions_impose_max_total_Ni_impl.hpp
  components/scream/src/physics/p3/p3_functions_incloud_mixingratios_impl.hpp
  components/scream/src/physics/p3/p3_functions_main_impl.hpp
  components/scream/src/physics/p3/p3_functions_prevent_ice_overdepletion_impl.hpp
  components/scream/src/physics/p3/p3_functions_rain_imm_freezing_impl.hpp
  components/scream/src/physics/p3/p3_functions_rain_sed_impl.hpp
  components/scream/src/physics/p3/p3_functions_rain_self_collection_impl.hpp
  components/scream/src/physics/p3/p3_functions_table3_impl.hpp
  components/scream/src/physics/p3/p3_functions_table_ice_impl.hpp
  components/scream/src/physics/p3/p3_functions_update_prognostics_impl.hpp
  components/scream/src/physics/p3/scream_p3_interface.F90
  components/scream/src/physics/p3/tests/p3_dsd2_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_ice_sed_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_ice_tables_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_main_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_rain_sed_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_table3_unit_tests.cpp
Labels: AT: AUTOMERGE, B4B, p3

#413 Homme: Fast F90 DIRK solver.
  components/homme/src/theta-l/imex_mod.F90
Labels: AT: AUTOMERGE, AT: RETEST

#415 Split out p3_main_post_main_loop in micro_p3
  components/cam/src/physics/cam/micro_p3.F90
Labels: AT: AUTOMERGE

#362 Refactor Shoc's update_prognostics_implicit
  components/cam/src/physics/cam/shoc.F90
Labels: AT: AUTOMERGE, B4B, shoc

#418 p3_main_post_main_loop: couple changes to ensure bfb with cxx
  components/cam/src/physics/cam/micro_p3.F90
Labels: Non-B4B

#419 Port p3 main post loop
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_functions_main_impl.hpp
  components/scream/src/physics/p3/tests/p3_main_unit_tests.cpp
Labels: AT: AUTOMERGE

#410 Testing: separating compilation and testing parallel levels
  components/scream/scripts/gather-all-data
  components/scream/scripts/gather_all_data.py
  components/scream/scripts/machines_specs.py
  components/scream/scripts/test-all-scream
  components/scream/scripts/test_all_scream.py
  components/scream/scripts/utils.py
Labels: AT: AUTOMERGE, B4B, testing

#383 refactor pblintd subroutine
  components/cam/src/physics/cam/shoc.F90
Labels: AT: AUTOMERGE, B4B, shoc

#421 Fix outflds and rm vap_cld_exchange from micro_p3_interface.F90
  components/cam/src/physics/cam/micro_p3_interface.F90
Labels: AT: AUTOMERGE, B4B, bug, p3

#422 Zero-init some outflds.
  components/cam/src/physics/cam/micro_p3.F90
Labels: AT: AUTOMERGE

#317 Interface scream with MCT, Vol. I
  cime/scripts/lib/CIME/build.py
  components/CMakeLists.txt
  components/cmake/build_scream.cmake
  components/homme/src/preqx_kokkos/CMakeLists.txt
  components/scream/CMakeLists.txt
  components/scream/cime_config/buildlib_cmake
  components/scream/cime_config/config_component.xml
  components/scream/cmake/machine-files/linux-generic-debug.cmake
  components/scream/cmake/machine-files/linux-generic-serial.cmake
  components/scream/cmake/machine-files/linux-generic.cmake
  components/scream/data/scream_input.yaml
  components/scream/ekat/CMakeLists.txt
  components/scream/ekat/cmake/YamlCpp.cmake
  components/scream/ekat/src/ekat/scream_parameter_list.hpp
  components/scream/ekat/src/ekat/scream_session.cpp
  components/scream/ekat/src/ekat/util/scream_arch.cpp
  components/scream/ekat/src/ekat/util/time_stamp.cpp
  components/scream/ekat/src/ekat/util/time_stamp.hpp
  components/scream/src/control/atmosphere_driver.cpp
  components/scream/src/control/tests/ad_tests.cpp
  components/scream/src/control/tests/ping_pong_test.cpp
  components/scream/src/dynamics/CMakeLists.txt
  components/scream/src/dynamics/homme/CMakeLists.txt
  components/scream/src/dynamics/homme/atmosphere_dynamics.cpp
  components/scream/src/dynamics/homme/atmosphere_dynamics.hpp
  components/scream/src/dynamics/homme/dynamics_driven_grids_manager.cpp
  components/scream/src/dynamics/homme/dynamics_driven_grids_manager.hpp
  components/scream/src/dynamics/homme/homme_dynamics_helpers.hpp
  components/scream/src/dynamics/homme/physics_dynamics_remapper.hpp
  components/scream/src/dynamics/homme/scream_homme_interface.hpp
  components/scream/src/dynamics/register_dynamics.hpp
  components/scream/src/interface/CMakeLists.txt
  components/scream/src/interface/ScreamContext.hpp
  components/scream/src/interface/atm_comp_mct.F90
  components/scream/src/interface/scream_cxx_f90_interface.cpp
  components/scream/src/interface/surface_coupling.hpp
  components/scream/src/physics/common/CMakeLists.txt
  components/scream/src/physics/common/physics_only_grids_manager.cpp
  components/scream/src/physics/common/physics_only_grids_manager.hpp
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/atmosphere_microphysics.cpp
  components/scream/src/physics/p3/p3_inputs_initializer.cpp
  components/scream/src/physics/p3/p3_inputs_initializer.hpp
  components/scream/src/physics/register_physics.hpp
  components/scream/src/physics/shoc/tests/shoc_stand_alone.cpp
  components/scream/src/scream_config.h.in
  components/scream/src/share/field/field_tracking.cpp
  components/scream/src/share/field/field_tracking.hpp
  components/scream/src/share/field/field_utils.hpp
  components/scream/src/share/field/field_value_initializer.hpp
  components/scream/src/share/grid/grids_manager.hpp
  components/scream/src/share/tests/field_tests.cpp
  components/scream/tests/scream_p3/input.yaml
  components/scream/tests/scream_p3/p3_stand_alone.cpp
  components/scream/tests/scream_p3_shoc/input.yaml
  components/scream/tests/scream_p3_shoc/p3_shoc_coupled.cpp
Labels: Atmosphere Driver, cmake, infrastructure

#425 This commit will add the FSCREAM-SA compset to the nightly tests
  cime/config/e3sm/tests.py
Labels: AT: AUTOMERGE, B4B, testing

#388 Add SCREAM interface to RRTMGP
  components/scream/src/physics/rrtmgp/CMakeLists.txt
  components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp
  components/scream/src/physics/rrtmgp/atmosphere_radiation.hpp
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.F90
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.cpp
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.hpp
  components/scream/src/physics/rrtmgp/tests/rrtmgp_tests.cpp
  components/scream/tests/rrtmgp/CMakeLists.txt
  components/scream/tests/rrtmgp/rrtmgp_stand_alone.cpp
Labels: AT: AUTOMERGE, radiation

#426 Include <vector> in scream_session.cpp.
  components/scream/ekat/src/ekat/scream_assert.hpp
  components/scream/ekat/src/ekat/scream_session.cpp
Labels: AT: AUTOMERGE, B4B, bug, bugfix

#384 SCORPIO - output integration
  components/scream/src/CMakeLists.txt
  components/scream/src/mct_coupling/CMakeLists.txt
  components/scream/src/mct_coupling/ScreamContext.hpp
  components/scream/src/mct_coupling/atm_comp_mct.F90
  components/scream/src/mct_coupling/dead_data_mod.F90
  components/scream/src/mct_coupling/dead_mct_mod.F90
  components/scream/src/mct_coupling/dead_mod.F90
  components/scream/src/mct_coupling/scream_cxx_f90_interface.cpp
  components/scream/src/mct_coupling/scream_scorpio_interface.F90
  components/scream/src/mct_coupling/surface_coupling.cpp
  components/scream/src/mct_coupling/surface_coupling.hpp
Labels: B4B, I/O, enhancement, infrastructure

#357 Shoc TKE refactor
  components/cam/src/physics/cam/shoc.F90
Labels: AT: AUTOMERGE, B4B, shoc

#424 A series of small upgrades to automated testing scripts
  components/scream/CMakeLists.txt
  components/scream/scripts/jenkins/jenkins_common.sh
  components/scream/scripts/machines_specs.py
  components/scream/scripts/test_all_scream.py
  components/scream/src/control/tests/CMakeLists.txt
  components/scream/src/dynamics/homme/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/rrtmgp/tests/CMakeLists.txt
  components/scream/src/physics/shoc/tests/CMakeLists.txt
  components/scream/src/share/tests/CMakeLists.txt
  components/scream/tests/CMakeLists.txt
Labels: AT: AUTOMERGE, B4B, cmake, enhancement, testing

#427 Set a few arrays to zero
  components/cam/src/physics/cam/micro_p3_interface.F90
Labels: AT: AUTOMERGE

#431 Include a call to finalize scream session for SCORPIO error handling
  components/scream/ekat/src/ekat/scream_session.cpp
  components/scream/ekat/src/ekat/scream_session.hpp
  components/scream/src/mct_coupling/scream_scorpio_interface.F90
Labels: AT: AUTOMERGE, B4B, EKAT

#429 Replaced STOP with endscreamrun calls and some minor fixes
  components/cam/src/physics/cam/micro_p3.F90
  components/cam/src/physics/cam/scream_abortutils.F90
  components/scream/cmake/machine-files/compy.cmake
  components/scream/ekat/src/ekat/util/scream_utils.hpp
  components/scream/src/physics/p3/CMakeLists.txt
Labels: AT: AUTOMERGE, B4B, p3

#414 Micro optimization to the Mask structure utilities.
  components/scream/ekat/src/ekat/ekat_scalar_traits.hpp
  components/scream/ekat/src/ekat/scream_assert.hpp
  components/scream/ekat/src/ekat/scream_pack.hpp
  components/scream/scripts/test_all_scream.py
Labels: AT: AUTOMERGE, B4B, EKAT, infrastructure

#438 Clean P3 scream infrastructure
  components/cam/src/physics/cam/micro_p3.F90
  components/cam/src/physics/cam/micro_p3_utils.F90
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_f90.cpp
  components/scream/src/physics/p3/p3_f90.hpp
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_functions_main_impl.hpp
  components/scream/src/physics/p3/tests/p3_check_values_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_main_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_rain_sed_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_run_and_cmp.cpp
  components/scream/src/physics/p3/tests/p3_table3_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_tests.cpp
Labels: AT: AUTOMERGE

#437 Adds Compy's machine spec file
  components/scream/scripts/machines_specs.py
Labels: AT: AUTOMERGE, B4B, Machine File

#439 Add include of std::vector.
  components/scream/ekat/src/ekat/scream_pack_kokkos.hpp
Labels: AT: AUTOMERGE, B4B, EKAT, bugfix

#390 further refactor shock_moments subroutine
  components/cam/src/physics/cam/shoc.F90
Labels: Non-B4B, shoc
