Repository E3SM-Project/scream, pull requests merged in 2020-02, with the labels that each got.

#215 Scream: allow non-clean repo if baseline ref is HEAD
  components/scream/scripts/test-all-scream
  components/scream/scripts/test_all_scream.py
Labels: AT: AUTOMERGE, enhancement, testing

#202 Upgrade for GPU workspace idx
  components/scream/scripts/perf-analysis
  components/scream/scripts/perf_analysis.py
  components/scream/src/share/scream_workspace.hpp
  components/scream/src/share/scream_workspace_impl.hpp
  components/scream/src/share/tests/kokkos_utils_tests.cpp
  components/scream/src/share/tests/workspace_tests.cpp
  components/scream/src/share/util/scream_kokkos_utils.hpp
Labels: AT: AUTOMERGE

#216 Fix minor bugs preventing building with GNU
  components/cam/src/physics/cam/micro_p3_interface.F90
  components/cam/src/physics/rrtmgp/radiation.F90
Labels: AT: AUTOMERGE, B4B, code quality, p3, radiation

#208 Suppress warnings from Kokkos
  components/scream/cmake/Kokkos.cmake
  components/scream/src/dynamics/homme/CMakeLists.txt
  components/scream/src/interface/CMakeLists.txt
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/shoc/CMakeLists.txt
  components/scream/src/share/CMakeLists.txt
  components/scream/src/share/scream_kokkos.hpp
  components/scream/src/share/scream_kokkos_meta.hpp
  components/scream/src/share/scream_session.cpp
  components/scream/src/share/scream_types.hpp
  components/scream/src/share/util/scream_kokkos_utils.hpp
  components/scream/src/share/util/scream_upper_bound.hpp
Labels: AT: AUTOMERGE

#221 SHOC fix to prevent raising negative value to fraction power
  components/cam/src/physics/cam/shoc.F90
Labels: B4B, bug, shoc

#220 Add e3sm_scream suite
  cime/config/e3sm/tests.py
  cime/scripts/Tools/Makefile
  cime/scripts/lib/CIME/build.py
Labels: B4B

#222 Flip SHOC in the vertical
  components/cam/src/physics/cam/shoc.F90
  components/cam/src/physics/cam/shoc_intr.F90
Labels: Non-B4B, shoc

#223 Xyuan/p3 ice collection
  components/cam/src/physics/cam/micro_p3.F90
  components/cam/src/physics/cam/micro_p3_utils.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_constants.hpp
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_functions_ice_collection.cpp
  components/scream/src/physics/p3/p3_functions_ice_collection_impl.hpp
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_ice_collection_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: AT: AUTOMERGE, p3

#224 Convert homogeneous_freezing
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_constants.hpp
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_functions_ice_sed_impl.hpp
  components/scream/src/physics/p3/tests/p3_ice_sed_unit_tests.cpp
Labels: B4B, p3

#225 test-all-scream: Upgrade handling of baselines
  components/scream/scripts/test-all-scream
  components/scream/scripts/test_all_scream.py
  components/scream/scripts/utils.py
Labels: B4B, infrastructure, testing

#226 Kylepressel/impose max total ni
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_functions_impose_max_total_Ni.cpp
  components/scream/src/physics/p3/p3_functions_impose_max_total_Ni_impl.hpp
  components/scream/src/physics/p3/tests/p3_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: B4B, p3

#217 Update_prognostic_liquid subroutine port
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_constants.hpp
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_functions_update_prognostics_impl.hpp
  components/scream/src/physics/p3/tests/p3_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
  components/scream/src/share/scream_pack.hpp
  components/scream/src/share/tests/pack_tests.cpp
Labels: p3

#230 Autoconversion test refactor and clean-up.
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_autoconversion_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests.cpp
Labels: B4B, p3, testing

#227 Converted p3 microphysics cloud_rain_accretion subroutine to C++/Kokkos.
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_cloud_rain_acc.cpp
  components/scream/src/physics/p3/p3_functions_cloud_rain_acc_impl.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_cloud_rain_acc_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: Non-B4B, p3

#228 add and modify tuning parameter for SHOC mixing length
  components/cam/src/physics/cam/shoc.F90
Labels: Non-B4B, shoc

#232 SHOC refactor (PBL depth, energy calculation, substep)
  components/cam/src/physics/cam/shoc.F90
  components/cam/src/physics/cam/shoc_intr.F90
  components/scream/src/physics/shoc/scream_shoc_interface.F90
Labels: Non-B4B, shoc

#235 SHOC refactor cleanup
  components/cam/src/physics/cam/shoc.F90
  components/cam/src/physics/cam/shoc_intr.F90
  components/scream/src/physics/shoc/scream_shoc_interface.F90
Labels: AT: AUTOMERGE

#237 SHOC bug fix to resolve intent in/out issue
  components/cam/src/physics/cam/shoc.F90
Labels: AT: AUTOMERGE, B4B, bug, shoc

#239 correct size of input array presi in SHOC
  components/cam/src/physics/cam/shoc.F90
Labels: AT: AUTOMERGE, bug, shoc

#242 Warnings suppression
  components/cam/src/physics/cam/micro_p3_utils.F90
  components/scream/CMakeLists.txt
  components/scream/src/physics/p3/scream_p3_interface.F90
  components/scream/src/physics/shoc/scream_shoc_interface.F90
Labels: AT: AUTOMERGE, B4B

#245 SHOC fixes
  components/cam/src/physics/cam/shoc.F90
Labels: AT: AUTOMERGE, Non-B4B, bug, shoc

#246 Removing useless sed for f90 config file
  components/scream/CMakeLists.txt
Labels: AT: AUTOMERGE, cmake

#241 Jeff cohere/droplet self collection
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_droplet_self_coll.cpp
  components/scream/src/physics/p3/p3_functions_droplet_self_coll_impl.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_droplet_self_coll_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: AT: AUTOMERGE, B4B

#249 Non-BFB re-baseline for rain_immersion_freezing conversion
  components/cam/src/physics/cam/micro_p3.F90
Labels: Non-B4B

#250 Conversion of rain_immersion_freezing
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_constants.hpp
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_functions_rain_imm_freezing.cpp
  components/scream/src/physics/p3/p3_functions_rain_imm_freezing_impl.hpp
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_cloud_rain_acc_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_droplet_self_coll_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_rain_imm_freezing_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: B4B

#251 Non-BFB changes to F90 cldliq_immersion_freezing subroutine
  components/cam/src/physics/cam/micro_p3.F90
Labels: Non-B4B, p3

#253 Converted cldliq_immersion_freezing subroutine to C++/Kokkos
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_cldliq_imm_freezing.cpp
  components/scream/src/physics/p3/p3_functions_cldliq_imm_freezing_impl.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_cldliq_imm_freezing_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
  components/scream/src/share/scream_pack.hpp
  components/scream/src/share/tests/pack_tests.cpp
Labels: AT: AUTOMERGE, B4B, p3
