Repository E3SM-Project/scream, pull requests merged in 2020-03, with the labels that each got.

#255 Non-BFB conversion of calc_rime_density.
  components/cam/src/physics/cam/micro_p3.F90
Labels: Non-B4B, p3

#257 Kylepres/rename autoconversion ut
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_autoconversion_unit_tests.cpp
Labels: B4B, p3

#259 Port ice_melting: initial non-bfb F90 changes
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
Labels: Non-B4B

#264 Made sure outputs are always set for calc_rime_density.
  components/cam/src/physics/cam/micro_p3.F90
Labels: B4B, p3

#273 bfb apply bfb_cbrt, bfb_sqrt to fortran relaxation_timescale
  components/cam/src/physics/cam/micro_p3.F90
Labels: AT: AUTOMERGE, Non-B4B, p3

#271 Helping out a picky C++ compiler with initializing an array.
  components/scream/src/share/util/rational_constant.hpp
  components/scream/src/share/util/scaling_factor.hpp
  components/scream/src/share/util/units.hpp
Labels: AT: AUTOMERGE, B4B, bug

#270 Non-b4b F90 changes for rain self collection.
  components/cam/src/physics/cam/micro_p3.F90
Labels: AT: RETEST, Non-B4B, p3

#261 Limit temperature debugging warnings in P3
  components/cam/src/physics/cam/micro_p3.F90
Labels: AT: AUTOMERGE, p3, radiation

#276 non BFB bfb_exp function replacement for ice_nucleation
  components/cam/src/physics/cam/micro_p3.F90
Labels: AT: AUTOMERGE, Non-B4B, p3

#262 bugfix: T0=273.15 rather htan 273.16 in polysvp1
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/p3_functions_math_impl.hpp
Labels: Non-B4B

#260 Converted calc_rime_density to C++/Kokkos
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_calc_rime_density.cpp
  components/scream/src/physics/p3/p3_functions_calc_rime_density_impl.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_calc_rime_density_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: AT: AUTOMERGE, B4B, p3

#278 Make master clean wrt nightlies and AT.
  components/scream/src/physics/p3/tests/p3_unit_tests.cpp
Labels: AT: AUTOMERGE

#280 BFB porting ice_relaxation_timescale to cpp
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_functions_ice_relaxation_timescale.cpp
  components/scream/src/physics/p3/p3_functions_ice_relaxation_timescale_impl.hpp
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_ice_relaxation_timescale_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: AT: AUTOMERGE, B4B, p3

#281 BFB porting ice_nucleation to cpp
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_functions_ice_nucleation.cpp
  components/scream/src/physics/p3/p3_functions_ice_nucleation_impl.hpp
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_ice_nucleation_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: AT: AUTOMERGE, B4B, p3

#263 Converted back_to_cell_average
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_back_to_cell_average.cpp
  components/scream/src/physics/p3/p3_functions_back_to_cell_average_impl.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_back_to_cell_average_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: AT: AUTOMERGE, B4B, p3

#283 non-BFB change in micro_p3 for ice_cldliq_wet_growth
  components/cam/src/physics/cam/micro_p3.F90
Labels: AT: AUTOMERGE, Non-B4B, p3

#284 Non-BFB changes for conversion of prevent_ice_overdepletion
  components/cam/src/physics/cam/micro_p3.F90
Labels: Non-B4B, p3

#288 Some fixes/upgrades to test-all-scream
  components/scream/scripts/test_all_scream.py
  components/scream/scripts/utils.py
Labels: AT: AUTOMERGE, enhancement, testing

#287 Deleted default constructor for FieldHeader class.
  components/scream/src/share/field/field_header.hpp
Labels: AT: AUTOMERGE, B4B

#285 Converted prevent_ice_overdepletion to C++/Kokkos.
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_functions_math_impl.hpp
  components/scream/src/physics/p3/p3_functions_prevent_ice_overdepletion.cpp
  components/scream/src/physics/p3/p3_functions_prevent_ice_overdepletion_impl.hpp
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_prevent_ice_overdepletion_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: AT: AUTOMERGE, B4B, p3

#290 Non-BFB revisions to calc_liq_relaxation_timescale
  components/cam/src/physics/cam/micro_p3.F90
Labels: AT: AUTOMERGE, Non-B4B, p3

#295 non-BFB for droplet_activation
  components/cam/src/physics/cam/micro_p3_utils.F90
Labels: AT: AUTOMERGE, Non-B4B, p3

#300 Reformatted shoc.F90 (whitespace only).
  components/cam/src/physics/cam/shoc.F90
Labels: B4B, shoc

#229 Kylepressel/rain self collection
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_functions_rain_self_collection.cpp
  components/scream/src/physics/p3/p3_functions_rain_self_collection_impl.hpp
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_rain_self_collection_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: B4B, p3

#293 SCREAM: disable mpicxx bindings
  components/scream/CMakeLists.txt
  components/scream/cmake/ScreamMpiUtils.cmake
  components/scream/cmake/SetMpiCxxBackendCompilerVarName.cmake
Labels: AT: AUTOMERGE, B4B, cmake

#252 Ports ice_deposition_sublimation subroutine
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_functions_ice_deposition_sublimation.cpp
  components/scream/src/physics/p3/p3_functions_ice_deposition_sublimation_impl.hpp
  components/scream/src/physics/p3/tests/p3_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: AT: AUTOMERGE, B4B, p3

#256 Ports evaporate_sublimate_precip
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_evaporate_sublimate_precip.cpp
  components/scream/src/physics/p3/p3_functions_evaporate_sublimate_precip_impl.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/tests/p3_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: B4B, p3

#291 SCREAM: Turn sp into a constexpr function.
  components/scream/src/share/util/scream_utils.hpp
Labels: AT: AUTOMERGE, B4B, code quality

#298 changes in check_values for better porting to scream
  components/cam/src/physics/cam/micro_p3.F90
Labels: AT: AUTOMERGE, B4B, p3

#301 SCREAM: make test-all-scream side-effect-free
  components/scream/scripts/test_all_scream.py
  components/scream/scripts/utils.py
Labels: AT: AUTOMERGE, enhancement, testing

#294 Converted calc_liq_relaxation_timescale to C++/Kokkos
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_calc_liq_relaxation_timescale.cpp
  components/scream/src/physics/p3/p3_functions_calc_liq_relaxation_timescale_impl.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_functions_table3_impl.hpp
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_calc_liq_relaxation_timescale_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_dsd2_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_ice_collection_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_rain_sed_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_table3_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: AT: AUTOMERGE, B4B, p3

#307 BFB porting of droplet_activation function to scream
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/scripts/test_all_scream.py
  components/scream/scripts/utils.py
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_constants.hpp
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_droplet_activation.cpp
  components/scream/src/physics/p3/p3_functions_droplet_activation_impl.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_functions_ice_nucleation_impl.hpp
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_droplet_activation_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_ice_nucleation_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: AT: AUTOMERGE, B4B, p3

#268 P3 Port: Ice Melting
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/scripts/gather_all_data.py
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_constants.hpp
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_functions_ice_melting.cpp
  components/scream/src/physics/p3/p3_functions_ice_melting_impl.hpp
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_ice_melting_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: AT: AUTOMERGE, B4B, p3

#308 Aarondonahue/lc testing
  cime/config/e3sm/machines/config_compilers.xml
  cime/config/e3sm/machines/config_machines.xml
  components/cam/cime_config/testdefs/testmods_dirs/cam/force_smp/shell_commands
  components/cam/src/physics/cam/phys_grid.F90
  components/scream/cmake/YamlCpp.cmake
Labels: AT: AUTOMERGE, Machine File, testing

#309 test-all-scream: quality of life improvements
  components/scream/scripts/test-all-scream
  components/scream/scripts/test_all_scream.py
  components/scream/scripts/utils.py
Labels: AT: AUTOMERGE

#312 Added bfb_pow function in get_time_space_phys_variables subroutine
  components/cam/src/physics/cam/micro_p3.F90
Labels: Non-B4B, p3

#310 gather-all-data: quality of life improvements
  components/scream/scripts/gather-all-data
  components/scream/scripts/gather_all_data.py
  components/scream/scripts/test-all-scream
  components/scream/scripts/utils.py
Labels: AT: AUTOMERGE

#318 SHOC modified length scale
  components/cam/src/physics/cam/shoc.F90
Labels: AT: AUTOMERGE, Non-B4B, shoc

#302 SCREAM: more std-like handling of exceptions.
  components/scream/src/share/scream_assert.cpp
  components/scream/src/share/scream_assert.hpp
  components/scream/src/share/scream_session.cpp
  components/scream/src/share/tests/CMakeLists.txt
  components/scream/src/share/tests/debug_tools_tests.cpp
  components/scream/src/share/util/scream_arch.cpp
  components/scream/src/share/util/scream_arch.hpp
Labels: AT: AUTOMERGE, infrastructure

#305 Update SCREAM compsets
  cime/config/e3sm/config_grids.xml
  cime/src/drivers/mct/cime_config/config_component_e3sm.xml
  components/cam/bld/namelist_files/namelist_defaults_cam.xml
  components/cam/bld/namelist_files/use_cases/2000_scream_hr.xml
  components/cam/bld/namelist_files/use_cases/2000_scream_lr.xml
  components/cam/cime_config/config_component.xml
  components/cam/cime_config/config_compsets.xml
  components/clm/bld/namelist_files/namelist_defaults_clm4_5.xml
Labels: AT: AUTOMERGE

#313 Capability to Output Data to Create Prescribed Aerosol Forcing
  components/cam/bld/namelist_files/namelist_defaults_cam.xml
  components/cam/bld/namelist_files/namelist_definition.xml
  components/cam/src/chemistry/modal_aero/aero_model.F90
  components/cam/src/chemistry/mozart/mo_chm_diags.F90
  components/cam/src/chemistry/utils/modal_aero_wateruptake.F90
  components/cam/src/physics/cam/phys_control.F90
Labels: AT: AUTOMERGE, B4B, enhancement

#322 Explicitly add -O0 for debug builds
  components/scream/cmake/SetCompilerFlags.cmake
Labels: AT: AUTOMERGE, B4B

#323 Add missing returns
  components/cam/src/physics/cam/micro_p3.F90
Labels: AT: AUTOMERGE

#316 Ports get_time_space_phys_variables subroutine
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_constants.hpp
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_calc_rime_density_impl.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_functions_get_time_space_phys_variables.cpp
  components/scream/src/physics/p3/p3_functions_get_time_space_phys_variables_impl.hpp
  components/scream/src/physics/p3/tests/p3_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: AT: AUTOMERGE, B4B, p3

#210 IOP-SCREAM infrastructure
  cime/src/components/data_comps/docn/mct/docn_comp_mod.F90
  cime/src/components/data_comps/docn/mct/ocn_comp_mct.F90
  cime/src/drivers/mct/cime_config/config_component.xml
  cime/src/drivers/mct/cime_config/namelist_definition_drv.xml
  cime/src/drivers/mct/main/cime_comp_mod.F90
  cime/src/drivers/mct/shr/seq_infodata_mod.F90
  cime/src/share/streams/shr_dmodel_mod.F90
  cime/src/share/streams/shr_strdata_mod.F90
  cime/src/share/util/shr_scam_mod.F90
  components/cam/bld/build-namelist
  components/cam/bld/config_files/definition.xml
  components/cam/bld/configure
  components/cam/bld/namelist_files/namelist_defaults_cam.xml
  components/cam/bld/namelist_files/namelist_definition.xml
  components/cam/src/control/forecast.F90
  components/cam/src/control/history_scam.F90
  components/cam/src/control/ncdio_atm.F90
  components/cam/src/control/physconst.F90
  components/cam/src/control/runtime_opts.F90
  components/cam/src/control/scamMod.F90
  components/cam/src/cpl/atm_comp_mct.F90
  components/cam/src/dynamics/se/dyn_comp.F90
  components/cam/src/dynamics/se/dyn_grid.F90
  components/cam/src/dynamics/se/inidat.F90
  components/cam/src/dynamics/se/se_single_column_mod.F90
  components/cam/src/dynamics/se/stepon.F90
  components/cam/src/physics/cam/phys_grid.F90
  components/cam/src/physics/cam/shoc_intr.F90
  components/cice/src/drivers/cpl/ice_comp_mct.F90
  components/cice/src/drivers/cpl/ice_scam.F90
  components/cice/src/source/ice_grid.F90
  components/clm/src/cpl/lnd_comp_mct.F90
  components/clm/src/main/clm_varctl.F90
  components/clm/src/main/ncdio_pio.F90.in
Labels: AT: AUTOMERGE, B4B, I/O, infrastructure
