Repository E3SM-Project/scream, pull requests merged in 2020-04, with the labels that each got.

#330 Minor fixes and changes
  components/scream/scripts/jenkins/jenkins_common.sh
  components/scream/scripts/test_all_scream.py
  components/scream/scripts/utils.py
Labels: AT: AUTOMERGE

#303 Shoc porting testbed
  components/cam/src/physics/cam/bfb_math.inc
  components/cam/src/physics/cam/micro_p3.F90
  components/cam/src/physics/cam/micro_p3_utils.F90
  components/cam/src/physics/cam/shoc.F90
  components/scream/src/physics/CMakeLists.txt
  components/scream/src/physics/common/CMakeLists.txt
  components/scream/src/physics/common/physics_common.cpp
  components/scream/src/physics/common/physics_common.hpp
  components/scream/src/physics/common/physics_common_iso_f.F90
  components/scream/src/physics/common/physics_constants.hpp
  components/scream/src/physics/common/physics_utils.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/p3_f90.cpp
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_conservation_impl.hpp
  components/scream/src/physics/p3/p3_functions_dsd2_impl.hpp
  components/scream/src/physics/p3/p3_functions_evaporate_sublimate_precip_impl.hpp
  components/scream/src/physics/p3/p3_functions_get_time_space_phys_variables_impl.hpp
  components/scream/src/physics/p3/p3_functions_ice_deposition_sublimation_impl.hpp
  components/scream/src/physics/p3/p3_functions_update_prognostics_impl.hpp
  components/scream/src/physics/p3/p3_ic_cases.cpp
  components/scream/src/physics/p3/scream_p3_interface.F90
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/shoc/CMakeLists.txt
  components/scream/src/physics/shoc/scream_shoc_interface.F90
  components/scream/src/physics/shoc/shoc.cpp
  components/scream/src/physics/shoc/shoc.hpp
  components/scream/src/physics/shoc/shoc_f90.cpp
  components/scream/src/physics/shoc/shoc_f90.hpp
  components/scream/src/physics/shoc/shoc_functions.hpp
  components/scream/src/physics/shoc/shoc_functions_f90.cpp
  components/scream/src/physics/shoc/shoc_functions_f90.hpp
  components/scream/src/physics/shoc/shoc_ic_cases.cpp
  components/scream/src/physics/shoc/shoc_ic_cases.hpp
  components/scream/src/physics/shoc/shoc_iso_c.f90
  components/scream/src/physics/shoc/shoc_iso_f.f90
  components/scream/src/physics/shoc/tests/CMakeLists.txt
  components/scream/src/physics/shoc/tests/shoc_run_and_cmp.cpp
  components/scream/src/physics/shoc/tests/shoc_stand_alone.cpp
  components/scream/src/physics/shoc/tests/shoc_tests.cpp
  components/scream/src/physics/shoc/tests/shoc_unit_tests.cpp
  components/scream/src/physics/shoc/tests/shoc_unit_tests_common.hpp
  components/scream/src/share/util/scream_utils.hpp
Labels: Non-B4B, shoc

#311 BFB porting checkvalues to scream
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_check_values.cpp
  components/scream/src/physics/p3/p3_functions_check_values_impl.hpp
  components/scream/src/physics/p3/p3_functions_evaporate_sublimate_precip_impl.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_functions_ice_deposition_sublimation_impl.hpp
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_check_values_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: AT: AUTOMERGE, B4B, p3

#339 Move physics_utils to support SCREAM-LR build.
  components/cam/src/physics/cam/physics_utils.F90
  components/scream/src/physics/common/CMakeLists.txt
Labels: AT: AUTOMERGE, B4B

#341 fix the c++ warning messages
  components/scream/src/physics/p3/p3_functions_get_time_space_phys_variables_impl.hpp
Labels: AT: AUTOMERGE, B4B, p3

#336 porting get_latent_heat to scream
  components/cam/src/physics/cam/micro_p3.F90
  components/cam/src/physics/cam/micro_p3_utils.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_functions_get_latent_heat.cpp
  components/scream/src/physics/p3/p3_functions_get_latent_heat_impl.hpp
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_get_latent_heat_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: AT: AUTOMERGE, B4B, p3

#343 Add explicit cxx and f90 versions of the p3_run_and_cmp test
  components/scream/CMakeLists.txt
  components/scream/src/physics/p3/tests/CMakeLists.txt
Labels: AT: AUTOMERGE, testing

#335 Fix broken saturation unit tests
  components/scream/src/physics/common/physics_constants.hpp
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_math_impl.hpp
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_saturation_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: AT: AUTOMERGE, B4B, infrastructure

#346 Fixes a bug in how the tendency for rimed ice mass is handled in P3.
  components/cam/src/physics/cam/micro_p3_interface.F90
Labels: Non-B4B, bug, p3

#349 Add dummy RRTMGP standalone test
  components/scream/src/physics/rrtmgp/CMakeLists.txt
  components/scream/src/physics/rrtmgp/rrtmgp.cpp
  components/scream/src/physics/rrtmgp/rrtmgp.hpp
  components/scream/tests/CMakeLists.txt
  components/scream/tests/rrtmgp/CMakeLists.txt
  components/scream/tests/rrtmgp/rrtmgp_stand_alone.cpp
Labels: AT: AUTOMERGE, B4B, radiation
