Repository E3SM-Project/scream, pull requests merged in 2020-11, with the labels that each got.

#710 Populate RRTMGP optical property outputs
  components/eam/src/physics/rrtmg/radiation.F90
  components/eam/src/physics/rrtmgp/radiation.F90
Labels: B4B

#711 Rename U10 Outfld
  components/eam/src/physics/cam/cam_diagnostics.F90
Labels: CI: Integrate Without Testing, I/O

#712 v0: RH output on pressure levels was broken
  components/eam/src/physics/cam/cam_diagnostics.F90
Labels: CI: Integrate Without Testing, bugfix

#716 Some mods to the grids classes, notably SEGrid
  components/scream/src/control/tests/dummy_atm_setup.hpp
  components/scream/src/control/tests/dummy_grid.hpp
  components/scream/src/physics/share/physics_only_grids_manager.cpp
  components/scream/src/share/CMakeLists.txt
  components/scream/src/share/field/field_monotonicity_check.hpp
  components/scream/src/share/grid/abstract_grid.hpp
  components/scream/src/share/grid/grid_utils.hpp
  components/scream/src/share/grid/point_grid.cpp
  components/scream/src/share/grid/point_grid.hpp
  components/scream/src/share/grid/se_grid.cpp
  components/scream/src/share/grid/se_grid.hpp
  components/scream/src/share/grid/simple_grid.cpp
  components/scream/src/share/grid/simple_grid.hpp
  components/scream/src/share/tests/atm_process_tests.cpp
  components/scream/src/share/tests/dummy_se_point_remapper.hpp
  components/scream/src/share/tests/field_tests.cpp
  components/scream/src/share/tests/grid_tests.cpp
Labels: AT: AUTOMERGE, infrastructure

#715 Fix warning in p3_run_and_cmp
  components/scream/src/physics/p3/tests/p3_run_and_cmp.cpp
Labels: AT: AUTOMERGE, code cleanup, p3

#717 Port dp_inverse and compute_tmpi
  components/eam/src/physics/cam/shoc.F90
  components/scream/src/physics/shoc/CMakeLists.txt
  components/scream/src/physics/shoc/shoc_compute_tmpi.cpp
  components/scream/src/physics/shoc/shoc_compute_tmpi_impl.hpp
  components/scream/src/physics/shoc/shoc_dp_inverse.cpp
  components/scream/src/physics/shoc/shoc_dp_inverse_impl.hpp
  components/scream/src/physics/shoc/shoc_functions.hpp
  components/scream/src/physics/shoc/shoc_functions_f90.cpp
  components/scream/src/physics/shoc/shoc_functions_f90.hpp
  components/scream/src/physics/shoc/shoc_iso_f.f90
  components/scream/src/physics/shoc/tests/shoc_impli_comp_tmpi_tests.cpp
  components/scream/src/physics/shoc/tests/shoc_impli_dp_inverse_tests.cpp
Labels: AT: AUTOMERGE, B4B, shoc

#721 Set prescribed aerosol noise to zero and add bc_dep_to_snow_updates to scream compsets
  components/eam/cime_config/config_component.xml
  components/eam/src/chemistry/utils/prescribed_aero.F90
Labels: AT: AUTOMERGE, Non-B4B

#718 Add more structured support for f90 compilers in testing scripts
  components/scream/scripts/gather-all-data
  components/scream/scripts/gather_all_data.py
  components/scream/scripts/machines_specs.py
  components/scream/scripts/test-all-scream
  components/scream/scripts/test_all_scream.py
Labels: AT: AUTOMERGE, enhancement, testing

#706 SHOC Implicit diffusion upper level property tests
  components/scream/scripts/gen_boiler.py
  components/scream/src/physics/shoc/shoc_functions_f90.hpp
  components/scream/src/physics/shoc/tests/shoc_update_prognostics_implicit_tests.cpp
Labels: AT: AUTOMERGE, B4B, shoc, testing

#720 porting shoc_diag_second_moments_impl function
  components/eam/src/physics/cam/shoc.F90
  components/scream/src/physics/shoc/shoc_diag_second_moments_impl.hpp
  components/scream/src/physics/shoc/shoc_diag_second_shoc_moments_impl.hpp
  components/scream/src/physics/shoc/shoc_functions.hpp
  components/scream/src/physics/shoc/shoc_functions_f90.cpp
  components/scream/src/physics/shoc/shoc_functions_f90.hpp
  components/scream/src/physics/shoc/shoc_iso_c.f90
  components/scream/src/physics/shoc/shoc_iso_f.f90
  components/scream/src/physics/shoc/tests/shoc_diag_second_moments_tests.cpp
Labels: AT: AUTOMERGE, B4B, shoc

#719 Added a Python script that converts a CF standards XML file to a YAML file.
  components/scream/data/cf-standard-name-table.yaml
  components/scream/scripts/cf-xml-to-yaml
  components/scream/src/share/CMakeLists.txt
Labels: AT: AUTOMERGE, Atmosphere Driver, CI: Integrate Without Testing

#725 Fix missing shoc_main intents and gen-boiler
  components/eam/src/physics/cam/shoc.F90
  components/scream/scripts/gen_boiler.py
  components/scream/src/physics/shoc/CMakeLists.txt
  components/scream/src/physics/shoc/shoc_functions.hpp
  components/scream/src/physics/shoc/shoc_functions_f90.cpp
  components/scream/src/physics/shoc/shoc_functions_f90.hpp
  components/scream/src/physics/shoc/shoc_iso_f.f90
  components/scream/src/physics/shoc/shoc_shoc_main.cpp
  components/scream/src/physics/shoc/shoc_shoc_main_impl.hpp
  components/scream/src/physics/shoc/tests/CMakeLists.txt
  components/scream/src/physics/shoc/tests/shoc_shoc_main_tests.cpp
  components/scream/src/physics/shoc/tests/shoc_unit_tests_common.hpp
Labels: AT: AUTOMERGE

#726 lc machine support 2020 11 - general mpirun flag addition
  components/scream/CMakeLists.txt
  components/scream/cmake/ScreamUtils.cmake
  components/scream/cmake/machine-files/lassen.cmake
  components/scream/cmake/machine-files/quartz.cmake
  components/scream/cmake/machine-files/summit.cmake
  components/scream/cmake/machine-files/syrah.cmake
  components/scream/scripts/machines_specs.py
Labels: AT: AUTOMERGE, B4B, Machine File, infrastructure

#727 SCREAM: add support for c compiler in test-all-scream
  components/scream/scripts/gather-all-data
  components/scream/scripts/gather_all_data.py
  components/scream/scripts/machines_specs.py
  components/scream/scripts/test-all-scream
  components/scream/scripts/test_all_scream.py
Labels: AT: AUTOMERGE, cmake, testing

#732 Fixes memory leak in calcsize_diag
  components/eam/src/chemistry/utils/modal_aero_calcsize.F90
  components/eam/src/chemistry/utils/modal_aero_wateruptake.F90
  components/eam/src/physics/cam/modal_aer_opt.F90
Labels: B4B

#733 Hack Koby conservation checks into 'dyamond2' branch
  components/eam/src/physics/cam/micro_p3.F90
Labels: bugfix, p3

#735 Get scream scripts working on cori
  components/scream/CMakeLists.txt
  components/scream/cmake/machine-files/cori-knl.cmake
  components/scream/cmake/machine-files/cori.cmake
  components/scream/scripts/machines_specs.py
Labels: AT: AUTOMERGE

#737 Property test for shoc_main
  components/scream/src/physics/shoc/shoc_iso_c.f90
  components/scream/src/physics/shoc/tests/shoc_shoc_main_tests.cpp
Labels: AT: AUTOMERGE, B4B, shoc, testing

#730 Bring scream-homme interface back to life.
  components/homme/CMakeLists.txt
  components/homme/cmake/HommeMacros.cmake
  components/homme/cmake/Kokkos.cmake
  components/homme/src/preqx_kokkos/CMakeLists.txt
  components/homme/src/preqx_kokkos/cxx/cxx_f90_interface_preqx.cpp
  components/homme/src/preqx_kokkos/preqx_f2c_mod.F90
  components/homme/src/preqx_kokkos/prim_driver_mod.F90
  components/homme/src/share/cxx/ElementsGeometry.cpp
  components/homme/src/share/cxx/ElementsGeometry.hpp
  components/homme/src/share/cxx/Hommexx_Session.cpp
  components/homme/src/share/cxx/Hommexx_Session.hpp
  components/homme/src/share/cxx/RemapFunctor.hpp
  components/homme/src/share/cxx/SimulationParams.hpp
  components/homme/src/share/cxx/mpi/BoundaryExchange.hpp
  components/homme/src/share/cxx/prim_cxx_driver_base.F90
  components/homme/src/share/prim_driver_base.F90
  components/homme/src/theta-l_kokkos/CMakeLists.txt
  components/homme/src/theta-l_kokkos/cxx/CaarFunctorImpl.hpp
  components/homme/src/theta-l_kokkos/cxx/Diagnostics.cpp
  components/homme/src/theta-l_kokkos/cxx/DirkFunctorImpl.hpp
  components/homme/src/theta-l_kokkos/cxx/HyperviscosityFunctorImpl.hpp
  components/homme/src/theta-l_kokkos/cxx/cxx_f90_interface_theta.cpp
  components/homme/src/theta-l_kokkos/prim_driver_mod.F90
  components/homme/src/theta-l_kokkos/theta_f2c_mod.F90
  components/homme/test/unit_tests/CMakeLists.txt
  components/scream/CMakeLists.txt
  components/scream/cime_config/config_component.xml
  components/scream/scripts/machines_specs.py
  components/scream/scripts/test-all-scream
  components/scream/scripts/test_all_scream.py
  components/scream/src/control/atmosphere_driver.cpp
  components/scream/src/dynamics/homme/CMakeLists.txt
  components/scream/src/dynamics/homme/atmosphere_dynamics.cpp
  components/scream/src/dynamics/homme/atmosphere_dynamics.hpp
  components/scream/src/dynamics/homme/dynamics_driven_grids_manager.cpp
  components/scream/src/dynamics/homme/homme
  components/scream/src/dynamics/homme/homme_dimensions.hpp
  components/scream/src/dynamics/homme/homme_inputs_initializer.cpp
  components/scream/src/dynamics/homme/homme_inputs_initializer.hpp
  components/scream/src/dynamics/homme/interface/homme_context_mod.F90
  components/scream/src/dynamics/homme/interface/homme_driver_mod.F90
  components/scream/src/dynamics/homme/interface/homme_grid_mod.F90
  components/scream/src/dynamics/homme/interface/homme_inputs_mod.F90
  components/scream/src/dynamics/homme/interface/homme_params_mod.F90
  components/scream/src/dynamics/homme/interface/scream_homme_interface.hpp
  components/scream/src/dynamics/homme/physics_dynamics_remapper.hpp
  components/scream/src/dynamics/homme/scream_homme_interface.F90
  components/scream/src/dynamics/homme/scream_homme_interface.hpp
  components/scream/src/dynamics/homme/tests/CMakeLists.txt
  components/scream/src/dynamics/homme/tests/homme_pd_remap_tests.cpp
  components/scream/src/dynamics/homme/tests/test_geometry_mod.F90
  components/scream/src/mct_coupling/CMakeLists.txt
  components/scream/tests/CMakeLists.txt
  components/scream/tests/scream_homme_dyn_p3/CMakeLists.txt
  components/scream/tests/scream_homme_dyn_p3/homme_p3.cpp
  components/scream/tests/scream_homme_dyn_p3/input.yaml
  components/scream/tests/scream_homme_dyn_ut_nlev72_qsize4/CMakeLists.txt
  components/scream/tests/scream_homme_dyn_ut_nlev72_qsize4/homme_stand_alone.cpp
  components/scream/tests/scream_homme_dyn_ut_nlev72_qsize4/input.yaml
Labels: homme

#738 SCREAM: fix link flags for dynamics lib
  components/scream/src/dynamics/homme/CMakeLists.txt
Labels: AT: AUTOMERGE, bugfix, cmake

#740 use bfb_* calls
  components/eam/src/physics/cam/shoc.F90
Labels: Non-B4B, shoc

#731 Refactor tridiag solver
  components/eam/src/physics/cam/shoc.F90
Labels: Non-B4B, shoc

#744 Fix a rare race condition in shoc_diag_second_moments_impl
  components/scream/src/physics/shoc/shoc_calc_shoc_varorcovar_impl.hpp
  components/scream/src/physics/shoc/shoc_diag_second_moments_impl.hpp
Labels: AT: AUTOMERGE

#745 Machine file fix for the livermore computing machine lassen.
  components/scream/cmake/machine-files/lassen.cmake
  components/scream/scripts/machines_specs.py
Labels: AT: AUTOMERGE, B4B, CI: Integrate Without Testing, Machine File

#741 SCREAM: allow to specify a work dir for test-all-scream
  components/scream/cmake/ctest_script.cmake
  components/scream/scripts/test-all-scream
  components/scream/scripts/test_all_scream.py
Labels: AT: AUTOMERGE, enhancement, testing

#714 Hack Koby's conservation checks into SCREAMv0
  components/eam/src/physics/cam/micro_p3.F90
  components/scream/scripts/gen_boiler.py
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_ice_supersat_conservation.cpp
  components/scream/src/physics/p3/p3_ice_supersat_conservation_impl.hpp
  components/scream/src/physics/p3/p3_iso_c.f90
  components/scream/src/physics/p3/p3_iso_f.f90
  components/scream/src/physics/p3/p3_main_impl.hpp
  components/scream/src/physics/p3/p3_nc_conservation.cpp
  components/scream/src/physics/p3/p3_nc_conservation_impl.hpp
  components/scream/src/physics/p3/p3_ni_conservation.cpp
  components/scream/src/physics/p3/p3_ni_conservation_impl.hpp
  components/scream/src/physics/p3/p3_nr_conservation.cpp
  components/scream/src/physics/p3/p3_nr_conservation_impl.hpp
  components/scream/src/physics/p3/p3_water_vapor_conservation.cpp
  components/scream/src/physics/p3/p3_water_vapor_conservation_impl.hpp
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_ice_supersat_conservation_tests.cpp
  components/scream/src/physics/p3/tests/p3_incloud_mixingratios_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_nc_conservation_tests.cpp
  components/scream/src/physics/p3/tests/p3_ni_conservation_tests.cpp
  components/scream/src/physics/p3/tests/p3_nr_conservation_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
  components/scream/src/physics/p3/tests/p3_water_vapor_conservation_tests.cpp
  components/scream/src/physics/shoc/CMakeLists.txt
  components/scream/src/physics/shoc/shoc_functions.hpp
  components/scream/src/physics/shoc/shoc_functions_f90.hpp
  components/scream/src/physics/shoc/tests/CMakeLists.txt
Labels: Non-B4B, p3

#755 Ports integ_column_stability to C++/Kokkos
  components/eam/src/physics/cam/shoc.F90
  components/scream/src/physics/shoc/CMakeLists.txt
  components/scream/src/physics/shoc/shoc_functions.hpp
  components/scream/src/physics/shoc/shoc_functions_f90.cpp
  components/scream/src/physics/shoc/shoc_functions_f90.hpp
  components/scream/src/physics/shoc/shoc_integ_column_stability.cpp
  components/scream/src/physics/shoc/shoc_integ_column_stability_impl.hpp
  components/scream/src/physics/shoc/shoc_iso_f.f90
  components/scream/src/physics/shoc/tests/shoc_tke_column_stab_tests.cpp
Labels: AT: AUTOMERGE

#753 Fixing bug in scripts/utils.py
  components/scream/scripts/utils.py
Labels: AT: AUTOMERGE, bugfix, scripts, testing

#761 dyamond2 specific: Fix bug where code looks for clm2.r file rather than elm.r for branch runs
  components/elm/cime_config/buildnml
Labels: bugfix

#750 test-all-scream: A few minor fixes
  components/scream/scripts/gather_all_data.py
  components/scream/scripts/machines_specs.py
  components/scream/scripts/test-all-scream
  components/scream/scripts/test_all_scream.py
Labels: AT: AUTOMERGE

#751 Port shoc solver functions
  components/scream/src/physics/shoc/CMakeLists.txt
  components/scream/src/physics/shoc/shoc_functions.hpp
  components/scream/src/physics/shoc/shoc_functions_f90.cpp
  components/scream/src/physics/shoc/shoc_functions_f90.hpp
  components/scream/src/physics/shoc/shoc_iso_c.f90
  components/scream/src/physics/shoc/shoc_iso_f.f90
  components/scream/src/physics/shoc/shoc_tridiag_solver.cpp
  components/scream/src/physics/shoc/shoc_tridiag_solver_impl.hpp
  components/scream/src/physics/shoc/tests/CMakeLists.txt
  components/scream/src/physics/shoc/tests/shoc_unit_tests_common.hpp
  components/scream/src/physics/shoc/tests/shoc_vd_shoc_decomp_and_solve_tests.cpp
Labels: AT: AUTOMERGE, B4B, shoc
