Repository E3SM-Project/scream, pull requests merged in 2020-01, with the labels that each got.

#197 Fix for variable mu_c which is not properly initialized.
  components/cam/src/physics/cam/micro_p3.F90
  components/cam/src/physics/cam/micro_p3_interface.F90
Labels: Non-B4B, bug, p3

#200 Fix p3_stand_alone and p3_shoc_coupled unit tests.
  components/scream/src/physics/p3/atmosphere_microphysics.cpp
  components/scream/src/physics/p3/atmosphere_microphysics.hpp
  components/scream/src/physics/p3/scream_p3_interface.F90
  components/scream/src/physics/p3/scream_p3_interface.hpp
  components/scream/tests/CMakeLists.txt
  components/scream/tests/scream_p3/p3_stand_alone.cpp
  components/scream/tests/scream_p3_shoc/p3_shoc_coupled.cpp
Labels: B4B, bug, p3, testing

#194 Fix a bug in P3 microphysics which still relied on the variable `it`
  components/cam/src/physics/cam/micro_p3.F90
  components/cam/src/physics/cam/micro_p3_interface.F90
Labels: AT: AUTOMERGE, bug, p3

#199 add pow operator for exponential calculation
  components/scream/src/share/scream_pack.hpp
  components/scream/src/share/tests/pack_tests.cpp
Labels: B4B, p3

#203 Improve packs testing.
  components/scream/src/share/tests/pack_tests.cpp
Labels: AT: AUTOMERGE

#205 Improve CIMEs handling of scream data
  components/scream/cime_config/buildnml
Labels: B4B, enhancement

#207 Aarondonahue/scream atm mct
  cime/config/e3sm/machines/config_compilers.xml
  components/scream/src/control/tests/dummy_grid.hpp
  components/scream/src/interface/CMakeLists.txt
  components/scream/src/interface/ScreamContext.hpp
  components/scream/src/interface/atm_comp_mct.F90
  components/scream/src/interface/dead_data_mod.F90
  components/scream/src/interface/dead_mct_mod.F90
  components/scream/src/interface/dead_mod.F90
  components/scream/src/interface/scream_cxx_f90_interface.cpp
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/p3_f90.cpp
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/scream_p3_interface.F90
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/share/scream_session.cpp
  components/scream/src/share/scream_session.hpp
  components/scream/tests/scream_p3/CMakeLists.txt
  components/scream/tests/scream_p3_shoc/CMakeLists.txt
Labels: B4B, enhancement, infrastructure, p3, shoc

#206 Add option for only making scream libraries
  components/scream/CMakeLists.txt
  components/scream/src/control/CMakeLists.txt
  components/scream/src/dynamics/homme/CMakeLists.txt
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/rrtmgp/CMakeLists.txt
  components/scream/src/physics/shoc/CMakeLists.txt
  components/scream/src/share/CMakeLists.txt
Labels: AT: AUTOMERGE

#190 Update_prognostic_ice subroutine port
  components/cam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/micro_p3_iso_f.f90
  components/scream/src/physics/p3/p3_constants.hpp
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_functions_update_prognostics.cpp
  components/scream/src/physics/p3/p3_functions_update_prognostics_impl.hpp
  components/scream/src/physics/p3/tests/p3_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
Labels: B4B, p3

#211 Jgfouca/upstream merge 2020 01 29
  cime/config/e3sm/config_grids.xml
  components/cam/bld/namelist_files/namelist_defaults_cam.xml
  components/cam/cime_config/testdefs/testmods_dirs/cam/preqx_ftype1/shell_commands
  components/cam/src/dynamics/se/dp_coupling.F90
  components/cam/src/dynamics/se/dyn_comp.F90
  components/cam/src/dynamics/se/inidat.F90
  components/cam/src/dynamics/se/interp_mod.F90
  components/cam/src/dynamics/se/stepon.F90
  components/cam/src/physics/cam/check_energy.F90
  components/cam/src/physics/cam/clubb_intr.F90
  components/cam/src/physics/cam/geopotential.F90
  components/cam/src/physics/cam/gw_drag.F90
  components/cam/src/physics/cam/physics_types.F90
  components/cam/src/physics/cam/physpkg.F90
  components/cam/tools/topo_tool/cube_to_target/cube_to_target.F90
  components/cam/tools/topo_tool/cube_to_target/remap.F90
  components/homme/src/interpolate_driver_mod.F90
  components/homme/src/share/compose/compose_cedr.cpp
  components/homme/src/share/compose/compose_slmm.cpp
  components/homme/src/share/compose_mod.F90
  components/homme/src/share/compose_test_mod.F90
  components/homme/src/share/gllfvremap_mod.F90
  components/homme/src/share/gllfvremap_util_mod.F90
  components/homme/src/share/prim_driver_base.F90
  components/homme/src/share/sl_advection.F90
  components/homme/src/share/vertremap_base.F90
  components/homme/src/theta-l/prim_state_mod.F90
  components/homme/src/tool/tool_main.F90
Labels: AT: AUTOMERGE

#212 Update the P3 debug warnings
  components/cam/src/physics/cam/micro_p3.F90
  components/cam/src/physics/cam/micro_p3_interface.F90
  components/scream/src/physics/p3/micro_p3_iso_c.f90
  components/scream/src/physics/p3/scream_p3_interface.F90
Labels: AT: AUTOMERGE, B4B, p3

#213 Add additional temperature debugging for RRTMGP
  components/cam/bld/namelist_files/namelist_defaults_cam.xml
  components/cam/bld/namelist_files/namelist_definition.xml
  components/cam/src/physics/rrtmgp/cloud_rad_props.F90
  components/cam/src/physics/rrtmgp/radiation.F90
  components/cam/src/physics/rrtmgp/radiation_utils.F90
Labels: AT: AUTOMERGE, B4B, radiation
