Repository E3SM-Project/scream, pull requests merged in 2021-01, with the labels that each got.

#851 use cbrt instead of bfb_pow
  components/eam/src/physics/cam/shoc.F90
  components/scream/src/physics/shoc/shoc_pblintd_surf_temp_impl.hpp
Labels: AT: AUTOMERGE, shoc

#853 Port pblintd
  components/eam/src/physics/cam/shoc.F90
  components/scream/src/physics/shoc/CMakeLists.txt
  components/scream/src/physics/shoc/shoc_functions.hpp
  components/scream/src/physics/shoc/shoc_functions_f90.cpp
  components/scream/src/physics/shoc/shoc_functions_f90.hpp
  components/scream/src/physics/shoc/shoc_iso_c.f90
  components/scream/src/physics/shoc/shoc_iso_f.f90
  components/scream/src/physics/shoc/shoc_pblintd_height_impl.hpp
  components/scream/src/physics/shoc/shoc_pblintd_impl.hpp
  components/scream/src/physics/shoc/shoc_pblintd_init.cpp
  components/scream/src/physics/shoc/shoc_pblintd_init_impl.hpp
  components/scream/src/physics/shoc/shoc_pblintd_init_pot_impl.hpp
  components/scream/src/physics/shoc/shoc_pblintd_surf_temp_impl.hpp
  components/scream/src/physics/shoc/tests/CMakeLists.txt
  components/scream/src/physics/shoc/tests/shoc_pblintd_height_tests.cpp
  components/scream/src/physics/shoc/tests/shoc_pblintd_init_tests.cpp
  components/scream/src/physics/shoc/tests/shoc_pblintd_tests.cpp
  components/scream/src/physics/shoc/tests/shoc_unit_tests_common.hpp
Labels: AT: AUTOMERGE, B4B, shoc

#854 Quick fix to a build error where the variable "thrd" was not defined in the bfb_math.inc file
  components/eam/src/physics/cam/bfb_math.inc
Labels: AT: AUTOMERGE, B4B, bugfix

#852 output fix for SCREAM SCM
  components/eam/src/dynamics/se/se_single_column_mod.F90
Labels: AT: AUTOMERGE, B4B, bugfix

#856 Port shoc_main
  components/eam/src/physics/cam/shoc.F90
  components/scream/src/physics/shoc/CMakeLists.txt
  components/scream/src/physics/shoc/shoc_assumed_pdf_impl.hpp
  components/scream/src/physics/shoc/shoc_constants.hpp
  components/scream/src/physics/shoc/shoc_energy_fixer_impl.hpp
  components/scream/src/physics/shoc/shoc_functions.hpp
  components/scream/src/physics/shoc/shoc_functions_f90.cpp
  components/scream/src/physics/shoc/shoc_functions_f90.hpp
  components/scream/src/physics/shoc/shoc_length_impl.hpp
  components/scream/src/physics/shoc/shoc_main.cpp
  components/scream/src/physics/shoc/shoc_main_impl.hpp
  components/scream/src/physics/shoc/shoc_shoc_main_impl.hpp
  components/scream/src/physics/shoc/tests/CMakeLists.txt
  components/scream/src/physics/shoc/tests/shoc_assumed_pdf_tests.cpp
  components/scream/src/physics/shoc/tests/shoc_main_tests.cpp
Labels: AT: AUTOMERGE, B4B, shoc

#863 Move scream_config.h config later in file
  components/scream/CMakeLists.txt
Labels: AT: AUTOMERGE

#804 Refactor P3-AD interface to call only C++ version of P3
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/atmosphere_microphysics.cpp
  components/scream/src/physics/p3/atmosphere_microphysics.hpp
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_inputs_initializer.cpp
  components/scream/src/physics/p3/scream_p3_interface.F90
  components/scream/src/physics/p3/scream_p3_interface.hpp
  components/scream/tests/scream_p3/CMakeLists.txt
  components/scream/tests/scream_p3/input.yaml
  components/scream/tests/scream_p3/p3_init_vals.txt
  components/scream/tests/scream_p3/p3_stand_alone.cpp
  components/scream/tests/scream_p3_shoc/CMakeLists.txt
  components/scream/tests/scream_p3_shoc/p3_init_vals.txt
  components/scream/tests/scream_p3_shoc/p3_shoc_coupled.cpp
Labels: AT: AUTOMERGE, Atmosphere Driver, B4B, p3

#868 Add an python utility to ensure pyyaml availability
  components/scream/scripts/utils.py
Labels: AT: AUTOMERGE

#867 ni2nr_melt_tend tendency should be multiplied by nmltratio in conserv…
  components/eam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_iso_c.f90
  components/scream/src/physics/p3/p3_main_impl.hpp
  components/scream/src/physics/p3/p3_nr_conservation_impl.hpp
  components/scream/src/physics/p3/tests/p3_nr_conservation_tests.cpp
Labels: AT: AUTOMERGE, Non-B4B, bugfix, p3
