Repository E3SM-Project/scream, pull requests merged in 2021-08, with the labels that each got.

#1142 Change exner to inv_exner in SHOC
  components/eam/src/physics/cam/shoc.F90
  components/scream/src/physics/shoc/atmosphere_macrophysics.cpp
  components/scream/src/physics/shoc/atmosphere_macrophysics.hpp
  components/scream/src/physics/shoc/shoc_f90.cpp
  components/scream/src/physics/shoc/shoc_f90.hpp
  components/scream/src/physics/shoc/shoc_functions.hpp
  components/scream/src/physics/shoc/shoc_functions_f90.cpp
  components/scream/src/physics/shoc/shoc_functions_f90.hpp
  components/scream/src/physics/shoc/shoc_ic_cases.cpp
  components/scream/src/physics/shoc/shoc_iso_c.f90
  components/scream/src/physics/shoc/shoc_iso_f.f90
  components/scream/src/physics/shoc/shoc_main_impl.hpp
  components/scream/src/physics/shoc/shoc_update_host_dse_impl.hpp
  components/scream/src/physics/shoc/tests/shoc_energy_update_dse_tests.cpp
  components/scream/src/physics/shoc/tests/shoc_main_tests.cpp
Labels: shoc

#1128 Add import/export in SurfaceCouplingfor SCREAM variable
  components/scream/src/control/surface_coupling.cpp
  components/scream/src/control/surface_coupling.hpp
  components/scream/src/control/tests/sc_tests.cpp
  components/scream/src/mct_coupling/atm_comp_mct.F90
  components/scream/src/mct_coupling/scream_cpl_indices.F90
  components/scream/src/mct_coupling/scream_cxx_f90_interface.cpp
  components/scream/src/mct_coupling/scream_f2c_mod.F90
Labels: AT: AUTOMERGE

#1147 Some changes to how we extract a kokkos view from a Field.
  components/scream/src/control/surface_coupling.cpp
  components/scream/src/control/tests/ad_tests.cpp
  components/scream/src/control/tests/dummy_atm_proc.hpp
  components/scream/src/control/tests/sc_tests.cpp
  components/scream/src/dynamics/homme/atmosphere_dynamics.cpp
  components/scream/src/dynamics/homme/physics_dynamics_remapper.hpp
  components/scream/src/dynamics/homme/tests/homme_pd_remap_tests.cpp
  components/scream/src/physics/cld_fraction/atmosphere_cld_fraction.cpp
  components/scream/src/physics/p3/atmosphere_microphysics.cpp
  components/scream/src/physics/p3/atmosphere_microphysics.hpp
  components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp
  components/scream/src/physics/rrtmgp/atmosphere_radiation.hpp
  components/scream/src/physics/shoc/atmosphere_macrophysics.cpp
  components/scream/src/share/atm_process/atmosphere_process.hpp
  components/scream/src/share/field/field.hpp
  components/scream/src/share/field/field_alloc_prop.hpp
  components/scream/src/share/field/field_property_checks/field_monotonicity_check.hpp
  components/scream/src/share/field/field_property_checks/field_nan_check.hpp
  components/scream/src/share/field/field_property_checks/field_positivity_check.hpp
  components/scream/src/share/field/field_property_checks/field_within_interval_check.hpp
  components/scream/src/share/field/field_utils.hpp
  components/scream/src/share/io/scorpio_input.cpp
  components/scream/src/share/io/scorpio_input.hpp
  components/scream/src/share/io/scorpio_output.cpp
  components/scream/src/share/io/tests/io.cpp
  components/scream/src/share/io/tests/restart.cpp
  components/scream/src/share/tests/field_tests.cpp
  components/scream/tests/uncoupled/cld_fraction/cld_fraction_stand_alone.cpp
  components/scream/tests/uncoupled/rrtmgp/rrtmgp_stand_alone.cpp
Labels: infrastructure, B4B, AT: AUTOMERGE, code cleanup

#1156 mct-coupling changes
  components/scream/src/control/atmosphere_driver.hpp
  components/scream/src/control/surface_coupling.cpp
  components/scream/src/mct_coupling/CMakeLists.txt
  components/scream/src/mct_coupling/atm_comp_mct.F90
  components/scream/src/mct_coupling/scream_cpl_indices.F90
  components/scream/src/mct_coupling/scream_cxx_f90_interface.cpp
  components/scream/src/mct_coupling/scream_f2c_mod.F90
Labels: AT: AUTOMERGE

#1087 P3 - Recent Fixes/Changes in P3
  components/eam/src/physics/cam/micro_p3.F90
  components/eam/src/physics/cam/micro_p3_utils.F90
  components/scream/src/physics/p3/p3_get_time_space_phys_variables_impl.hpp
  components/scream/src/physics/p3/p3_ice_collection_impl.hpp
  components/scream/src/physics/share/physics_constants.hpp
Labels: Non-B4B, p3, AT: AUTOMERGE, bugfix

#1131 Add bi-grid support for ne1024pg2 and update lnd io modules for ultra hires
  cime_config/config_grids.xml
  components/elm/bld/namelist_files/namelist_defaults.xml
  components/elm/bld/namelist_files/namelist_definition.xml
  components/elm/src/cpl/lnd_comp_mct.F90
  components/elm/src/main/elm_instance.F90
  components/elm/src/main/ncdio_pio.F90.in
Labels: B4B, I/O, AT: AUTOMERGE

#1163 Update machine specs for LC machine syrah to avoid timing out during nightly tests
  components/scream/scripts/machines_specs.py
Labels: Machine File, AT: AUTOMERGE, AT: Integrate Without Testing

#1166 Remove outdated F2000 SCREAM compsets
  components/eam/bld/namelist_files/use_cases/2000_scream_hr.xml
  components/eam/bld/namelist_files/use_cases/2000_scream_lr.xml
  components/eam/cime_config/config_component.xml
  components/eam/cime_config/config_compsets.xml
Labels: AT: AUTOMERGE
