Repository E3SM-Project/scream, pull requests merged in 2021-07, with the labels that each got.

#1099 SCREAM: fix usage of CudaWrap structs
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/share/physics_share.cpp
Labels: B4B, bugfix

#1100 Changes equal to approx equal for wet<-->dry mmr test
  components/scream/src/share/tests/common_physics_functions_tests.cpp
Labels: AT: AUTOMERGE, bugfix, physics

#1103 Add precip_liq_surf to FM
  components/scream/src/physics/p3/atmosphere_microphysics.cpp
  components/scream/src/physics/p3/atmosphere_microphysics.hpp
Labels: AT: AUTOMERGE, Atmosphere Driver, p3

#1105 fix warning for previous PR
  components/homme/src/theta-l_kokkos/cxx/HyperviscosityFunctorImpl.cpp
Labels: AT: AUTOMERGE

#1086 DP-SCREAM nightly test fix
  cime_config/tests.py
Labels: AT: AUTOMERGE, B4B, CIME, bugfix

#1106 Enable core dumps on blake
  components/scream/src/physics/shoc/shoc_main_impl.hpp
Labels: AT: AUTOMERGE

#1114 fix in cloud bug for nc
  components/eam/src/physics/cam/micro_p3.F90
  components/eam/src/physics/cam/micro_p3_interface.F90
Labels: AT: AUTOMERGE

#1078 DP-SCREAM DOCN index bug fix
  share/streams/shr_dmodel_mod.F90
Labels: AT: AUTOMERGE, B4B, bugfix

#1110 Turn off bash '-e' settings for nightlies
  components/scream/scripts/jenkins/jenkins_common_impl.sh
Labels: AT: AUTOMERGE

#1111 Improve Kokkos bounds checking situation
  components/scream/CMakeLists.txt
  components/scream/scripts/scripts-tests
  components/scream/src/physics/shoc/shoc_compute_diag_third_shoc_moment_impl.hpp
  components/scream/src/share/tests/field_tests.cpp
  components/scream/tests/CMakeLists.txt
  components/scream/tests/infra/CMakeLists.txt
  components/scream/tests/infra/fake_test.cpp
Labels: AT: AUTOMERGE

#1116 DP-SCREAM cloud liquid initialization fix
  components/eam/src/dynamics/se/se_single_column_mod.F90
Labels: AT: AUTOMERGE, B4B, bugfix

#1118 Fix #1108.
  components/scream/src/dynamics/homme/CMakeLists.txt
  components/scream/src/physics/rrtmgp/tests/rrtmgp_test_utils.cpp
  components/scream/src/physics/shoc/tests/shoc_pblintd_check_pblh_tests.cpp
  components/scream/src/physics/shoc/tests/shoc_pblintd_height_tests.cpp
  components/scream/src/physics/shoc/tests/shoc_pblintd_surf_temp_tests.cpp
  components/scream/src/physics/shoc/tests/shoc_pblintd_tests.cpp
  components/scream/src/share/tests/common_physics_functions_tests.cpp
Labels: AT: AUTOMERGE

#1121 Encapsulate SCREAM Jenkins AT job cleanup
  components/scream/scripts/jenkins/jenkins_cleanup.sh
Labels: AT: Integrate Without Testing

#1122 Fixes for scream Jenkins cleanup
  components/scream/scripts/jenkins/jenkins_cleanup.sh
  components/scream/scripts/jenkins/jenkins_cleanup_impl.sh
Labels: AT: Integrate Without Testing

#1124 Quick fix for coupled stand-alone tests and machine config file
  cime_config/machines/config_machines.xml
  components/scream/tests/coupled/homme_physics/input.yaml
  components/scream/tests/coupled/shoc_cld_p3_rrtmgp/input.yaml
Labels: AT: AUTOMERGE, AT: Integrate Without Testing, B4B, Machine File, bugfix, priority:high, testing

#1125 Add script for querying CIME's config_machines.xml
  components/scream/cime_config/buildnml
  components/scream/scripts/query-cime
  components/scream/scripts/query_cime.py
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#1126 Final touches to get things building and running on LC machines
  cime_config/machines/config_compilers.xml
  components/scream/cmake/machine-files/quartz.cmake
  components/scream/cmake/machine-files/syrah.cmake
  components/scream/scripts/machines_specs.py
Labels: AT: AUTOMERGE, B4B, Machine File, testing

#1127 Response to review comments by @bartgol on #1112 and #1115
  components/scream/src/control/atmosphere_driver.cpp
  components/scream/src/physics/share/physics_constants.hpp
  components/scream/src/share/field/field_property_checks/field_nan_check.hpp
  components/scream/tests/coupled/homme_physics/CMakeLists.txt
  components/scream/tests/coupled/homme_physics/homme_shoc_cld_p3_rrtmgp.cpp
Labels: AT: AUTOMERGE, Atmosphere Driver, B4B, code cleanup, code quality, homme, physics, testing

#1130 update gcc version for lassen
  components/scream/scripts/machines_specs.py
Labels: AT: AUTOMERGE, AT: Integrate Without Testing, Machine File

#1132 Replace SROF with MOSART for the F compsets
  components/eam/cime_config/config_compsets.xml
Labels: B4B

#1129 Only compute SW radiative fluxes for daytime columns
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.cpp
  components/scream/tests/coupled/shoc_cld_p3_rrtmgp/CMakeLists.txt
Labels: AT: AUTOMERGE, physics, radiation

#1136 Hommexx: Fix a Cuda 10, c++14, gcc 7 internal error.
  components/homme/src/share/cxx/mpi/BoundaryExchange.cpp
Labels: AT: AUTOMERGE

#1141 HOMME: remove pointless cmake targets for cxx (homme) targets.
  components/homme/src/preqx_kokkos/CMakeLists.txt
  components/homme/src/theta-l_kokkos/CMakeLists.txt
Labels: AT: AUTOMERGE, cmake, homme

#1143 Allow output of subfields
  components/scream/src/share/io/scorpio_input.cpp
  components/scream/src/share/io/scorpio_output.cpp
  components/scream/src/share/io/scorpio_output.hpp
Labels: AT: AUTOMERGE, B4B, I/O, enhancement
