Repository E3SM-Project/scream, pull requests merged in 2021-10, with the labels that each got.

#1168 Allow scorpio I/O on dynamics grid
  components/scream/src/control/atmosphere_driver.cpp
  components/scream/src/dynamics/homme/dynamics_driven_grids_manager.cpp
  components/scream/src/dynamics/homme/dynamics_driven_grids_manager.hpp
  components/scream/src/dynamics/homme/homme_dimensions.hpp
  components/scream/src/dynamics/homme/interface/homme_grid_mod.F90
  components/scream/src/dynamics/homme/interface/homme_params_mod.F90
  components/scream/src/dynamics/homme/interface/phys_grid_mod.F90
  components/scream/src/dynamics/homme/interface/scream_homme_interface.hpp
  components/scream/src/dynamics/homme/tests/CMakeLists.txt
  components/scream/src/dynamics/homme/tests/dyn_grid_io.cpp
  components/scream/src/dynamics/homme/tests/homme_pd_remap_tests.cpp
  components/scream/src/dynamics/homme/tests/test_helper_mod.F90
  components/scream/src/share/CMakeLists.txt
  components/scream/src/share/field/field_alloc_prop.cpp
  components/scream/src/share/field/field_alloc_prop.hpp
  components/scream/src/share/grid/abstract_grid.cpp
  components/scream/src/share/grid/abstract_grid.hpp
  components/scream/src/share/grid/point_grid.cpp
  components/scream/src/share/grid/point_grid.hpp
  components/scream/src/share/grid/se_grid.cpp
  components/scream/src/share/grid/se_grid.hpp
  components/scream/src/share/io/scorpio_input.cpp
  components/scream/src/share/io/scorpio_input.hpp
  components/scream/src/share/io/scorpio_output.cpp
  components/scream/src/share/io/scorpio_output.hpp
  components/scream/src/share/io/scream_output_manager.cpp
  components/scream/src/share/io/scream_output_manager.hpp
  components/scream/src/share/io/scream_scorpio_interface.F90
  components/scream/src/share/io/scream_scorpio_interface.cpp
  components/scream/src/share/io/scream_scorpio_interface.hpp
  components/scream/src/share/io/scream_scorpio_interface_iso_c2f.F90
  components/scream/src/share/io/tests/CMakeLists.txt
  components/scream/src/share/io/tests/io.cpp
  components/scream/src/share/io/tests/restart.cpp
  components/scream/src/share/tests/CMakeLists.txt
  components/scream/src/share/tests/atm_process_tests.cpp
  components/scream/src/share/tests/grid_tests.cpp
Labels: enhancement, B4B, I/O, AT: AUTOMERGE

#1231 Quick fix of typo impacting timer
  components/eam/src/dynamics/se/dyn_comp.F90
Labels: B4B, AT: AUTOMERGE

#1218 Add diagnostic of SHOC cloud liquid water
  components/eam/src/physics/cam/shoc_intr.F90
Labels: B4B, shoc, AT: AUTOMERGE

#1233 Scorpio read input interface allow for specific time level to be read
  components/scream/src/share/io/scorpio_input.cpp
  components/scream/src/share/io/scorpio_input.hpp
  components/scream/src/share/io/scorpio_output.cpp
  components/scream/src/share/io/scorpio_output.hpp
  components/scream/src/share/io/scream_scorpio_interface.F90
  components/scream/src/share/io/scream_scorpio_interface.cpp
  components/scream/src/share/io/scream_scorpio_interface.hpp
  components/scream/src/share/io/scream_scorpio_interface_iso_c2f.F90
  components/scream/src/share/io/tests/CMakeLists.txt
  components/scream/src/share/io/tests/io.cpp
  components/scream/src/share/io/tests/io_test_multisnap.yaml
Labels: enhancement, I/O, AT: AUTOMERGE, priority:high

#1230 Some mods to GridsManager classes
  components/scream/src/control/atmosphere_driver.cpp
  components/scream/src/dynamics/homme/dynamics_driven_grids_manager.cpp
  components/scream/src/dynamics/homme/dynamics_driven_grids_manager.hpp
  components/scream/src/dynamics/homme/interface/homme_params_mod.F90
  components/scream/src/dynamics/homme/tests/dyn_grid_io.cpp
  components/scream/src/dynamics/homme/tests/homme_pd_remap_tests.cpp
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/atmosphere_microphysics.cpp
  components/scream/src/physics/p3/atmosphere_microphysics_run.cpp
  components/scream/src/physics/register_physics.hpp
  components/scream/src/physics/share/CMakeLists.txt
  components/scream/src/physics/share/physics_only_grids_manager.cpp
  components/scream/src/physics/share/physics_only_grids_manager.hpp
  components/scream/src/share/CMakeLists.txt
  components/scream/src/share/grid/grids_manager.hpp
  components/scream/src/share/grid/mesh_free_grids_manager.cpp
  components/scream/src/share/grid/mesh_free_grids_manager.hpp
  components/scream/src/share/grid/remap/do_nothing_remapper.hpp
  components/scream/src/share/grid/user_provided_grids_manager.hpp
  components/scream/src/share/io/tests/io.cpp
  components/scream/src/share/io/tests/restart.cpp
  components/scream/src/share/tests/atm_process_tests.cpp
  components/scream/src/share/tests/atm_process_tests.yaml
  components/scream/src/share/tests/grid_tests.cpp
  components/scream/tests/coupled/shoc_cld_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/shoc_cld_p3_rrtmgp/shoc_cld_p3_rrtmgp.cpp
  components/scream/tests/uncoupled/cld_fraction/cld_fraction_standalone.cpp
  components/scream/tests/uncoupled/cld_fraction/input.yaml
  components/scream/tests/uncoupled/p3/input.yaml
  components/scream/tests/uncoupled/p3/p3_standalone.cpp
  components/scream/tests/uncoupled/p3/p3_standalone_output.yaml
  components/scream/tests/uncoupled/rrtmgp/CMakeLists.txt
  components/scream/tests/uncoupled/rrtmgp/input.yaml
  components/scream/tests/uncoupled/rrtmgp/rrtmgp_standalone.cpp
  components/scream/tests/uncoupled/shoc/input.yaml
  components/scream/tests/uncoupled/shoc/shoc_standalone.cpp
  components/scream/tests/uncoupled/shoc/shoc_standalone_output.yaml
  components/scream/tests/uncoupled/spa/input.yaml
  components/scream/tests/uncoupled/spa/spa_output.yaml
  components/scream/tests/uncoupled/spa/spa_stand_alone.cpp
  components/scream/tests/uncoupled/zm/input.yaml
  components/scream/tests/uncoupled/zm/zm_standalone.cpp
Labels: infrastructure, AT: AUTOMERGE, code cleanup

#1235 Add F-SCREAM-LR-DYAMOND2-MPASSI and F-SCREAM-HR-DYAMOND2-MPASSI
  components/eam/cime_config/config_compsets.xml
Labels: B4B, AT: AUTOMERGE

#1239 Clean up context mask in p3
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_ice_cldliq_wet_growth_impl.hpp
  components/scream/src/physics/p3/p3_ice_collection_impl.hpp
  components/scream/src/physics/p3/p3_ice_melting_impl.hpp
  components/scream/src/physics/p3/p3_main_impl.hpp
  components/scream/src/physics/p3/p3_prevent_ice_overdepletion_impl.hpp
Labels: p3, AT: AUTOMERGE, bugfix, code cleanup

#1243 Simple fix to all AD based SHOC tests that zero out the surface fluxes.
  components/scream/tests/coupled/homme_physics/input.yaml
  components/scream/tests/coupled/shoc_cld_p3_rrtmgp/input.yaml
  components/scream/tests/uncoupled/shoc/input.yaml
Labels: testing, shoc, AT: AUTOMERGE

#1240 Clean up saturation conservation checks: "Koby fix #2"
  components/eam/src/physics/cam/micro_p3.F90
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_ice_cldliq_wet_growth_impl.hpp
  components/scream/src/physics/p3/p3_ice_deposition_sublimation_impl.hpp
  components/scream/src/physics/p3/p3_iso_c.f90
  components/scream/src/physics/p3/p3_iso_f.f90
  components/scream/src/physics/p3/p3_main_impl_part2.hpp
  components/scream/src/physics/p3/p3_prevent_ice_overdepletion.cpp
  components/scream/src/physics/p3/p3_prevent_ice_overdepletion_impl.hpp
  components/scream/src/physics/p3/p3_prevent_liq_supersaturation.cpp
  components/scream/src/physics/p3/p3_prevent_liq_supersaturation_impl.hpp
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_ice_deposition_sublimation_tests.cpp
  components/scream/src/physics/p3/tests/p3_prevent_ice_overdepletion_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_prevent_liq_supersaturation_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_unit_tests_common.hpp
  share/util/shr_sys_mod.F90
Labels: Non-B4B, p3, code cleanup

#1262 SCREAM: fix test-all-scream if work dir is specified
  components/scream/scripts/test_all_scream.py
Labels: AT: AUTOMERGE, bugfix, scripts

#1272 update lassen netcdf modules to gcc8.3.1
  components/scream/cmake/machine-files/lassen.cmake
  components/scream/scripts/machines_specs.py
Labels: Machine File, AT: AUTOMERGE, AT: Integrate Without Testing
