Repository E3SM-Project/scream, pull requests merged in 2021-12, with the labels that each got.

#1328 SCREAM: add minor capability to populate-nc-file script
  components/scream/scripts/populate-nc-file
  components/scream/scripts/populate_nc_file.py
Labels: AT: AUTOMERGE, AT: Integrate Without Testing, scripts

#1330 Add units to new diagnostic cloud fraction outputs
  components/eam/src/physics/cam/shoc_intr.F90
Labels: B4B, AT: AUTOMERGE

#1325 Update SHOC default tunable parameters
  components/eam/bld/namelist_files/namelist_defaults_eam.xml
  components/eam/src/physics/cam/shoc.F90
  components/scream/src/physics/shoc/shoc_assumed_pdf_impl.hpp
  components/scream/src/physics/shoc/shoc_diag_second_moments_impl.hpp
  components/scream/src/physics/shoc/shoc_eddy_diffusivities_impl.hpp
Labels: Non-B4B, shoc, AT: AUTOMERGE

#1332 SHOC surface sensible heat flux fix
  components/eam/src/physics/cam/shoc_intr.F90
  components/scream/src/physics/shoc/atmosphere_macrophysics.cpp
  components/scream/src/physics/shoc/atmosphere_macrophysics.hpp
Labels: Non-B4B, AT: AUTOMERGE, bugfix

#1334 Make vertically intergated cloud fractions use TOT_CLOUD_FRAC instead…
  components/eam/src/physics/cam/cloud_cover_diags.F90
  components/eam/src/physics/cam/cloud_diagnostics.F90
  components/eam/src/physics/cam/shoc_intr.F90
Labels: B4B, AT: AUTOMERGE

#1337 SCREAM: bug fix in column ops packed scan sum
  components/scream/src/share/util/scream_column_ops.hpp
Labels: AT: AUTOMERGE, bugfix

#1336 Add diagnostics specific for DP-SCREAM
  components/eam/src/control/history_scam.F90
  components/eam/src/dynamics/se/se_single_column_mod.F90
  components/homme/src/theta-l/share/element_ops.F90
Labels: B4B, AT: AUTOMERGE

#1340 set SCREAM to run with adjust_ps=.false.
  components/homme/src/share/prim_driver_base.F90
Labels: Non-B4B, AT: AUTOMERGE

#1345 DP-SCREAM mpi communicator for Data ocean initialization fix
  share/util/shr_scam_mod.F90
Labels: B4B, AT: AUTOMERGE, bugfix

#1349 Fix bug in pblintd_height()
  components/eam/src/physics/cam/shoc.F90
  components/scream/src/physics/shoc/shoc_functions_f90.cpp
  components/scream/src/physics/shoc/shoc_functions_f90.hpp
  components/scream/src/physics/shoc/shoc_iso_c.f90
  components/scream/src/physics/shoc/shoc_iso_f.f90
  components/scream/src/physics/shoc/shoc_pblintd_height_impl.hpp
  components/scream/src/physics/shoc/tests/shoc_pblintd_height_tests.cpp
  components/scream/src/physics/shoc/tests/shoc_pblintd_tests.cpp
Labels: B4B, shoc, AT: AUTOMERGE, bugfix

#1352 Change mappy setup to load archived sems tpls
  components/scream/scripts/jenkins/mappy_setup
  components/scream/scripts/machines_specs.py
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#1350 P3 F90 diagnostic bug fix (fixes chronically failing DP-SCREAM Mappy tests)
  cime_config/machines/config_machines.xml
  components/eam/cime_config/config_component.xml
  components/eam/src/physics/cam/micro_p3_interface.F90
Labels: B4B, p3, AT: AUTOMERGE, bugfix, CIME

#1347 Reset default cosp_ncolumns to 10
  components/eam/bld/build-namelist
  components/eam/bld/namelist_files/namelist_defaults_eam.xml
Labels: B4B, AT: AUTOMERGE, scripts

#1353 New lmod module system requires specific version numbers
  cime_config/machines/config_machines.xml
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#1359 Add -DSCREAM to enable SCREAM features from upstream
  components/eam/cime_config/config_component.xml
Labels: B4B, AT: AUTOMERGE

#1355 Fix valid_values string for do_spa_optics
  components/eam/bld/namelist_files/namelist_definition.xml
Labels: B4B, AT: AUTOMERGE, bugfix, SPA
