Repository E3SM-Project/scream, pull requests merged in 2021-11, with the labels that each got.

#1289 Make all tests that run through the AD run on multi-ranks.
  components/scream/cmake/CprncTest.cmake
  components/scream/cmake/machine-files/lassen.cmake
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.cpp
  components/scream/src/share/io/scorpio_output.cpp
  components/scream/src/share/io/scorpio_output.hpp
  components/scream/tests/coupled/shoc_cld_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/shoc_cld_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/shoc_cld_p3_rrtmgp/shoc_cld_p3_rrtmgp.cpp
  components/scream/tests/coupled/shoc_cld_p3_rrtmgp/shoc_cld_p3_rrtmgp_output.yaml
  components/scream/tests/uncoupled/p3/CMakeLists.txt
  components/scream/tests/uncoupled/p3/input.yaml
  components/scream/tests/uncoupled/p3/p3_standalone.cpp
  components/scream/tests/uncoupled/p3/p3_standalone_output.yaml
  components/scream/tests/uncoupled/rrtmgp/CMakeLists.txt
  components/scream/tests/uncoupled/rrtmgp/input.yaml
  components/scream/tests/uncoupled/rrtmgp/input_unit.yaml
  components/scream/tests/uncoupled/rrtmgp/rrtmgp_init_ne2np4.nc
  components/scream/tests/uncoupled/rrtmgp/rrtmgp_standalone.cpp
  components/scream/tests/uncoupled/rrtmgp/rrtmgp_standalone_output.yaml
  components/scream/tests/uncoupled/rrtmgp/rrtmgp_standalone_unit.cpp
  components/scream/tests/uncoupled/shoc/CMakeLists.txt
  components/scream/tests/uncoupled/shoc/input.yaml
  components/scream/tests/uncoupled/shoc/shoc_standalone.cpp
  components/scream/tests/uncoupled/shoc/shoc_standalone_output.yaml
  components/scream/tests/uncoupled/spa/CMakeLists.txt
  components/scream/tests/uncoupled/spa/input.yaml
  components/scream/tests/uncoupled/spa/spa_stand_alone.cpp
  components/scream/tests/uncoupled/spa/spa_standalone_output.yaml
Labels: testing, B4B, radiation, I/O, AT: AUTOMERGE, physics, priority:high

#1292 update lassen machine file to make sure run_and_cmp tests will pass
  components/scream/cmake/machine-files/lassen.cmake
Labels: Machine File, AT: AUTOMERGE, AT: Integrate Without Testing

#1294 Fix IO classes' handling of var offsets.
  components/scream/src/physics/p3/p3_main_impl_part2.hpp
  components/scream/src/share/grid/abstract_grid.cpp
  components/scream/src/share/grid/abstract_grid.hpp
  components/scream/src/share/io/scorpio_input.cpp
  components/scream/src/share/io/scorpio_output.cpp
  components/scream/src/share/tests/grid_tests.cpp
Labels: I/O, AT: AUTOMERGE, bugfix

#1295 SCREAM: fix machine specs check for "local" machine
  components/scream/scripts/machines_specs.py
Labels: AT: AUTOMERGE, bugfix, AT: Integrate Without Testing, scripts, CIME

#1296 Port SCREAM config_compilers stuff to new cmake macro system
  cime_config/machines/cmake_macros/gnu9.cmake
  cime_config/machines/cmake_macros/gnu9_mappy.cmake
  cime_config/machines/cmake_macros/intel_quartz.cmake
  cime_config/machines/cmake_macros/intel_syrah.cmake
Labels: AT: Integrate Without Testing

#1297 Do not set CTEST_PARALLEL_LEVEL for scripts-ctest-driver
  components/scream/scripts/scripts_ctest_driver.py
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#1281 DP-SCREAM large scale forcing bug fix
  components/eam/src/control/forecast.F90
Labels: B4B, AT: AUTOMERGE, bugfix, CIME

#1268 Add ERP test for doubly periodic SCREAM
  cime_config/tests.py
Labels: B4B, AT: AUTOMERGE, CIME

#1299 Pull V1 tests into their own suite
  cime_config/tests.py
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#1300 CIME label testing needs to include V1 tests now
  components/scream/scripts/jenkins/jenkins_common_impl.sh
Labels: AT: AUTOMERGE, CIME, AT: Skip weaver, AT: Skip blake

#1285 Fix F2000SCREAMv1 test
  cime_config/config_archive.xml
  cime_config/tests.py
  components/scream/cime_config/testdefs/testmods_dirs/scream/30min_ts/shell_commands
  components/scream/cime_config/testdefs/testmods_dirs/scream/3min_ts/shell_commands
  components/scream/data/scream_input.yaml
  components/scream/src/control/surface_coupling_export.cpp
  components/scream/src/dynamics/homme/interface/homme_params_mod.F90
  components/scream/src/mct_coupling/scream_cxx_f90_interface.cpp
  components/scream/src/physics/shoc/atmosphere_macrophysics.hpp
Labels: testing, CIME

#1304 Allow changing a subfield's slice idx at runtime
  components/scream/src/control/surface_coupling.cpp
  components/scream/src/share/field/field.hpp
  components/scream/src/share/field/field_alloc_prop.cpp
  components/scream/src/share/field/field_alloc_prop.hpp
  components/scream/src/share/field/field_header.cpp
  components/scream/src/share/field/field_header.hpp
  components/scream/src/share/field/field_manager.hpp
  components/scream/src/share/field/field_request.hpp
  components/scream/src/share/tests/field_tests.cpp
Labels: enhancement, AT: AUTOMERGE, Atmosphere Driver

#1309 Update F2000v1 compset to use 24 procs
  cime_config/tests.py
Labels: AT: AUTOMERGE, CIME, AT: Skip weaver, AT: Skip blake

#1306 Remove updated groups from atm proc interface
  components/scream/src/control/atmosphere_driver.cpp
  components/scream/src/control/atmosphere_driver.hpp
  components/scream/src/control/tests/ad_tests.cpp
  components/scream/src/control/tests/ad_tests.yaml
  components/scream/src/control/tests/dummy_atm_proc.hpp
  components/scream/src/dynamics/homme/atmosphere_dynamics.cpp
  components/scream/src/dynamics/homme/atmosphere_dynamics.hpp
  components/scream/src/physics/shoc/atmosphere_macrophysics.cpp
  components/scream/src/physics/shoc/atmosphere_macrophysics.hpp
  components/scream/src/share/atm_process/atmosphere_process.cpp
  components/scream/src/share/atm_process/atmosphere_process.hpp
  components/scream/src/share/atm_process/atmosphere_process_dag.cpp
  components/scream/src/share/atm_process/atmosphere_process_dag.hpp
  components/scream/src/share/atm_process/atmosphere_process_group.cpp
  components/scream/src/share/atm_process/atmosphere_process_group.hpp
  components/scream/tests/uncoupled/homme/homme_standalone.cpp
Labels: AT: AUTOMERGE, Atmosphere Driver, code cleanup

#1308 Move responsibility of handling output files to OutputManager
  components/scream/src/control/atmosphere_driver.cpp
  components/scream/src/control/atmosphere_driver.hpp
  components/scream/src/dynamics/homme/tests/dyn_grid_io.cpp
  components/scream/src/share/io/scorpio_input.cpp
  components/scream/src/share/io/scorpio_input.hpp
  components/scream/src/share/io/scorpio_output.cpp
  components/scream/src/share/io/scorpio_output.hpp
  components/scream/src/share/io/scream_io_utils.hpp
  components/scream/src/share/io/scream_output_manager.cpp
  components/scream/src/share/io/scream_output_manager.hpp
  components/scream/src/share/io/scream_scorpio_interface.F90
  components/scream/src/share/io/scream_scorpio_interface.hpp
  components/scream/src/share/io/scream_scorpio_interface_iso_c2f.F90
  components/scream/src/share/io/tests/CMakeLists.txt
  components/scream/src/share/io/tests/io.cpp
  components/scream/src/share/io/tests/io_test_average.yaml
  components/scream/src/share/io/tests/io_test_instant.yaml
  components/scream/src/share/io/tests/io_test_max.yaml
  components/scream/src/share/io/tests/io_test_min.yaml
  components/scream/src/share/io/tests/io_test_multisnap.yaml
  components/scream/src/share/io/tests/io_test_restart.yaml
  components/scream/src/share/io/tests/io_test_restart_check.yaml
  components/scream/src/share/io/tests/restart.cpp
  components/scream/src/share/tests/utils_tests.cpp
  components/scream/src/share/util/scream_time_stamp.cpp
  components/scream/src/share/util/scream_time_stamp.hpp
  components/scream/src/share/util/scream_utils.hpp
  components/scream/tests/coupled/homme_physics/homme_shoc_cld_p3_rrtmgp.cpp
  components/scream/tests/coupled/homme_physics/homme_shoc_cld_p3_rrtmgp_output.yaml
  components/scream/tests/coupled/homme_physics/input.yaml
  components/scream/tests/coupled/shoc_cld_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/shoc_cld_p3_rrtmgp/shoc_cld_p3_rrtmgp.cpp
  components/scream/tests/coupled/shoc_cld_p3_rrtmgp/shoc_cld_p3_rrtmgp_output.yaml
  components/scream/tests/uncoupled/cld_fraction/cld_fraction_standalone.cpp
  components/scream/tests/uncoupled/homme/homme_standalone.cpp
  components/scream/tests/uncoupled/homme/homme_standalone_output.yaml
  components/scream/tests/uncoupled/homme/input.yaml
  components/scream/tests/uncoupled/p3/input.yaml
  components/scream/tests/uncoupled/p3/p3_standalone.cpp
  components/scream/tests/uncoupled/p3/p3_standalone_output.yaml
  components/scream/tests/uncoupled/rrtmgp/input.yaml
  components/scream/tests/uncoupled/rrtmgp/rrtmgp_standalone.cpp
  components/scream/tests/uncoupled/rrtmgp/rrtmgp_standalone_output.yaml
  components/scream/tests/uncoupled/shoc/input.yaml
  components/scream/tests/uncoupled/shoc/shoc_standalone.cpp
  components/scream/tests/uncoupled/shoc/shoc_standalone_output.yaml
  components/scream/tests/uncoupled/spa/input.yaml
  components/scream/tests/uncoupled/spa/spa_output.yaml
  components/scream/tests/uncoupled/spa/spa_stand_alone.cpp
  components/scream/tests/uncoupled/spa/spa_standalone_output.yaml
Labels: I/O, AT: AUTOMERGE

#1307 Beydoun/precip ice fraction 2
  components/eam/src/physics/cam/shoc_intr.F90
Labels: p3, AT: AUTOMERGE

#1260 SPA Phase 2 - horizontal interpolation - new version
  components/scream/cmake/machine-files/blake.cmake
  components/scream/cmake/machine-files/lassen.cmake
  components/scream/cmake/machine-files/mappy.cmake
  components/scream/cmake/machine-files/quartz.cmake
  components/scream/cmake/machine-files/syrah.cmake
  components/scream/cmake/machine-files/weaver.cmake
  components/scream/src/physics/spa/CMakeLists.txt
  components/scream/src/physics/spa/atmosphere_prescribed_aerosol.cpp
  components/scream/src/physics/spa/atmosphere_prescribed_aerosol.hpp
  components/scream/src/physics/spa/atmosphere_prescribed_aerosol_hack.cpp
  components/scream/src/physics/spa/spa_functions.hpp
  components/scream/src/physics/spa/spa_functions_impl.hpp
  components/scream/src/physics/spa/tests/CMakeLists.txt
  components/scream/src/physics/spa/tests/spa_data_for_testing.nc
  components/scream/src/physics/spa/tests/spa_one_to_one_remap_test.cpp
  components/scream/src/physics/spa/tests/spa_read_data_from_file_test.cpp
  components/scream/src/physics/spa/tests/spa_read_remap_from_file_test.cpp
  components/scream/src/share/grid/abstract_grid.cpp
  components/scream/src/share/io/scream_scorpio_interface.F90
  components/scream/src/share/io/scream_scorpio_interface.cpp
  components/scream/src/share/io/scream_scorpio_interface.hpp
  components/scream/src/share/io/scream_scorpio_interface_iso_c2f.F90
  components/scream/src/share/io/tests/io.cpp
  components/scream/tests/uncoupled/CMakeLists.txt
  components/scream/tests/uncoupled/spa/CMakeLists.txt
  components/scream/tests/uncoupled/spa/input.yaml
Labels: enhancement, Non-B4B, I/O, AT: AUTOMERGE, priority:high, SPA

#1313 Set topography views inside Homme.
  components/scream/src/dynamics/homme/atmosphere_dynamics.cpp
  components/scream/src/dynamics/homme/atmosphere_dynamics.hpp
  components/scream/src/dynamics/homme/interface/homme_driver_mod.F90
  components/scream/tests/uncoupled/homme/homme_standalone.cpp
Labels: infrastructure, New Variables, homme, AT: AUTOMERGE, Atmosphere Driver, priority:high

#1310 Add std:: to isnan call to build with icpc on Chrysalis.
  components/scream/src/share/field/field_property_checks/field_nan_check.hpp
Labels: code quality, AT: AUTOMERGE, Atmosphere Driver

#1316 changed ice mixing ratio threshold to 1e-5 kg/kg for setting ice clou…
  components/eam/src/physics/cam/shoc_intr.F90
Labels: B4B, AT: AUTOMERGE

#1321 Fix dyn states time-slice handling in PD remapper
  components/scream/src/dynamics/homme/physics_dynamics_remapper.hpp
Labels: infrastructure, homme, AT: AUTOMERGE, bugfix, dynamics

#1319 Add ne256pg2 to r0125 atm2rof maps
  cime_config/config_grids.xml
Labels: AT: AUTOMERGE

#1323 Update the capabilities of SCREAM's scream_input.yaml file
  components/scream/cime_config/buildnml
  components/scream/data/scream_input.yaml
  components/scream/scripts/utils.py
Labels: AT: AUTOMERGE

#1324 This commit is a quick bugfix to an issue that was causing the SCREAMv1
  components/scream/src/mct_coupling/CMakeLists.txt
Labels: B4B, AT: AUTOMERGE, bugfix, CIME, AT: Skip mappy, AT: Skip weaver, AT: Skip blake
