Repository E3SM-Project/scream, pull requests merged in 2022-09, with the labels that each got.

#1913 On pm-cpu and pm-gpu, use CFS as output dir temporarily
  cime_config/machines/config_machines.xml
Labels: AT: AUTOMERGE, AT: Integrate Without Testing, pm-gpu, pm-cpu

#1915 Fix quartz building of kokkos
  cime_config/machines/cmake_macros/intel_quartz.cmake
  components/scream/cmake/machine-files/quartz.cmake
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#1914 Link YAKL against MPI if HAVE_MPI is defined
  components/cmake/build_scream.cmake
  components/scream/src/physics/rrtmgp/CMakeLists.txt
Labels: cmake, AT: AUTOMERGE, bugfix, yakl

#1918 SHOC: Add a missing team_barrier.
  components/scream/src/physics/shoc/shoc_update_prognostics_implicit_impl.hpp
Labels: AT: RETEST, AT: AUTOMERGE, bugfix, GPU

#1911 Allow to reduce size of e3sm log, by optionally suppressing pre/post condition checks warnings
  components/scream/cime_config/namelist_defaults_scream.xml
  components/scream/src/share/atm_process/atmosphere_process.cpp
  components/scream/src/share/atm_process/atmosphere_process.hpp
  components/scream/src/share/tests/atm_process_tests.cpp
Labels: enhancement, B4B, AT: AUTOMERGE

#1921 SHOC: Add some team_barriers that resolve a problem but don't make sense.
  components/scream/src/physics/shoc/shoc_energy_integrals_impl.hpp
Labels: GPU

#1906 EAMxx: fix time handling in SPA
  components/scream/src/physics/spa/atmosphere_prescribed_aerosol.cpp
  components/scream/src/physics/spa/spa_functions_impl.hpp
Labels: AT: AUTOMERGE, bugfix, SPA

#1880 Better handling of floating point precision in scorpio interface layer.
  components/scream/cmake/tpls/Scorpio.cmake
  components/scream/src/dynamics/homme/tests/dyn_grid_io.cpp
  components/scream/src/physics/spa/spa_functions_impl.hpp
  components/scream/src/share/io/CMakeLists.txt
  components/scream/src/share/io/scorpio_input.cpp
  components/scream/src/share/io/scorpio_output.cpp
  components/scream/src/share/io/scorpio_output.hpp
  components/scream/src/share/io/scream_output_manager.cpp
  components/scream/src/share/io/scream_scorpio_interface.F90
  components/scream/src/share/io/scream_scorpio_interface.cpp
  components/scream/src/share/io/scream_scorpio_interface.hpp
  components/scream/src/share/io/scream_scorpio_interface_iso_c2f.F90
  components/scream/src/share/io/tests/io.cpp
  components/scream/src/share/io/tests/io_se_grid.cpp
  components/scream/src/share/io/tests/output_restart.cpp
  components/scream/src/share/util/scream_time_stamp.cpp
  components/scream/src/share/util/scream_time_stamp.hpp
Labels: enhancement, B4B, I/O, AT: AUTOMERGE

#1924 ninja fix to remove errant print statement
  components/scream/src/share/io/scream_scorpio_interface.F90
Labels: AT: AUTOMERGE, bugfix, AT: Integrate Without Testing

#1925 EAMxx: fix shoc standalone output yaml file
  components/scream/tests/uncoupled/shoc/shoc_standalone_output.yaml
Labels: testing, B4B, AT: AUTOMERGE, bugfix, AT: Skip v1 Testing

#1912 Add ne1024pg2_ne1024pg2 grid to have ocnice on the same grid as atm
  cime_config/config_grids.xml
Labels: B4B, AT: AUTOMERGE, AT: Skip Stand-Alone Testing

#1892 Use reduced spectral resolution for RRTMGP
  components/scream/cime_config/namelist_defaults_scream.xml
  components/scream/src/physics/rrtmgp/CMakeLists.txt
  components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp
  components/scream/src/physics/rrtmgp/mo_load_coefficients.cpp
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.cpp
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.hpp
  components/scream/src/physics/rrtmgp/tests/generate_baseline.cpp
  components/scream/src/physics/rrtmgp/tests/rrtmgp_tests.cpp
  components/scream/src/physics/rrtmgp/tests/rrtmgp_unit_tests.cpp
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/input.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_baseline.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_initial.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_restarted.yaml
  components/scream/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/input.yaml
  components/scream/tests/uncoupled/rrtmgp/CMakeLists.txt
  components/scream/tests/uncoupled/rrtmgp/input.yaml
  components/scream/tests/uncoupled/rrtmgp/input_unit.yaml
Labels: Non-B4B, radiation

#1930 EAMxx: fix buggy logic in npX vs np1 tests
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/CMakeLists.txt
  components/scream/tests/coupled/dynamics_physics/model_restart/CMakeLists.txt
  components/scream/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/uncoupled/homme/CMakeLists.txt
  components/scream/tests/uncoupled/p3/CMakeLists.txt
  components/scream/tests/uncoupled/rrtmgp/CMakeLists.txt
  components/scream/tests/uncoupled/shoc/CMakeLists.txt
  components/scream/tests/uncoupled/spa/CMakeLists.txt
Labels: cmake, AT: AUTOMERGE, bugfix, AT: Skip v1 Testing

#1935 fix rh bug identified by AB
  components/scream/src/diagnostics/relative_humidity.cpp
Labels: AT: AUTOMERGE, bugfix, diagnostic

#1931 Re-instate single precision model output
  components/scream/cmake/tpls/Scorpio.cmake
  components/scream/src/dynamics/homme/tests/dyn_grid_io.cpp
  components/scream/src/physics/spa/spa_functions_impl.hpp
  components/scream/src/share/io/CMakeLists.txt
  components/scream/src/share/io/scorpio_input.cpp
  components/scream/src/share/io/scorpio_output.cpp
  components/scream/src/share/io/scorpio_output.hpp
  components/scream/src/share/io/scream_output_manager.cpp
  components/scream/src/share/io/scream_scorpio_interface.F90
  components/scream/src/share/io/scream_scorpio_interface.cpp
  components/scream/src/share/io/scream_scorpio_interface.hpp
  components/scream/src/share/io/scream_scorpio_interface_iso_c2f.F90
  components/scream/src/share/io/tests/io.cpp
  components/scream/src/share/io/tests/io_se_grid.cpp
  components/scream/src/share/io/tests/output_restart.cpp
  components/scream/src/share/util/scream_time_stamp.cpp
  components/scream/src/share/util/scream_time_stamp.hpp
Labels: enhancement, I/O, AT: AUTOMERGE

#1938 SHOC: Use another team_barrier based on view_reduction pattern.
  components/scream/src/physics/shoc/shoc_compute_l_inf_shoc_length_impl.hpp
Labels: AT: AUTOMERGE

#1927 Fix IO classes handling of grids with alias names
  components/scream/src/share/grid/abstract_grid.cpp
  components/scream/src/share/grid/grids_manager.cpp
  components/scream/src/share/io/scorpio_input.cpp
  components/scream/src/share/io/scorpio_input.hpp
  components/scream/src/share/io/scorpio_output.cpp
  components/scream/tests/uncoupled/shoc/shoc_standalone_output.yaml
Labels: I/O, AT: AUTOMERGE, bugfix

#1941 Bugfix to re-initialize views in output after each write step
  components/scream/src/share/io/scorpio_output.cpp
  components/scream/src/share/io/scorpio_output.hpp
  components/scream/src/share/io/scream_output_manager.cpp
Labels: B4B, I/O, AT: AUTOMERGE, bugfix, priority:high

#1947 EAMxx: add possibility to control atm procs log level in standalone test
  components/scream/src/share/atm_process/atmosphere_process.cpp
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/input.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_baseline.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_initial.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_restarted.yaml
Labels: B4B, AT: AUTOMERGE

#1948 Add initial condition and defaults for ne256
  components/scream/cime_config/namelist_defaults_scream.xml
Labels: B4B, AT: AUTOMERGE

#1949 Minor bugfixes for solar insolation
  components/eam/bld/configure
  components/eam/src/physics/rrtmgp/cpp/CMakeLists.txt
  components/eam/src/physics/rrtmgp/cpp/mo_load_coefficients.cpp
  components/eam/src/physics/rrtmgp/f90/mo_load_coefficients.F90
  components/scream/cime_config/namelist_defaults_scream.xml
  components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp
Labels: Non-B4B, radiation

#1952 EAMxx: fix detection of CIME build in scorpio F90 interface
  components/scream/src/scream_config.h.in
  components/scream/src/share/CMakeLists.txt
  components/scream/src/share/io/scream_scorpio_interface_iso_c2f.F90
  components/scream/src/share/util/scream_timing.cpp
Labels: I/O, AT: AUTOMERGE, bugfix

#1953 EAMxx: fix bug in message printed by property checks
  components/scream/src/share/property_checks/field_nan_check.cpp
  components/scream/src/share/property_checks/field_within_interval_check.cpp
  components/scream/src/share/tests/property_checks.cpp
  components/scream/src/share/tests/utils_tests.cpp
Labels: AT: AUTOMERGE, bugfix

#1954 Update files used w/ ne1024 runs in a CIME case.
  components/scream/cime_config/namelist_defaults_scream.xml
Labels: B4B, AT: AUTOMERGE, AT: Integrate Without Testing

#1928 Add subcolumn sampling for cloud overlap in radiation
  components/eam/src/physics/rrtmgp/radiation.F90
  components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp
  components/scream/src/physics/rrtmgp/atmosphere_radiation.hpp
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.cpp
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.hpp
  components/scream/src/physics/rrtmgp/tests/generate_baseline.cpp
  components/scream/src/physics/rrtmgp/tests/rrtmgp_tests.cpp
  components/scream/src/physics/rrtmgp/tests/rrtmgp_unit_tests.cpp
  components/scream/src/share/field/field_tag.hpp
  components/scream/src/share/io/scream_scorpio_interface.hpp
  components/scream/tests/uncoupled/rrtmgp/input_unit.yaml
Labels: enhancement, Non-B4B, radiation

#1746 Reverting the revert which reverted SHOC dry<->wet conversion and ERP bug fix
  components/eam/src/physics/cam/shoc_intr.F90
  components/scream/src/physics/shoc/atmosphere_macrophysics.cpp
  components/scream/src/physics/shoc/atmosphere_macrophysics.hpp
Labels: Non-B4B, shoc, bugfix, physics, CIME, SCREAMv0

#1956 HighResMIP 0.25x0.25 daily sstice for 2010 SCREAMv1 at ne120 or higher
  components/data_comps/docn/cime_config/config_component.xml
Labels: B4B, AT: AUTOMERGE, AT: Integrate Without Testing, SCREAMv1, input file

#1945 Introduce a general horizontal remapper v2
  components/scream/src/physics/spa/atmosphere_prescribed_aerosol.cpp
  components/scream/src/physics/spa/atmosphere_prescribed_aerosol.hpp
  components/scream/src/physics/spa/spa_functions.hpp
  components/scream/src/physics/spa/spa_functions_impl.hpp
  components/scream/src/physics/spa/tests/CMakeLists.txt
  components/scream/src/physics/spa/tests/spa_one_to_one_remap_test.cpp
  components/scream/src/physics/spa/tests/spa_read_data_from_file_test.cpp
  components/scream/src/physics/spa/tests/spa_read_remap_from_file_test.cpp
  components/scream/src/share/CMakeLists.txt
  components/scream/src/share/grid/remap/horizontal_remap_utility.cpp
  components/scream/src/share/grid/remap/horizontal_remap_utility.hpp
  components/scream/src/share/tests/CMakeLists.txt
  components/scream/src/share/tests/horizontal_remap_test.cpp
  components/scream/tests/uncoupled/spa/CMakeLists.txt
  components/scream/tests/uncoupled/spa/spa_standalone_output.yaml
Labels: enhancement, Non-B4B, SPA

#1957 This commit fixes the zonal and meridonal vapor flux diagnostics.
  components/scream/src/diagnostics/meridional_vapor_flux.cpp
  components/scream/src/diagnostics/tests/meridional_vapor_flux_tests.cpp
  components/scream/src/diagnostics/tests/zonal_vapor_flux_tests.cpp
  components/scream/src/diagnostics/zonal_vapor_flux.cpp
Labels: B4B, AT: AUTOMERGE, bugfix, diagnostic

#1962 Fix pioc/piof interface libraries in CIME builds
  components/scream/cmake/tpls/GetNetcdfLibs.cmake
  components/scream/cmake/tpls/Scorpio.cmake
Labels: cmake, AT: AUTOMERGE, bugfix, AT: Skip Stand-Alone Testing

#1967 EAMxx/SHOC: Fix new nondeterminism.
  cime_config/tests.py
  components/scream/src/physics/shoc/atmosphere_macrophysics.hpp
Labels: testing, AT: AUTOMERGE, bugfix

#1965 Fix passage of views to parallel Kokkos loops in horizontal_remap_utility.
  components/scream/src/share/grid/remap/horizontal_remap_utility.cpp
Labels: AT: AUTOMERGE, bugfix, priority:high, SPA

#1961 Add various fields to import fields
  components/scream/src/control/atmosphere_surface_coupling_importer.cpp
  components/scream/src/mct_coupling/scream_cpl_indices.F90
  components/scream/tests/uncoupled/surface_coupling/surface_coupling.cpp
Labels: AT: AUTOMERGE, Surface Coupling

#1964 EAMxx: fix creation of diags in IO
  components/scream/src/diagnostics/atm_density.hpp
  components/scream/src/diagnostics/dry_static_energy.hpp
  components/scream/src/diagnostics/exner.hpp
  components/scream/src/diagnostics/field_at_level.hpp
  components/scream/src/diagnostics/ice_cloud_mask.hpp
  components/scream/src/diagnostics/ice_water_path.hpp
  components/scream/src/diagnostics/liquid_water_path.hpp
  components/scream/src/diagnostics/longwave_cloud_forcing.hpp
  components/scream/src/diagnostics/meridional_vapor_flux.hpp
  components/scream/src/diagnostics/potential_temperature.hpp
  components/scream/src/diagnostics/rain_water_path.hpp
  components/scream/src/diagnostics/relative_humidity.hpp
  components/scream/src/diagnostics/rime_water_path.hpp
  components/scream/src/diagnostics/sea_level_pressure.hpp
  components/scream/src/diagnostics/shortwave_cloud_forcing.hpp
  components/scream/src/diagnostics/vapor_water_path.hpp
  components/scream/src/diagnostics/vertical_layer_interface.hpp
  components/scream/src/diagnostics/vertical_layer_midpoint.hpp
  components/scream/src/diagnostics/vertical_layer_thickness.hpp
  components/scream/src/diagnostics/virtual_temperature.hpp
  components/scream/src/diagnostics/zonal_vapor_flux.hpp
  components/scream/src/share/io/scorpio_output.cpp
  components/scream/src/share/io/scorpio_output.hpp
  components/scream/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/shoc_cld_spa_p3_rrtmgp_output.yaml
Labels: I/O, AT: AUTOMERGE, bugfix

#1970 Add vertically-projected cloud area output from radiation
  components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.cpp
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.hpp
  components/scream/src/physics/rrtmgp/tests/rrtmgp_unit_tests.cpp
Labels: B4B, radiation, AT: AUTOMERGE, SCREAMv1

#1971 Add temperature limiters for gaseous absorption calculations
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.cpp
Labels: Non-B4B, radiation, SCREAMv1
