Repository E3SM-Project/scream, pull requests merged in 2022-10, with the labels that each got.

#1974 Add vertically integrated low, mid, and high-level cloud area
  components/scream/data/scream_default_output.yaml
  components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.cpp
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.hpp
  components/scream/src/physics/rrtmgp/tests/rrtmgp_unit_tests.cpp
Labels: radiation, AT: AUTOMERGE, SCREAMv1

#1975 Remove warnings about no day columns
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.cpp
Labels: B4B, radiation, AT: AUTOMERGE, SCREAMv1

#1977 ninja fix to remove unneeded cout statement.
  components/scream/src/share/io/scorpio_output.cpp
Labels: B4B, AT: AUTOMERGE, bugfix

#1972 Remove extra large optics by g-point outputs
  components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp
Labels: B4B, radiation, AT: AUTOMERGE, SCREAMv1

#1969 EAMxx: Skip calling free_decomp when a file is closed.
  components/scream/src/share/grid/remap/horizontal_remap_utility.cpp
  components/scream/src/share/io/scorpio_output.cpp
  components/scream/src/share/io/scream_scorpio_interface.F90
Labels: enhancement, AT: AUTOMERGE

#1980 EAMxx/IO: Reinstate free_decomp for now.
  components/scream/src/share/io/scream_scorpio_interface.F90
Labels: bugfix

#1978 For perlmutter (pm-cpu and pm-gpu) use scratch instead of CFS for cases.
  cime_config/machines/config_machines.xml
Labels: AT: AUTOMERGE, pm-gpu, pm-cpu

#1981 Switch to new ne30L128 IC with hydrometeors clipped
  components/scream/cime_config/namelist_defaults_scream.xml
Labels: AT: AUTOMERGE

#1983 EAMxx: Try again to reuse PIO decomps across files.
  components/scream/src/share/io/scorpio_input.cpp
  components/scream/src/share/io/scorpio_output.cpp
  components/scream/src/share/io/scream_scorpio_interface.F90
Labels: AT: AUTOMERGE

#1985 EAMxx: Use simulation data type rather than I/O data type in decomp tag.
  components/scream/src/share/io/scorpio_output.cpp
Labels: B4B, AT: AUTOMERGE

#1986 EAMxx: Make iodesc_list_t%tag have length max_chars (256).
  components/scream/src/share/io/scream_scorpio_interface.F90
Labels: AT: AUTOMERGE

#1988 Add intbilin maps for SPA
  components/scream/cime_config/namelist_defaults_scream.xml
Labels: B4B, AT: AUTOMERGE

#1990 Fix race condition for compiled f90 modules in shoc
  components/scream/CMakeLists.txt
  components/scream/cmake/ScreamUtils.cmake
  components/scream/cmake/tpls/Mct.cmake
  components/scream/src/mct_coupling/CMakeLists.txt
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/rrtmgp/CMakeLists.txt
  components/scream/src/physics/share/CMakeLists.txt
  components/scream/src/physics/shoc/CMakeLists.txt
  components/scream/src/physics/zm/CMakeLists.txt
  components/scream/src/share/CMakeLists.txt
  components/scream/src/share/io/CMakeLists.txt
Labels: cmake, AT: AUTOMERGE, bugfix

#1979 Add a coarsening remapper
  components/scream/CMakeLists.txt
  components/scream/src/diagnostics/ice_cloud_mask.cpp
  components/scream/src/diagnostics/tests/ice_cloud_mask_tests.cpp
  components/scream/src/dynamics/homme/CMakeLists.txt
  components/scream/src/dynamics/homme/physics_dynamics_remapper.cpp
  components/scream/src/dynamics/homme/physics_dynamics_remapper.hpp
  components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp
  components/scream/src/physics/shoc/atmosphere_macrophysics.cpp
  components/scream/src/physics/spa/spa_functions_impl.hpp
  components/scream/src/scream_config.h.in
  components/scream/src/share/CMakeLists.txt
  components/scream/src/share/field/field.hpp
  components/scream/src/share/field/field_alloc_prop.cpp
  components/scream/src/share/field/field_layout.cpp
  components/scream/src/share/field/field_layout.hpp
  components/scream/src/share/grid/abstract_grid.cpp
  components/scream/src/share/grid/abstract_grid.hpp
  components/scream/src/share/grid/remap/abstract_remapper.cpp
  components/scream/src/share/grid/remap/abstract_remapper.hpp
  components/scream/src/share/grid/remap/coarsening_remapper.cpp
  components/scream/src/share/grid/remap/coarsening_remapper.hpp
  components/scream/src/share/grid/remap/do_nothing_remapper.hpp
  components/scream/src/share/grid/remap/horizontal_remap_utility.cpp
  components/scream/src/share/grid/remap/identity_remapper.hpp
  components/scream/src/share/grid/remap/inverse_remapper.hpp
  components/scream/src/share/tests/CMakeLists.txt
  components/scream/src/share/tests/coarsening_remapper_tests.cpp
  components/scream/src/share/tests/grid_tests.cpp
  components/scream/src/share/tests/horizontal_remap_test.cpp
Labels: enhancement, AT: AUTOMERGE

#1993 Added SCREAMv1-DYAMOND1 compset and related settings
  components/data_comps/docn/cime_config/config_component.xml
  components/elm/bld/namelist_files/namelist_defaults.xml
  components/elm/cime_config/buildnml
  components/scream/cime_config/config_compsets.xml
  components/scream/cime_config/namelist_defaults_scream.xml
Labels: B4B, AT: AUTOMERGE, SCREAMv1, input file

#1937 Add general vertical interpolation utility
  components/scream/src/physics/p3/atmosphere_microphysics.cpp
  components/scream/src/physics/p3/atmosphere_microphysics.hpp
  components/scream/src/share/tests/CMakeLists.txt
  components/scream/src/share/tests/vertical_interp_tests.cpp
  components/scream/src/share/util/scream_vertical_interpolation.hpp
  components/scream/src/share/util/scream_vertical_interpolation_impl.hpp
Labels: enhancement, B4B, AT: AUTOMERGE, priority:high, AT: PRE-TEST INSPECTED

#1999 Create local temp variables for device code
  components/scream/src/share/property_checks/mass_and_energy_column_conservation_check.cpp
  components/scream/src/share/property_checks/mass_and_energy_column_conservation_check.hpp
Labels: AT: AUTOMERGE, bugfix

#2000 Remove local view in conservation check
  components/scream/src/share/property_checks/mass_and_energy_column_conservation_check.cpp
Labels: code quality, AT: AUTOMERGE, code cleanup

#2006 Refactor how input files are handling in namelist_scream.xml
  components/scream/cime_config/buildnml
  components/scream/cime_config/eamxx_buildnml_impl.py
  components/scream/cime_config/namelist_defaults_scream.xml
Labels: AT: AUTOMERGE, CIME, AT: Skip Stand-Alone Testing

#2010 EAMxx: fix driver options sublist name in f90-cxx interface
  components/scream/src/mct_coupling/scream_cxx_f90_interface.cpp
Labels: AT: AUTOMERGE, bugfix, AT: Skip Stand-Alone Testing
