Repository E3SM-Project/scream, pull requests merged in 2022-12, with the labels that each got.

#2079 Crusher: Stick to one node for tests for now.
  cime_config/allactive/config_pesall.xml
Labels: AT: Integrate Without Testing

#2077 Remove hard-coded disabling of prescribed aero perturbation
  components/eam/src/chemistry/utils/prescribed_aero.F90
Labels: B4B, AT: AUTOMERGE, CIME

#2078 EAMxx: remove runtime parameter from phisics constants
  components/eamxx/src/physics/p3/atmosphere_microphysics.cpp
  components/eamxx/src/physics/p3/p3_f90.cpp
  components/eamxx/src/physics/p3/p3_f90.hpp
  components/eamxx/src/physics/p3/p3_iso_c.f90
  components/eamxx/src/physics/share/physics_constants.hpp
Labels: B4B, p3, AT: AUTOMERGE, code cleanup

#2085 Crusher: Temporarily run nightlies with netcdf.
  cime_config/machines/config_pio.xml
Labels: AT: Integrate Without Testing

#2081 Set phis from separate topography file
  components/eamxx/CMakeLists.txt
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/cmake/ScreamUtils.cmake
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/control/atmosphere_driver.hpp
  components/eamxx/src/dynamics/homme/atmosphere_dynamics.cpp
  components/eamxx/src/physics/p3/CMakeLists.txt
  components/eamxx/src/physics/rrtmgp/CMakeLists.txt
  components/eamxx/src/physics/spa/tests/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/model_restart/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/model_restart/input_baseline.yaml
  components/eamxx/tests/coupled/dynamics_physics/model_restart/input_initial.yaml
  components/eamxx/tests/coupled/physics_only/atm_proc_subcycling/CMakeLists.txt
  components/eamxx/tests/coupled/physics_only/atm_proc_subcycling/input.yaml
  components/eamxx/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/CMakeLists.txt
  components/eamxx/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/input.yaml
  components/eamxx/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/eamxx/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/input.yaml
  components/eamxx/tests/uncoupled/homme/CMakeLists.txt
  components/eamxx/tests/uncoupled/homme/input.yaml
  components/eamxx/tests/uncoupled/p3/CMakeLists.txt
  components/eamxx/tests/uncoupled/rrtmgp/CMakeLists.txt
  components/eamxx/tests/uncoupled/shoc/CMakeLists.txt
  components/eamxx/tests/uncoupled/shoc/input.yaml
  components/eamxx/tests/uncoupled/spa/CMakeLists.txt
  components/eamxx/tests/uncoupled/surface_coupling/CMakeLists.txt
  components/eamxx/tests/uncoupled/surface_coupling/input.yaml
Labels: AT: AUTOMERGE

#2086 Crusher: Simplify modules.
  cime_config/machines/config_machines.xml
Labels: AT: Integrate Without Testing

#2089 Revert "Set phis from separate topography file"
  components/eamxx/CMakeLists.txt
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/cmake/ScreamUtils.cmake
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/control/atmosphere_driver.hpp
  components/eamxx/src/dynamics/homme/atmosphere_dynamics.cpp
  components/eamxx/src/physics/p3/CMakeLists.txt
  components/eamxx/src/physics/rrtmgp/CMakeLists.txt
  components/eamxx/src/physics/spa/tests/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/model_restart/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/model_restart/input_baseline.yaml
  components/eamxx/tests/coupled/dynamics_physics/model_restart/input_initial.yaml
  components/eamxx/tests/coupled/physics_only/atm_proc_subcycling/CMakeLists.txt
  components/eamxx/tests/coupled/physics_only/atm_proc_subcycling/input.yaml
  components/eamxx/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/CMakeLists.txt
  components/eamxx/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/input.yaml
  components/eamxx/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/eamxx/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/input.yaml
  components/eamxx/tests/uncoupled/homme/CMakeLists.txt
  components/eamxx/tests/uncoupled/homme/input.yaml
  components/eamxx/tests/uncoupled/p3/CMakeLists.txt
  components/eamxx/tests/uncoupled/rrtmgp/CMakeLists.txt
  components/eamxx/tests/uncoupled/shoc/CMakeLists.txt
  components/eamxx/tests/uncoupled/shoc/input.yaml
  components/eamxx/tests/uncoupled/spa/CMakeLists.txt
  components/eamxx/tests/uncoupled/surface_coupling/CMakeLists.txt
  components/eamxx/tests/uncoupled/surface_coupling/input.yaml
Labels: AT: AUTOMERGE

#2092 Crusher: Specialize v1_long test group to Crusher.
  cime_config/tests.py
Labels: AT: Integrate Without Testing

#2087 Fix treatment of diagnostics in IO
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/io/scorpio_output.hpp
Labels: I/O, AT: AUTOMERGE, bugfix, diagnostic

#2094 Add a way to track alternate field names in output for certain diagnostics
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/io/scorpio_output.hpp
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/homme_shoc_cld_spa_p3_rrtmgp_diagnostics.yaml
Labels: B4B, I/O, AT: AUTOMERGE

#2083 Revised SHOC TL Rails
  components/eam/src/physics/cam/shoc.F90
  components/eamxx/src/physics/shoc/impl/shoc_assumed_pdf_impl.hpp
Labels: shoc, AT: AUTOMERGE

#2100 Use "static" to avoid implicit capture of 'this' warning
  components/eamxx/src/share/property_checks/mass_and_energy_column_conservation_check.cpp
  components/eamxx/src/share/property_checks/mass_and_energy_column_conservation_check.hpp
Labels: AT: AUTOMERGE, bugfix, GPU

#2097 SHOC assumed PDF NaN Output dump
  components/eamxx/src/physics/shoc/impl/shoc_assumed_pdf_impl.hpp
Labels: shoc, AT: AUTOMERGE, AT: Skip blake

#2102 Crusher: Update CDash configuration.
  cime_config/allactive/config_pesall.xml
  cime_config/machines/cmake_macros/crayclang_crusher-gpu.cmake
  cime_config/machines/config_machines.xml
  cime_config/machines/config_pio.xml
Labels: AT: Integrate Without Testing, crusher-gpu

#2103 Crusher: Back out Scorpio workaround now that 1.4.1 is here.
  cime_config/machines/cmake_macros/crayclang.cmake
  cime_config/machines/cmake_macros/crayclang_crusher-gpu.cmake
Labels: I/O, AT: Integrate Without Testing, crusher-gpu

#2105 EAMxx: fix valgrind error in FieldWithinIntervalCheck
  components/eamxx/src/share/property_checks/field_within_interval_check.cpp
Labels: AT: AUTOMERGE, bugfix, valgrind / cuda-memcheck

#2106 Jgfouca/update weaver toolchain
  components/eamxx/cmake/machine-files/weaver.cmake
  components/eamxx/scripts/machines_specs.py
Labels: AT: AUTOMERGE, AT: Skip mappy, AT: Skip blake

#2107 Do less rad work
  components/eamxx/src/physics/rrtmgp/atmosphere_radiation.cpp
  components/eamxx/src/physics/rrtmgp/atmosphere_radiation.hpp
Labels: B4B, radiation, AT: AUTOMERGE, SCREAMv1

#2104 Update vertical remapping to support 3+ dimensional variables
  components/eamxx/src/diagnostics/CMakeLists.txt
  components/eamxx/src/diagnostics/field_at_pressure_level.cpp
  components/eamxx/src/diagnostics/field_at_pressure_level.hpp
  components/eamxx/src/diagnostics/register_diagnostics.hpp
  components/eamxx/src/diagnostics/tests/CMakeLists.txt
  components/eamxx/src/diagnostics/tests/vertically_remapped_field_tests.cpp
  components/eamxx/src/diagnostics/vertically_remapped_field.cpp
  components/eamxx/src/diagnostics/vertically_remapped_field.hpp
  components/eamxx/src/share/tests/vertical_interp_tests.cpp
  components/eamxx/src/share/util/scream_vertical_interpolation.hpp
  components/eamxx/src/share/util/scream_vertical_interpolation_impl.hpp
Labels: enhancement, B4B, AT: AUTOMERGE

#2043 Fix crusher cpu build
  components/eamxx/CMakeLists.txt
Labels: AT: AUTOMERGE
