Repository E3SM-Project/scream, pull requests merged in 2022-04, with the labels that each got.

#1517 SCREAM: fix prim_init1 sequence for Homme
  components/scream/src/dynamics/homme/atmosphere_dynamics.cpp
  components/scream/src/dynamics/homme/atmosphere_dynamics.hpp
  components/scream/src/dynamics/homme/dynamics_driven_grids_manager.cpp
  components/scream/src/dynamics/homme/interface/dyn_grid_mod.F90
  components/scream/src/dynamics/homme/interface/homme_driver_mod.F90
  components/scream/src/dynamics/homme/interface/scream_homme_interface.hpp
  components/scream/src/dynamics/homme/tests/test_helper_mod.F90
Labels: homme, AT: AUTOMERGE, bugfix, dynamics

#1525 Fix subcycling logic for AtmosphereProcess
  components/scream/src/control/atmosphere_driver.cpp
  components/scream/src/physics/spa/atmosphere_prescribed_aerosol.cpp
  components/scream/src/share/atm_process/atmosphere_process.cpp
  components/scream/src/share/atm_process/atmosphere_process.hpp
  components/scream/src/share/atm_process/atmosphere_process_group.cpp
  components/scream/src/share/atm_process/atmosphere_process_group.hpp
  components/scream/tests/coupled/physics_only/CMakeLists.txt
  components/scream/tests/coupled/physics_only/atm_proc_subcycling/CMakeLists.txt
  components/scream/tests/coupled/physics_only/atm_proc_subcycling/input.yaml
  components/scream/tests/coupled/physics_only/atm_proc_subcycling/output.yaml
  components/scream/tests/coupled/physics_only/atm_proc_subcycling/shoc_p3.cpp
Labels: enhancement, AT: AUTOMERGE

#1527 Fix units on surf_latent_flux
  components/scream/src/control/tests/sc_tests.cpp
  components/scream/src/physics/shoc/atmosphere_macrophysics.cpp
Labels: B4B, AT: AUTOMERGE, bugfix, SCREAMv1

#1526 Set non-exported values to 0.0 in SurfaceCoupling::do_export()
  components/scream/src/control/surface_coupling_export.cpp
  components/scream/src/control/tests/sc_tests.cpp
Labels: AT: AUTOMERGE, CIME

#1531 Minor fixes in property check classes
  components/scream/src/share/property_checks/field_lower_bound_check.hpp
  components/scream/src/share/property_checks/field_positivity_check.hpp
  components/scream/src/share/property_checks/field_upper_bound_check.hpp
  components/scream/src/share/property_checks/field_within_interval_check.hpp
  components/scream/src/share/property_checks/property_check.cpp
  components/scream/src/share/tests/property_checks.cpp
Labels: infrastructure, AT: AUTOMERGE, bugfix

#1529 Improve scorpio output class
  components/scream/src/share/io/scorpio_output.cpp
  components/scream/src/share/io/scorpio_output.hpp
  components/scream/src/share/util/scream_view_utils.hpp
Labels: enhancement, I/O, AT: AUTOMERGE

#1538 For utility function, change len=256 to len=* for incoming fortran string
  components/scream/src/mct_coupling/ekat_string_utils.F90
Labels: bugfix, SCREAMv1, AT: Skip Stand-Alone Testing

#1536 Add radiation super-stepping
  components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp
  components/scream/src/physics/rrtmgp/atmosphere_radiation.hpp
  components/scream/src/physics/rrtmgp/rrtmgp_utils.hpp
  components/scream/src/physics/rrtmgp/tests/rrtmgp_unit_tests.cpp
  components/scream/tests/uncoupled/rrtmgp/input.yaml
  components/scream/tests/uncoupled/rrtmgp/rrtmgp_standalone.cpp
Labels: enhancement, B4B, radiation, SCREAMv1

#1545 For Cori, add flag to allow building with gnuv10 and above.
  components/scream/cmake/machine-files/cori-knl.cmake
Labels: AT: Integrate Without Testing, SCREAMv1, cori

#1496 Add ability to write diagnostic to file.
  components/scream/data/scream_output.yaml
  components/scream/src/diagnostics/potential_temperature.cpp
  components/scream/src/diagnostics/register_diagnostics.hpp
  components/scream/src/diagnostics/tests/potential_temperature_test.cpp
  components/scream/src/share/atm_process/atmosphere_diagnostic.cpp
  components/scream/src/share/atm_process/atmosphere_diagnostic.hpp
  components/scream/src/share/io/CMakeLists.txt
  components/scream/src/share/io/scorpio_output.cpp
  components/scream/src/share/io/scorpio_output.hpp
  components/scream/src/share/io/scream_output_manager.cpp
  components/scream/src/share/io/tests/io.cpp
  components/scream/src/share/io/tests/io_test_instant.yaml
Labels: enhancement, B4B, I/O, AT: AUTOMERGE, AT: Skip blake, SCREAMv1, diagnostic

#1462 Prototype of new namelists.xml
  components/scream/cime_config/buildnml
  components/scream/cime_config/namelist_defaults_scream.xml
  components/scream/data/scream_input.yaml
  components/scream/scripts/atm-config-chg
Labels: AT: AUTOMERGE, SCREAMv1

#1546 Improve documetation of nml XML
  components/scream/cime_config/buildnml
  components/scream/cime_config/namelist_defaults_scream.xml
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#1542 SCREAM: download all p3 tables
  components/scream/CMakeLists.txt
  components/scream/cmake/ScreamUtils.cmake
  components/scream/cmake/ctest_script.cmake
  components/scream/scripts/test_all_scream.py
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/p3_f90.cpp
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_iso_c.f90
  components/scream/src/physics/rrtmgp/CMakeLists.txt
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.cpp
  components/scream/src/physics/rrtmgp/tests/CMakeLists.txt
  components/scream/src/physics/spa/tests/CMakeLists.txt
  components/scream/src/physics/spa/tests/spa_main.yaml
  components/scream/src/physics/spa/tests/spa_one_to_one_remap_test.cpp
  components/scream/src/physics/spa/tests/spa_read_data_from_file_test.cpp
  components/scream/src/physics/spa/tests/spa_read_remap_from_file_test.cpp
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/CMakeLists.txt
  components/scream/tests/coupled/dynamics_physics/model_restart/input_baseline.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_initial.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_restarted.yaml
  components/scream/tests/coupled/physics_only/atm_proc_subcycling/CMakeLists.txt
  components/scream/tests/coupled/physics_only/atm_proc_subcycling/input.yaml
  components/scream/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/input.yaml
  components/scream/tests/uncoupled/homme/CMakeLists.txt
  components/scream/tests/uncoupled/homme/input.yaml
  components/scream/tests/uncoupled/p3/CMakeLists.txt
  components/scream/tests/uncoupled/p3/input.yaml
  components/scream/tests/uncoupled/rrtmgp/CMakeLists.txt
  components/scream/tests/uncoupled/rrtmgp/input.yaml
  components/scream/tests/uncoupled/shoc/CMakeLists.txt
  components/scream/tests/uncoupled/shoc/input.yaml
  components/scream/tests/uncoupled/spa/CMakeLists.txt
  components/scream/tests/uncoupled/spa/input.yaml
Labels: AT: AUTOMERGE, bugfix, SCREAMv1

#1534 Miscellanea scorpio fixes
  components/scream/src/control/atmosphere_driver.cpp
  components/scream/src/control/atmosphere_driver.hpp
  components/scream/src/mct_coupling/atm_comp_mct.F90
  components/scream/src/mct_coupling/scream_cxx_f90_interface.cpp
  components/scream/src/mct_coupling/scream_f2c_mod.F90
  components/scream/src/share/io/scream_output_manager.cpp
  components/scream/src/share/io/scream_scorpio_interface.F90
  components/scream/src/share/io/scream_scorpio_interface.cpp
  components/scream/src/share/io/scream_scorpio_interface.hpp
  components/scream/src/share/io/scream_scorpio_interface_iso_c2f.F90
Labels: I/O, AT: AUTOMERGE, performance, SCREAMv1

#1550 SCREAM: exclude p3_tables_setup from the ALL target
  components/scream/src/physics/p3/CMakeLists.txt
Labels: cmake, AT: AUTOMERGE, bugfix

#1549 Restart fixes
  components/scream/cime_config/namelist_defaults_scream.xml
  components/scream/src/control/atmosphere_driver.cpp
  components/scream/src/control/atmosphere_driver.hpp
  components/scream/src/dynamics/homme/tests/dyn_grid_io.cpp
  components/scream/src/mct_coupling/atm_comp_mct.F90
  components/scream/src/mct_coupling/scream_cxx_f90_interface.cpp
  components/scream/src/mct_coupling/scream_f2c_mod.F90
  components/scream/src/share/io/scream_output_manager.cpp
  components/scream/src/share/io/scream_output_manager.hpp
  components/scream/src/share/io/tests/io.cpp
  components/scream/src/share/io/tests/output_restart.cpp
  components/scream/tests/coupled/dynamics_physics/model_restart/input_baseline.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_initial.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_restarted.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/model_restart.cpp
Labels: enhancement, infrastructure, I/O, AT: AUTOMERGE, SCREAMv1

#1555 Have dynamic expose omega as a computed field
  components/scream/src/dynamics/homme/atmosphere_dynamics.cpp
  components/scream/src/dynamics/homme/tests/CMakeLists.txt
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/dynamics_physics/model_restart/CMakeLists.txt
  components/scream/tests/uncoupled/homme/CMakeLists.txt
Labels: Non-B4B, AT: AUTOMERGE, dynamics, SCREAMv1

#1532 Add bounds checks for atmospheric processes
  components/scream/src/dynamics/homme/atmosphere_dynamics.cpp
  components/scream/src/physics/cld_fraction/atmosphere_cld_fraction.cpp
  components/scream/src/physics/p3/atmosphere_microphysics.cpp
  components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp
  components/scream/src/physics/shoc/atmosphere_macrophysics.cpp
  components/scream/src/physics/spa/atmosphere_prescribed_aerosol.cpp
  components/scream/src/share/atm_process/atmosphere_process.cpp
Labels: B4B, AT: AUTOMERGE

#1556 Better memory management for SPA data read
  components/scream/src/physics/spa/spa_functions.hpp
  components/scream/src/physics/spa/spa_functions_impl.hpp
  components/scream/src/physics/spa/tests/spa_one_to_one_remap_test.cpp
  components/scream/src/physics/spa/tests/spa_read_remap_from_file_test.cpp
  components/scream/src/share/io/scorpio_input.cpp
Labels: bug, B4B, I/O, AT: AUTOMERGE, SPA

#1562 Add error message output from property checks
  components/scream/src/share/atm_process/atmosphere_process.cpp
  components/scream/src/share/property_checks/check_and_repair_wrapper.hpp
  components/scream/src/share/property_checks/field_nan_check.cpp
  components/scream/src/share/property_checks/field_nan_check.hpp
  components/scream/src/share/property_checks/field_within_interval_check.cpp
  components/scream/src/share/property_checks/field_within_interval_check.hpp
  components/scream/src/share/property_checks/property_check.cpp
  components/scream/src/share/property_checks/property_check.hpp
  components/scream/src/share/tests/property_checks.cpp
Labels: enhancement, B4B, AT: AUTOMERGE

#1566 This commit adds a temporary fix to the SHOC field checks.
  components/scream/src/physics/shoc/atmosphere_macrophysics.cpp
Labels: shoc, AT: AUTOMERGE, SCREAMv1

#1570 Add memory usage information to atm log
  components/scream/CMakeLists.txt
  components/scream/src/control/atmosphere_driver.cpp
  components/scream/src/scream_config.h.in
  components/scream/src/share/CMakeLists.txt
  components/scream/src/share/util/scream_utils.cpp
  components/scream/src/share/util/scream_utils.hpp
Labels: enhancement, AT: AUTOMERGE, memory

#1582 Fix handling of tpls targets in CIME builds
  components/scream/cmake/tpls/CsmShare.cmake
  components/scream/cmake/tpls/GPTL.cmake
  components/scream/cmake/tpls/Mct.cmake
  components/scream/cmake/tpls/Scorpio.cmake
  components/scream/src/control/atmosphere_driver.cpp
  components/scream/src/mct_coupling/atm_comp_mct.F90
Labels: cmake, AT: AUTOMERGE, bugfix, SCREAMv1

#1521 Second iteration of namelist defaults & Co.
  components/scream/cime_config/buildnml
  components/scream/cime_config/eamxx_buildnml_impl.py
  components/scream/cime_config/namelist_defaults_scream.xml
  components/scream/scripts/atm-config-chg
  components/scream/src/control/atmosphere_driver.cpp
  components/scream/src/control/tests/ad_tests.yaml
  components/scream/src/diagnostics/tests/potential_temperature_test.cpp
  components/scream/src/dynamics/homme/dynamics_driven_grids_manager.cpp
  components/scream/src/mct_coupling/scream_cxx_f90_interface.cpp
  components/scream/src/share/atm_process/atmosphere_process_group.cpp
  components/scream/src/share/grid/mesh_free_grids_manager.cpp
  components/scream/src/share/io/tests/io.cpp
  components/scream/src/share/io/tests/output_restart.cpp
  components/scream/src/share/tests/CMakeLists.txt
  components/scream/src/share/tests/atm_process_tests.cpp
  components/scream/src/share/tests/atm_process_tests.yaml
  components/scream/src/share/tests/atm_process_tests_named_procs.yaml
  components/scream/src/share/tests/atm_process_tests_parse_list.yaml
  components/scream/src/share/util/scream_time_stamp.cpp
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_baseline.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_initial.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_restarted.yaml
  components/scream/tests/coupled/physics_only/atm_proc_subcycling/input.yaml
  components/scream/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/input.yaml
  components/scream/tests/uncoupled/cld_fraction/input.yaml
  components/scream/tests/uncoupled/homme/homme_standalone.cpp
  components/scream/tests/uncoupled/homme/input.yaml
  components/scream/tests/uncoupled/p3/input.yaml
  components/scream/tests/uncoupled/rrtmgp/input.yaml
  components/scream/tests/uncoupled/rrtmgp/input_unit.yaml
  components/scream/tests/uncoupled/shoc/input.yaml
  components/scream/tests/uncoupled/spa/input.yaml
  components/scream/tests/uncoupled/zm/input.yaml
Labels: SCREAMv1

#1584 Add F2010 compsets for running SCREAMv1
  cime_config/tests.py
  components/scream/cime_config/config_compsets.xml
Labels: B4B, SCREAMv1
