Repository E3SM-Project/scream, pull requests merged in 2022-01, with the labels that each got.

#1315 Add an aquaplanet compset for SCREAMv0
  components/eam/bld/namelist_files/namelist_defaults_eam.xml
  components/eam/bld/namelist_files/use_cases/aquaplanet_SCREAM-HR.xml
  components/eam/bld/namelist_files/use_cases/aquaplanet_SCREAM-LR.xml
  components/eam/cime_config/config_component.xml
  components/eam/cime_config/config_compsets.xml
  components/eam/src/physics/rrtmg/radiation.F90
Labels: B4B, AT: AUTOMERGE

#1360 Make adjust_ps consistent with SCREAM
  components/homme/src/share/prim_driver_base.F90
Labels: AT: AUTOMERGE

#1363 Mappy setup was not safe to call if already called
  components/scream/scripts/jenkins/mappy_setup
Labels: AT: AUTOMERGE

#1364 New scripts to help EKAT transition to better test system
  components/scream/scripts/jenkins/jenkins_cleanup.sh
  components/scream/scripts/jenkins/jenkins_common.sh
  components/scream/scripts/jenkins/jenkins_scripts_tests.sh
  components/scream/scripts/query-scream
  components/scream/scripts/query_scream.py
  components/scream/scripts/scream-env-cmd
  components/scream/scripts/source_to_load_scream_env.sh
Labels: AT: AUTOMERGE

#1366 Fix some cuda-memcheck errors in HommeDynamics
  components/scream/src/dynamics/homme/atmosphere_dynamics.cpp
Labels: AT: AUTOMERGE, bugfix, CUDA

#1365 Some fixes/changes to IO restart unit test
  components/scream/cmake/BuildCprnc.cmake
  components/scream/cmake/CprncTest.cmake.in
  components/scream/src/share/io/scorpio_output.cpp
  components/scream/src/share/io/tests/CMakeLists.txt
  components/scream/src/share/io/tests/CmpNcdumpOutput.cmake
  components/scream/src/share/io/tests/io.cpp
  components/scream/src/share/io/tests/io_test_average.yaml
  components/scream/src/share/io/tests/io_test_instant.yaml
  components/scream/src/share/io/tests/io_test_max.yaml
  components/scream/src/share/io/tests/io_test_min.yaml
  components/scream/src/share/io/tests/io_test_multisnap.yaml
  components/scream/src/share/io/tests/io_test_restart.yaml
  components/scream/src/share/io/tests/io_test_restart_check.yaml
  components/scream/src/share/io/tests/output_restart.cpp
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/dynamics_physics/model_restart/CMakeLists.txt
  components/scream/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/uncoupled/homme/CMakeLists.txt
  components/scream/tests/uncoupled/p3/CMakeLists.txt
  components/scream/tests/uncoupled/rrtmgp/CMakeLists.txt
  components/scream/tests/uncoupled/shoc/CMakeLists.txt
  components/scream/tests/uncoupled/spa/CMakeLists.txt
Labels: testing, I/O, AT: AUTOMERGE, code cleanup

#1354 Move field property check outside the Field class
  components/scream/src/dynamics/homme/atmosphere_dynamics.cpp
  components/scream/src/dynamics/homme/atmosphere_dynamics.hpp
  components/scream/src/physics/cld_fraction/atmosphere_cld_fraction.cpp
  components/scream/src/physics/p3/atmosphere_microphysics.cpp
  components/scream/src/physics/shoc/atmosphere_macrophysics.cpp
  components/scream/src/physics/shoc/atmosphere_macrophysics.hpp
  components/scream/src/share/atm_process/atmosphere_process.cpp
  components/scream/src/share/atm_process/atmosphere_process.hpp
  components/scream/src/share/field/field.hpp
  components/scream/src/share/field/field_manager.hpp
  components/scream/src/share/field/field_property_check.hpp
  components/scream/src/share/field/field_property_checks/check_and_repair_wrapper.hpp
  components/scream/src/share/field/field_property_checks/field_lower_bound_check.hpp
  components/scream/src/share/field/field_property_checks/field_nan_check.hpp
  components/scream/src/share/field/field_property_checks/field_positivity_check.hpp
  components/scream/src/share/field/field_property_checks/field_upper_bound_check.hpp
  components/scream/src/share/field/field_property_checks/field_within_interval_check.hpp
  components/scream/src/share/field/field_request.hpp
  components/scream/src/share/tests/atm_process_tests.cpp
  components/scream/src/share/tests/field_tests.cpp
  components/scream/src/share/util/map_key_iterator.hpp
  components/scream/src/share/util/pointer_list.hpp
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_baseline.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_initial.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_restarted.yaml
Labels: infrastructure, AT: AUTOMERGE

#1367 SCREAM: make model_restart test use the CreateUnitTestXYZ machineries
  components/scream/tests/coupled/dynamics_physics/model_restart/CMakeLists.txt
Labels: testing, cmake, AT: AUTOMERGE, code cleanup

#1368 SCREAM: fix cmake var typo that caused CIME build failures
  components/scream/src/share/io/CMakeLists.txt
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#1371 Add the possibility to subcycle any atm process
  components/scream/src/share/atm_process/atmosphere_process.cpp
  components/scream/src/share/atm_process/atmosphere_process.hpp
  components/scream/src/share/tests/atm_process_tests.cpp
Labels: infrastructure, AT: AUTOMERGE

#1358 Fix issues with surface coupling for F-Compset runs
  components/scream/src/control/surface_coupling.cpp
  components/scream/src/control/surface_coupling.hpp
  components/scream/src/control/tests/sc_tests.cpp
  components/scream/src/mct_coupling/CMakeLists.txt
  components/scream/src/mct_coupling/atm_comp_mct.F90
  components/scream/src/mct_coupling/cam_cpl_indices.F90
  components/scream/src/mct_coupling/dead_data_mod.F90
  components/scream/src/mct_coupling/dead_mct_mod.F90
  components/scream/src/mct_coupling/dead_mod.F90
Labels: bug, infrastructure, priority:high, CIME, Surface Coupling

#1373 Scale Faxa_rainl in SC::do_export
  components/scream/src/control/surface_coupling.cpp
  components/scream/src/control/surface_coupling.hpp
  components/scream/src/control/surface_coupling_export.cpp
  components/scream/src/control/tests/sc_tests.cpp
  components/scream/src/mct_coupling/scream_cpl_indices.F90
Labels: CIME

#1369 SCREAM: minor mods to BuildCprnc
  components/scream/cmake/BuildCprnc.cmake
Labels: cmake, AT: AUTOMERGE, code cleanup

#1375 Fix quartz and syrah SCREAM machine files to work with CIME
  components/scream/cmake/machine-files/quartz.cmake
  components/scream/cmake/machine-files/syrah.cmake
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#1378 Fix scream v1 compiler flags when building from CIME
  components/CMakeLists.txt
  components/scream/CMakeLists.txt
Labels: AT: AUTOMERGE, CIME

#1288 Convert wet mixing ratios to dry mixing ratios for P3 (Fortran and C++)
  components/eam/src/physics/cam/micro_p3_interface.F90
  components/eam/src/physics/cam/physics_utils.F90
  components/scream/src/physics/p3/atmosphere_microphysics.cpp
  components/scream/src/physics/p3/atmosphere_microphysics.hpp
  components/scream/src/share/tests/common_physics_functions_tests.cpp
  components/scream/src/share/util/scream_common_physics_functions.hpp
  components/scream/src/share/util/scream_common_physics_functions_impl.hpp
Labels: Non-B4B, p3, CIME

#1382 Refactor handling of scream_input.yaml
  components/scream/cime_config/buildnml
  components/scream/data/SCREAM_YAML_README
Labels: CIME
