Repository E3SM-Project/scream, pull requests merged in 2022-11, with the labels that each got.

#2013 fix call to get_pottemp
  components/homme/src/theta-l/share/element_ops.F90
Labels: SCREAMv0, SCREAMv1

#2011 Set the year values for DYAMOND-1 SSTICE data stream
  components/data_comps/docn/cime_config/config_component.xml
Labels: AT: AUTOMERGE

#2016 Avoid very expensive $phys_functions_f90.cpp compile if SCREAM_LIB_ONLY
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/p3_f90.cpp
  components/scream/src/physics/p3/p3_f90.hpp
  components/scream/src/physics/p3/p3_main_wrap.cpp
  components/scream/src/physics/p3/p3_main_wrap.hpp
  components/scream/src/physics/p3/tests/p3_run_and_cmp.cpp
  components/scream/src/physics/p3/tests/p3_tests.cpp
  components/scream/src/physics/shoc/CMakeLists.txt
  components/scream/src/physics/shoc/shoc_f90.cpp
  components/scream/src/physics/shoc/shoc_f90.hpp
  components/scream/src/physics/shoc/shoc_main_wrap.cpp
  components/scream/src/physics/shoc/shoc_main_wrap.hpp
  components/scream/src/physics/shoc/tests/shoc_run_and_cmp.cpp
  components/scream/src/physics/shoc/tests/shoc_tests.cpp
Labels: AT: AUTOMERGE, CIME

#2009 Prevent SHOC temperature from going negative
  components/eam/src/physics/cam/shoc.F90
  components/scream/src/physics/shoc/shoc_assumed_pdf_impl.hpp
Labels: B4B, shoc, AT: AUTOMERGE

#2007 Add a diagnostic that can vertically remap a field to new pressure levels
  components/scream/src/diagnostics/CMakeLists.txt
  components/scream/src/diagnostics/register_diagnostics.hpp
  components/scream/src/diagnostics/tests/CMakeLists.txt
  components/scream/src/diagnostics/tests/vertically_remapped_field_tests.cpp
  components/scream/src/diagnostics/vertically_remapped_field.cpp
  components/scream/src/diagnostics/vertically_remapped_field.hpp
Labels: B4B, AT: AUTOMERGE, AT: PRE-TEST INSPECTED, diagnostic

#2021 EAMxx: process rrtmgp sources with YAKL's macros to select compile language
  components/scream/src/physics/rrtmgp/CMakeLists.txt
Labels: cmake, radiation, AT: AUTOMERGE, bugfix, yakl

#2023 This commit fixes a bug in the team policy declaration for diagnostics.
  components/scream/src/diagnostics/dry_static_energy.cpp
  components/scream/src/diagnostics/dry_static_energy.hpp
  components/scream/src/diagnostics/vertical_layer_interface.cpp
  components/scream/src/diagnostics/vertical_layer_interface.hpp
  components/scream/src/diagnostics/vertical_layer_midpoint.cpp
  components/scream/src/diagnostics/vertical_layer_midpoint.hpp
Labels: B4B, AT: AUTOMERGE, bugfix, diagnostic

#2032 Revert PR 2021.
  components/scream/src/physics/rrtmgp/CMakeLists.txt
Labels: AT: AUTOMERGE, AT: PRE-TEST INSPECTED

#2022 EAMxx: minor mod to random test setup, to enhance reproducibility
  components/scream/src/share/util/scream_setup_random_test.hpp
Labels: enhancement, testing, code quality, AT: AUTOMERGE

#1989 Add a diagnostic to take variables at a specific pressure level
  components/scream/src/diagnostics/CMakeLists.txt
  components/scream/src/diagnostics/field_at_pressure_level.cpp
  components/scream/src/diagnostics/field_at_pressure_level.hpp
  components/scream/src/diagnostics/register_diagnostics.hpp
  components/scream/src/diagnostics/tests/CMakeLists.txt
  components/scream/src/diagnostics/tests/field_at_pressure_level_tests.cpp
  components/scream/src/share/io/scorpio_output.cpp
  components/scream/src/share/util/scream_vertical_interpolation.hpp
  components/scream/src/share/util/scream_vertical_interpolation_impl.hpp
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/homme_shoc_cld_spa_p3_rrtmgp_diagnostics.yaml
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/input.yaml
Labels: B4B, AT: AUTOMERGE, diagnostic

#2034 SCREAMv1 nightlies: Remove two MPASSI-based tests.
  cime_config/tests.py
Labels: testing, AT: AUTOMERGE, AT: Skip weaver, AT: Skip blake, AT: Skip v1 Testing

#2035 For NERSC CPU machines (and GCP), use serial kokkos backend when no threads in CIME case
  components/scream/cmake/machine-files/alvarez.cmake
  components/scream/cmake/machine-files/cori-knl.cmake
  components/scream/cmake/machine-files/gcp.cmake
  components/scream/cmake/machine-files/pm-cpu.cmake
Labels: Machine File, AT: AUTOMERGE, AT: Skip weaver, AT: Skip blake, cori, pm-cpu

#2037 Precipitation mass flux diagnostics
  components/scream/src/control/atmosphere_surface_coupling_exporter.cpp
  components/scream/src/diagnostics/CMakeLists.txt
  components/scream/src/diagnostics/precip_ice_surf_mass_flux.cpp
  components/scream/src/diagnostics/precip_ice_surf_mass_flux.hpp
  components/scream/src/diagnostics/precip_liq_surf_mass_flux.cpp
  components/scream/src/diagnostics/precip_liq_surf_mass_flux.hpp
  components/scream/src/diagnostics/register_diagnostics.hpp
  components/scream/src/diagnostics/tests/CMakeLists.txt
  components/scream/src/diagnostics/tests/precip_ice_surf_mass_flux_tests.cpp
  components/scream/src/diagnostics/tests/precip_liq_surf_mass_flux_tests.cpp
  components/scream/src/physics/p3/atmosphere_microphysics.cpp
  components/scream/src/share/atm_process/atmosphere_diagnostic.cpp
  components/scream/src/share/atm_process/atmosphere_diagnostic.hpp
  components/scream/tests/uncoupled/surface_coupling/surface_coupling.cpp
Labels: B4B, AT: AUTOMERGE, diagnostic

#2041 Improve qv_sat to allow more caller info
  components/scream/src/diagnostics/relative_humidity.cpp
  components/scream/src/physics/p3/impl/p3_ice_cldliq_wet_growth_impl.hpp
  components/scream/src/physics/p3/impl/p3_ice_melting_impl.hpp
  components/scream/src/physics/p3/impl/p3_main_impl_part1.hpp
  components/scream/src/physics/p3/impl/p3_prevent_liq_supersaturation_impl.hpp
  components/scream/src/physics/share/physics_functions.hpp
  components/scream/src/physics/share/physics_saturation_impl.hpp
  components/scream/src/physics/shoc/impl/shoc_assumed_pdf_impl.hpp
Labels: AT: AUTOMERGE

#2046 Fix CMake -O1 code for cori-knl.
  components/scream/src/physics/shoc/CMakeLists.txt
Labels: AT: AUTOMERGE, bugfix

#2049 On crusher-gpu, use CLI133_crusher as the project
  cime_config/machines/config_machines.xml
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2052 Crusher-GPU: Build CICE with -O0.
  cime_config/machines/Depends.crusher-gpu.crayclang.cmake
Labels: B4B, AT: AUTOMERGE, bugfix, crusher-gpu

#2053 Crusher-GPU: Fix one source of build errors for some tests.
  cime_config/machines/cmake_macros/crayclang_crusher-gpu.cmake
Labels: B4B, AT: AUTOMERGE, bugfix, crusher-gpu

#2055 crusher-gpu should not archive test data
  cime_config/machines/config_machines.xml
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2056 Jgfouca/upstream merge 2022 11 23
  cime_config/customize/provenance.py
  cime_config/machines/config_machines.xml
  cime_config/machines/syslog.alvarez
  cime_config/machines/syslog.pm-cpu
  cime_config/machines/syslog.pm-gpu
  cime_config/machines/template.case.run.sh
  components/data_comps/datm/cime_config/config_component.xml
  components/data_comps/datm/cime_config/namelist_definition_datm.xml
  components/data_comps/datm/src/datm_comp_mod.F90
  components/data_comps/datm/src/datm_shr_mod.F90
  components/data_comps/drof/cime_config/config_component.xml
  components/data_comps/drof/cime_config/namelist_definition_drof.xml
  components/homme/src/theta-l/share/element_ops.F90
  components/homme/src/theta-l_kokkos/cxx/CaarFunctorImpl.hpp
  components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml
  components/mpas-ocean/cime_config/config_compsets.xml
  components/mpas-seaice/bld/build-namelist
  components/mpas-seaice/bld/build-namelist-section
  components/mpas-seaice/bld/namelist_files/namelist_defaults_mpassi.xml
  components/mpas-seaice/bld/namelist_files/namelist_definition_mpassi.xml
  components/mpas-seaice/src/Registry.xml
  components/mpas-seaice/src/analysis_members/Registry_seaice_conservation_check.xml
  components/mpas-seaice/src/analysis_members/mpas_seaice_conservation_check.F
  components/mpas-seaice/src/column/ice_atmo.F90
  components/mpas-seaice/src/column/ice_colpkg.F90
  components/mpas-seaice/src/column/ice_mushy_physics.F90
  components/mpas-seaice/src/column/ice_therm_vertical.F90
  components/mpas-seaice/src/shared/mpas_seaice_column.F
  components/mpas-seaice/src/shared/mpas_seaice_constants.F
  components/mpas-seaice/src/shared/mpas_seaice_forcing.F
  components/mpas-seaice/src/shared/mpas_seaice_initialize.F
  share/timing/private.h
Labels: AT: AUTOMERGE, CIME

#2064 Lower the T_mid minimum cutoff to 100 from 130
  components/scream/src/dynamics/homme/atmosphere_dynamics.cpp
  components/scream/src/physics/p3/atmosphere_microphysics.cpp
  components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp
  components/scream/src/physics/shoc/atmosphere_macrophysics.cpp
Labels: AT: AUTOMERGE

#2066 Crusher: Remove -hzero from crayclang line.
  cime_config/machines/cmake_macros/crayclang_crusher-gpu.cmake
Labels: AT: Integrate Without Testing, crusher-gpu

#2051 Add the capability to produce regional output.
  components/eamxx/data/scream_default_remap.yaml
  components/eamxx/src/share/grid/abstract_grid.cpp
  components/eamxx/src/share/grid/abstract_grid.hpp
  components/eamxx/src/share/grid/remap/coarsening_remapper.cpp
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/tests/coarsening_remapper_tests.cpp
Labels: enhancement, B4B, I/O, AT: AUTOMERGE

#2072 Crusher: Enable threading specification for use in LND.
  cime_config/machines/config_machines.xml
Labels: AT: Integrate Without Testing

#2068 Jgfouca/upstream merge 2022 11 29
  components/eam/src/physics/crm/cospsimulator_intr.F90
  components/eam/src/physics/crm/crm_physics.F90
  components/eam/src/physics/crm/rrtmgp/radiation.F90
  components/homme/src/share/cxx/ExecSpaceDefs.cpp
  components/homme/src/share/cxx/PhysicalConstants.hpp
  components/homme/src/share/cxx/SimulationParams.hpp
  components/homme/src/share/cxx/utilities/BfbUtils.cpp
  components/homme/src/share/cxx/utilities/VectorUtils.hpp
  components/homme/src/share/cxx/utilities/bfb_mod.F90
  components/homme/src/theta-l/share/prim_advance_mod.F90
  components/homme/src/theta-l_kokkos/cxx/CaarFunctorImpl.hpp
  components/homme/src/theta-l_kokkos/cxx/ElementOps.hpp
  components/homme/src/theta-l_kokkos/cxx/cxx_f90_interface_theta.cpp
  components/homme/src/theta-l_kokkos/prim_driver_mod.F90
  components/homme/src/theta-l_kokkos/theta_f2c_mod.F90
  components/homme/test/reg_test/namelists/thetahs1.nl
Labels: AT: AUTOMERGE, CIME

#2074 Crusher: Work around SCORPIO threading issue.
  cime_config/machines/cmake_macros/crayclang.cmake
  cime_config/machines/cmake_macros/crayclang_crusher-gpu.cmake
Labels: AT: Integrate Without Testing, crusher-gpu

#2075 Crusher: Set default PE layout for ne30* to get more tests passing.
  cime_config/allactive/config_pesall.xml
Labels: AT: Integrate Without Testing

#2076 Crusher: Fix MAX_TASKS_PER_NODE to align with default PEs layout.
  cime_config/machines/config_machines.xml
Labels: AT: Integrate Without Testing
