Repository E3SM-Project/scream, pull requests merged in 2022-03, with the labels that each got.

#1445 Fix SC team policy issue on GPU
  components/scream/src/control/surface_coupling_export.cpp
  components/scream/src/control/tests/sc_tests.cpp
Labels: AT: AUTOMERGE, bugfix, CIME

#1442 Revert "Add logic to specify mach-specific flags in scream"
  components/scream/CMakeLists.txt
  components/scream/cmake/BuildCprnc.cmake
  components/scream/cmake/MachSpecificFlags.cmake
  components/scream/cmake/machine-files/quartz.cmake
  components/scream/cmake/machine-files/syrah.cmake
  components/scream/cmake/tpls/Scorpio.cmake
  components/scream/src/share/CMakeLists.txt
Labels: AT: AUTOMERGE, bugfix

#1432 WIP: Put tech docs in scream/docs/
  components/scream/docs/README.md
  components/scream/docs/amermeteorsoc.bst
  components/scream/docs/biblio.bib
  components/scream/docs/control/driver_doc.tex
  components/scream/docs/control/main.pdf
  components/scream/docs/control/main.tex
  components/scream/docs/main.pdf
  components/scream/docs/main.tex
  components/scream/docs/physics/p3/main.tex
  components/scream/docs/physics/psl/main.pdf
  components/scream/docs/physics/psl/main.tex
  components/scream/docs/physics/psl/psl_doc.tex
  components/scream/docs/physics/psl/psl_exactVSapprox.pdf
  components/scream/docs/physics/psl/psl_vs_v0.pdf
  components/scream/docs/physics/shoc/main.pdf
  components/scream/docs/physics/shoc/main.tex
  components/scream/docs/physics/shoc/shoc_doc.tex
Labels: B4B, documentation, AT: WIP

#1455 SCREAM: make '--baseline-dir AUTO' the default
  components/scream/scripts/test_all_scream.py
Labels: testing, AT: AUTOMERGE, scripts

#1456 Add CIME support for weaver
  cime_config/machines/cmake_macros/gnugpu_weaver.cmake
  cime_config/machines/config_batch.xml
  cime_config/machines/config_machines.xml
  components/scream/scripts/machines_specs.py
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#1247 Remove unused _f functions in P3
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_functions_f90.hpp
  components/scream/src/physics/p3/p3_iso_f.f90
Labels: AT: AUTOMERGE, CIME

#1457 SCREAM: micro fix to test-all-scream
  components/scream/scripts/test_all_scream.py
Labels: AT: AUTOMERGE, scripts, AT: Skip Stand-Alone Testing

#1458 Fix to get past insufficient slots error
  cime_config/machines/config_batch.xml
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#1459 Change weaver to use netcdf mode for PIO
  cime_config/machines/config_pio.xml
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#1460 SCREAM: fix test-all-scream support for arbitrary work dir
  components/scream/scripts/test_all_scream.py
Labels: AT: AUTOMERGE, AT: Integrate Without Testing, scripts

#1446 Introduce a unit test for spa_main
  components/scream/src/physics/spa/atmosphere_prescribed_aerosol.cpp
  components/scream/src/physics/spa/atmosphere_prescribed_aerosol.hpp
  components/scream/src/physics/spa/spa_functions.hpp
  components/scream/src/physics/spa/spa_functions_impl.hpp
  components/scream/src/physics/spa/tests/CMakeLists.txt
  components/scream/src/physics/spa/tests/spa_main.yaml
  components/scream/src/physics/spa/tests/spa_main_test.cpp
  components/scream/src/physics/spa/tests/spa_one_to_one_remap_test.cpp
  components/scream/src/physics/spa/tests/spa_read_data_from_file_test.cpp
Labels: testing, Non-B4B, AT: AUTOMERGE, code cleanup, CIME, SPA

#1466 Fix build times, perl env, and cprnc
  cime_config/machines/config_batch.xml
  cime_config/machines/config_machines.xml
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#1419 Enable aerosol optics for RRTMGP
  components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp
  components/scream/src/physics/rrtmgp/atmosphere_radiation.hpp
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.cpp
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.hpp
  components/scream/src/physics/rrtmgp/tests/generate_baseline.cpp
  components/scream/src/physics/rrtmgp/tests/rrtmgp_tests.cpp
  components/scream/src/physics/spa/atmosphere_prescribed_aerosol.cpp
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_baseline.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_initial.yaml
  components/scream/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/input.yaml
  components/scream/tests/uncoupled/rrtmgp/input.yaml
  components/scream/tests/uncoupled/rrtmgp/input_unit.yaml
Labels: Non-B4B, radiation, AT: AUTOMERGE, priority:high, SPA, SCREAMv1

#1472 SCREAM: fix compilation error on CUDA
  components/scream/src/control/CMakeLists.txt
Labels: cmake, AT: AUTOMERGE, bugfix, CUDA, SCREAMv1

#1475 SCREAM: fix kernel access to class member in rrtmgp
  components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp
Labels: radiation, AT: AUTOMERGE, bugfix, valgrind / cuda-memcheck, CUDA

#1473 Apply scaling to incoming solar flux to account for orbital eccentricity
  components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.cpp
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.hpp
  components/scream/src/physics/rrtmgp/tests/generate_baseline.cpp
  components/scream/src/physics/rrtmgp/tests/rrtmgp_tests.cpp
  components/scream/tests/uncoupled/rrtmgp/input_unit.yaml
Labels: radiation, SCREAMv1

#1413 Add ne1024pg2_ICOS10 grid and supporting files
  cime_config/config_grids.xml
  components/elm/bld/namelist_files/namelist_defaults.xml
  components/elm/bld/namelist_files/namelist_definition.xml
  components/mpas-seaice/cime_config/buildnml
Labels: AT: AUTOMERGE, CIME

#1471 SCREAM: disable baselines logic for certain builds in test-all-scream
  components/scream/CMakeLists.txt
  components/scream/scripts/test_all_scream.py
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/rrtmgp/tests/CMakeLists.txt
  components/scream/src/physics/shoc/tests/CMakeLists.txt
  components/scream/tests/coupled/CMakeLists.txt
  components/scream/tests/uncoupled/CMakeLists.txt
  components/scream/tests/uncoupled/rrtmgp/CMakeLists.txt
  components/scream/tests/uncoupled/rrtmgp/rrtmgp_standalone_unit.cpp
Labels: enhancement, AT: AUTOMERGE, scripts

#1454 Add PSL to cpl export
  components/scream/docs/physics/psl/main.pdf
  components/scream/docs/physics/psl/psl_exactVSapprox.pdf
  components/scream/docs/physics/psl/psl_vs_v0.pdf
  components/scream/src/control/surface_coupling.cpp
  components/scream/src/control/surface_coupling.hpp
  components/scream/src/control/surface_coupling_export.cpp
  components/scream/src/control/tests/sc_tests.cpp
  components/scream/src/mct_coupling/scream_cpl_indices.F90
  components/scream/src/share/tests/common_physics_functions_tests.cpp
  components/scream/src/share/util/scream_common_physics_functions.hpp
  components/scream/src/share/util/scream_common_physics_functions_impl.hpp
Labels: Non-B4B, CIME, Surface Coupling

#1481 Add arg to jsrun for summit
  cime_config/machines/config_machines.xml
  components/scream/scripts/machines_specs.py
Labels: bugfix, AT: Integrate Without Testing

#1482 Fix coverage build mode
  components/scream/CMakeLists.txt
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#1489 Make default timestep 5min for SCREAMv1 CIME cases
  cime_config/tests.py
  components/scream/cime_config/testdefs/testmods_dirs/scream/30min_ts/shell_commands
  driver-mct/cime_config/config_component_e3sm.xml
Labels: Non-B4B, CIME, SCREAMv1

#1500 Set default PIO output type to be 64bit
  components/scream/src/share/io/scream_scorpio_interface.F90
Labels: I/O, AT: AUTOMERGE, bugfix, CIME, SCREAMv1

#1501 Fix scorpio cmake settings for scream
  components/scream/cmake/tpls/Scorpio.cmake
  components/scream/src/share/io/scream_scorpio_interface.F90
Labels: AT: AUTOMERGE, CIME

#1498 For integer types storing sizes in bytes, use size_t
  components/scream/src/dynamics/homme/atmosphere_dynamics.cpp
  components/scream/src/dynamics/homme/atmosphere_dynamics.hpp
  components/scream/src/physics/p3/atmosphere_microphysics.cpp
  components/scream/src/physics/p3/atmosphere_microphysics.hpp
  components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp
  components/scream/src/physics/rrtmgp/atmosphere_radiation.hpp
  components/scream/src/physics/shoc/atmosphere_macrophysics.cpp
  components/scream/src/physics/shoc/atmosphere_macrophysics.hpp
  components/scream/src/physics/spa/atmosphere_prescribed_aerosol.cpp
  components/scream/src/physics/spa/atmosphere_prescribed_aerosol.hpp
  components/scream/src/share/atm_process/ATMBufferManager.hpp
  components/scream/src/share/atm_process/atmosphere_process.hpp
Labels: AT: AUTOMERGE, CIME, SCREAMv1

#1487 SCREAM: fix valgrind error related to homme's readnl
  components/scream/src/dynamics/homme/tests/theta.nl
Labels: AT: AUTOMERGE, bugfix, valgrind / cuda-memcheck

#1356 Remove temporary override of tensor HV setting for ne4
  components/eam/bld/namelist_files/namelist_defaults_eam.xml
Labels: Non-B4B, AT: AUTOMERGE, dynamics, CIME

#1491 Use 10 tracers and field checking by default
  components/scream/cime_config/config_component.xml
  components/scream/data/scream_input.yaml
Labels: B4B, AT: AUTOMERGE

#1513 Be consistent in referring to cori as cori-knl
  components/scream/cmake/machine-files/cori-knl.cmake
  components/scream/scripts/machines_specs.py
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#1511 Add clone method to Field class
  components/scream/src/share/atm_process/atmosphere_diagnostic.cpp
  components/scream/src/share/field/field.cpp
  components/scream/src/share/field/field.hpp
  components/scream/src/share/field/field_utils_impl.hpp
  components/scream/src/share/tests/field_tests.cpp
  components/scream/src/share/util/scream_utils.hpp
Labels: enhancement, AT: AUTOMERGE

#1512 Quickfix to the scream_input.yaml file for pre/post checks
  components/scream/data/scream_input.yaml
Labels: B4B, AT: AUTOMERGE, bugfix, CIME
