Repository E3SM-Project/scream, pull requests merged in 2022-02, with the labels that each got.

#1390 Add units and long-name to SCREAM netcdf output
  components/scream/src/share/io/scorpio_output.cpp
  components/scream/src/share/io/scream_output_manager.cpp
  components/scream/src/share/io/scream_scorpio_interface.F90
  components/scream/src/share/io/scream_scorpio_interface.cpp
  components/scream/src/share/io/scream_scorpio_interface.hpp
  components/scream/src/share/io/scream_scorpio_interface_iso_c2f.F90
Labels: B4B, I/O, AT: AUTOMERGE

#1388 Update homme namelist options for SCREAMv1 run.
  components/scream/data/scream_input.yaml
  components/scream/data/screamv1_output.yaml
Labels: Non-B4B, homme, CIME

#1381 Add a SCREAMv1 aquaplanet compset
  cime_config/tests.py
  components/scream/cime_config/buildnml
  components/scream/cime_config/config_compsets.xml
  components/scream/data/scream_input.yaml
  components/scream/src/control/atmosphere_driver.cpp
  components/scream/src/physics/p3/atmosphere_microphysics.cpp
  components/scream/src/physics/shoc/atmosphere_macrophysics.cpp
Labels: testing, B4B, AT: AUTOMERGE, CIME, AT: Skip weaver, AT: Skip blake, SCREAMv1

#1396 Hot-fix to the set of output fields.
  components/scream/data/scream_input.yaml
  components/scream/data/scream_output.yaml
Labels: bug, B4B, AT: AUTOMERGE, priority:high, CIME, SCREAMv1

#1398 Fix to allow dynamics output for DP-SCREAM
  components/eam/src/dynamics/se/stepon.F90
Labels: B4B, AT: AUTOMERGE

#1403 Bugfix to when we reset the number of nsteps since the last write.
  components/scream/src/share/io/scream_output_manager.cpp
Labels: bug, B4B, I/O, AT: AUTOMERGE

#1397 Compute and expose surface radiative fluxes
  components/scream/src/physics/rrtmgp/CMakeLists.txt
  components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp
  components/scream/src/physics/rrtmgp/atmosphere_radiation.hpp
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.cpp
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.hpp
  components/scream/src/physics/rrtmgp/tests/generate_baseline.cpp
  components/scream/src/physics/rrtmgp/tests/rrtmgp_tests.cpp
  components/scream/src/physics/rrtmgp/tests/rrtmgp_unit_tests.cpp
Labels: B4B, radiation, AT: AUTOMERGE, SCREAMv1

#1401 Change output netcdf time units to days
  components/scream/src/share/io/scream_output_manager.cpp
  components/scream/src/share/io/scream_scorpio_interface.F90
  components/scream/src/share/util/scream_time_stamp.cpp
  components/scream/src/share/util/scream_time_stamp.hpp
Labels: B4B, I/O, AT: AUTOMERGE, AT: Skip mappy, AT: Skip blake

#1402 Add surface radiative fluxes to surface coupling
  components/scream/src/control/tests/sc_tests.cpp
  components/scream/src/mct_coupling/scream_cpl_indices.F90
Labels: AT: AUTOMERGE, CIME

#1395 Fix dimensions of dry/wet mixing variables in p3
  components/eam/src/physics/cam/micro_p3_interface.F90
Labels: B4B, p3, AT: AUTOMERGE, bugfix, CIME, SCREAMv0

#1404 Quick fix to the default settings for scream_output.yaml
  components/scream/data/scream_output.yaml
Labels: B4B, AT: AUTOMERGE, CIME, SCREAMv1, AT: Skip Stand-Alone Testing

#1405 Valgrind fixes
  components/scream/src/dynamics/homme/interface/homme_params_mod.F90
Labels: AT: AUTOMERGE, bugfix, valgrind / cuda-memcheck

#1406 Make check_input more robust
  components/scream/scripts/check_input.py
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#1387 Upgrades to scripts-tests framework
  components/scream/CMakeLists.txt
  components/scream/cmake/ctest_script.cmake
  components/scream/scripts/scripts-tests
  components/scream/scripts/test-all-scream
  components/scream/scripts/test_all_scream.py
  components/scream/src/CMakeLists.txt
  components/scream/src/physics/CMakeLists.txt
  components/scream/src/physics/p3/CMakeLists.txt
  components/scream/src/physics/p3/p3_rain_sed_impl.hpp
  components/scream/src/physics/p3/tests/CMakeLists.txt
  components/scream/src/physics/p3/tests/p3_rain_sed_unit_tests.cpp
  components/scream/src/physics/p3/tests/p3_run_and_cmp.cpp
  components/scream/src/share/CMakeLists.txt
  components/scream/tests/CMakeLists.txt
  components/scream/tests/generic/CMakeLists.txt
  components/scream/tests/generic/fail_check/CMakeLists.txt
  components/scream/tests/generic/fail_check/fail.cpp
  components/scream/tests/generic/fail_check/fpe_fail.cpp
  components/scream/tests/generic/fail_check/kokkos_fail.cpp
  components/scream/tests/generic/fail_check/valg_fail.cpp
  components/scream/tests/generic/infra/CMakeLists.txt
  components/scream/tests/generic/infra/fake_test.cpp
  components/scream/tests/meta-tests/CMakeLists.txt
  components/scream/tests/meta-tests/build_fail.cpp
  components/scream/tests/meta-tests/resource_spread.cpp
  components/scream/tests/meta-tests/test_fail.cpp
Labels: testing, AT: AUTOMERGE, scripts

#1383 SCREAM: add some fine-grain switches when testing with jenkins
  components/scream/scripts/jenkins/jenkins_common_impl.sh
Labels: SCREAMv0, SCREAMv1, AT: Skip Stand-Alone Testing

#1407 Enable setting fixed orbital parameters
  components/scream/data/scream_input.yaml
  components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp
  components/scream/src/physics/rrtmgp/atmosphere_radiation.hpp
  components/scream/src/physics/rrtmgp/share/shr_orb_mod_c2f.F90
  components/scream/src/physics/rrtmgp/share/shr_orb_mod_c2f.hpp
Labels: Non-B4B, radiation, bugfix, CIME, SCREAMv1

#1408 Fix p3 tests "will-fail" logic on CUDA builds
  components/scream/src/physics/p3/tests/CMakeLists.txt
Labels: testing, AT: AUTOMERGE, bugfix, valgrind / cuda-memcheck, CUDA

#1409 Move table init out of p3_main()
  components/scream/src/physics/p3/atmosphere_microphysics.cpp
  components/scream/src/physics/p3/atmosphere_microphysics.hpp
  components/scream/src/physics/p3/atmosphere_microphysics_run.cpp
  components/scream/src/physics/p3/p3_functions.hpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_main_impl.hpp
Labels: B4B, p3, AT: AUTOMERGE, performance

#1412 Correct qc computation in shoc ad
  components/scream/src/physics/shoc/atmosphere_macrophysics.cpp
  components/scream/src/physics/shoc/atmosphere_macrophysics.hpp
Labels: B4B, shoc, AT: AUTOMERGE, Atmosphere Driver, bugfix

#1392 Revised theta_l definition to SHOC
  components/eam/src/physics/cam/shoc.F90
  components/eam/src/physics/cam/shoc_intr.F90
  components/scream/src/physics/shoc/atmosphere_macrophysics.hpp
  components/scream/src/physics/shoc/shoc_update_host_dse_impl.hpp
Labels: Non-B4B, shoc, AT: AUTOMERGE, CIME, AT: Skip weaver, AT: Skip blake

#1418 Update jenkins script to better handle out-of-date PRs
  components/scream/scripts/git-merge-ref
  components/scream/scripts/jenkins/jenkins_common_impl.sh
Labels: AT: AUTOMERGE, scripts, CIME

#1415 Add SPA to the set of default processes run for all SCREAMv1 F-Case
  components/scream/data/scream_input.yaml
  components/scream/data/scream_output.yaml
Labels: Non-B4B, priority:high, CIME, SPA, AT: Skip weaver, AT: Skip blake, SCREAMv1

#1417 add snowl to CPL
  components/scream/data/scream_output.yaml
  components/scream/src/control/atmosphere_driver.cpp
  components/scream/src/control/surface_coupling.cpp
  components/scream/src/control/surface_coupling.hpp
  components/scream/src/control/surface_coupling_export.cpp
  components/scream/src/control/tests/sc_tests.cpp
  components/scream/src/mct_coupling/scream_cpl_indices.F90
  components/scream/src/physics/p3/atmosphere_microphysics.cpp
  components/scream/src/physics/p3/atmosphere_microphysics.hpp
Labels: New Variables, Surface Coupling, SCREAMv1

#1416 Aarondonahue/add diagnostic class
  components/scream/src/CMakeLists.txt
  components/scream/src/diagnostics/CMakeLists.txt
  components/scream/src/diagnostics/potential_temperature.cpp
  components/scream/src/diagnostics/potential_temperature.hpp
  components/scream/src/diagnostics/tests/CMakeLists.txt
  components/scream/src/diagnostics/tests/potential_temperature_test.cpp
  components/scream/src/share/CMakeLists.txt
  components/scream/src/share/atm_process/atmosphere_diagnostic.cpp
  components/scream/src/share/atm_process/atmosphere_diagnostic.hpp
  components/scream/src/share/atm_process/atmosphere_process_utils.hpp
  components/scream/src/share/tests/atm_process_tests.cpp
  components/scream/src/share/tests/common_physics_functions_tests.cpp
Labels: enhancement, infrastructure, testing, B4B, AT: AUTOMERGE, Development Task, priority:medium, SCREAMv1

#1424 Change SPA tests to use standard input file system
  components/scream/data/scream_input.yaml
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/input.yaml
  components/scream/tests/uncoupled/spa/CMakeLists.txt
  components/scream/tests/uncoupled/spa/input.yaml
Labels: AT: AUTOMERGE

#1430 SCREAM: fix cmake var name
  components/scream/cmake/tpls/Scorpio.cmake
Labels: cmake, AT: AUTOMERGE, bugfix, SCREAMv1, AT: Skip Stand-Alone Testing

#1431 Emergency fix for mappy env
  cime_config/machines/config_machines.xml
  components/scream/scripts/jenkins/mappy_setup
  components/scream/scripts/machines_specs.py
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#1435 Fix creation of cmake targets wrapping scorpio libs in CIME builds
  components/scream/cmake/tpls/CsmShare.cmake
  components/scream/cmake/tpls/Scorpio.cmake
  components/scream/src/physics/spa/CMakeLists.txt
  components/scream/src/share/io/CMakeLists.txt
Labels: cmake, AT: AUTOMERGE, bugfix, SCREAMv1

#1438 Changes to allow building on Perlmutter
  components/scream/cmake/machine-files/perlmutter.cmake
  components/scream/scripts/machines_specs.py
Labels: Machine File, AT: AUTOMERGE, AT: Integrate Without Testing, SCREAMv1, Perlmutter

#1439 Add logic to specify mach-specific flags in scream
  components/scream/CMakeLists.txt
  components/scream/cmake/BuildCprnc.cmake
  components/scream/cmake/MachSpecificFlags.cmake
  components/scream/cmake/machine-files/quartz.cmake
  components/scream/cmake/machine-files/syrah.cmake
  components/scream/cmake/tpls/Scorpio.cmake
  components/scream/src/share/CMakeLists.txt
Labels: cmake, code quality, Machine File, AT: AUTOMERGE
