Repository E3SM-Project/scream, pull requests merged in 2022-05, with the labels that each got.

#1593 Adds the XML defaults to run an ne30 case for CIME
  components/scream/cime_config/namelist_defaults_scream.xml
  components/scream/src/physics/spa/atmosphere_prescribed_aerosol.cpp
  components/scream/src/physics/spa/spa_functions_impl.hpp
  driver-mct/cime_config/config_component_e3sm.xml
Labels: enhancement, Non-B4B, AT: AUTOMERGE, Development Task, priority:high, CIME, SCREAMv1

#1595 Homme optimize use of WSM
  components/scream/src/dynamics/homme/atmosphere_dynamics.cpp
Labels: AT: AUTOMERGE

#1589 restore pbl_height postcondition check
  components/scream/src/physics/shoc/atmosphere_macrophysics.cpp
Labels: B4B, shoc, AT: AUTOMERGE

#1599 Use file that exists input repo for ne30
  components/scream/cime_config/namelist_defaults_scream.xml
Labels: AT: AUTOMERGE, CIME, namelist

#1596 Adjust default SPA data files to reflect the new set of data files.
  components/scream/cime_config/namelist_defaults_scream.xml
  components/scream/src/physics/p3/atmosphere_microphysics.cpp
  components/scream/src/physics/spa/atmosphere_prescribed_aerosol.cpp
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/input.yaml
  components/scream/tests/uncoupled/spa/CMakeLists.txt
  components/scream/tests/uncoupled/spa/input.yaml
  driver-mct/cime_config/config_component_e3sm.xml
Labels: Non-B4B, CIME, SPA, AT: Skip weaver, AT: Skip blake, namelist

#1600 Adjust rrtmgp albedo checks to repair albedo's out of range.
  components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp
Labels: Non-B4B, radiation, AT: AUTOMERGE

#1606 Fix env setup in machine_specs.py
  components/scream/scripts/machines_specs.py
Labels: AT: AUTOMERGE, scripts

#1598 Fix bug in SHOC with calculation of cell grid length
  components/scream/src/physics/share/physics_constants.hpp
  components/scream/src/physics/shoc/atmosphere_macrophysics.cpp
  components/scream/src/physics/shoc/atmosphere_macrophysics.hpp
  components/scream/src/share/grid/point_grid.cpp
  components/scream/src/share/tests/common_physics_functions_tests.cpp
  components/scream/src/share/util/scream_common_physics_functions.hpp
  components/scream/src/share/util/scream_common_physics_functions_impl.hpp
  components/scream/tests/uncoupled/shoc/input.yaml
Labels: Non-B4B, homme, shoc, AT: AUTOMERGE, bugfix, priority:high, CIME

#1617 SCREAM: use same value of PI in SHOC for v1 and v0 code bases
  components/eam/src/physics/cam/shoc.F90
  components/scream/src/physics/share/physics_constants.hpp
Labels: AT: AUTOMERGE, bugfix, priority:high

#1618 Make the AT test v1 by default
  components/scream/scripts/jenkins/jenkins_common_impl.sh
Labels: AT: AUTOMERGE

#1573 Add python script to query atm configs, similar to xmlquery
  components/scream/cime_config/buildnml
  components/scream/cime_config/eamxx_buildnml_impl.py
  components/scream/cime_config/namelist_defaults_scream.xml
  components/scream/scripts/atm-config-chg
  components/scream/scripts/atm_manip.py
  components/scream/scripts/atmchange
  components/scream/scripts/atmquery
Labels: AT: AUTOMERGE, SCREAMv1

#1616 SHOC v1 buoyancy flux bug fix
  components/scream/src/physics/shoc/atmosphere_macrophysics.cpp
  components/scream/src/physics/shoc/atmosphere_macrophysics.hpp
Labels: Non-B4B, shoc, AT: AUTOMERGE, bugfix, priority:high, SCREAMv1

#1604 Allow unexpected resolutions and add ne120 defaults in XML
  components/scream/cime_config/namelist_defaults_scream.xml
Labels: enhancement, B4B, AT: AUTOMERGE, bugfix, CIME, AT: Skip Stand-Alone Testing

#1632 Work-around for slurm settings on perlmutter
  cime_config/machines/config_batch.xml
  components/scream/src/physics/spa/atmosphere_prescribed_aerosol.cpp
Labels: AT: AUTOMERGE, AT: Integrate Without Testing, SCREAMv1, Perlmutter

#1628 Slimmed down output request
  components/scream/data/scream_output.yaml
Labels: B4B, AT: AUTOMERGE

#1601 Allow to pass a Comm to field utils, to perform global operations
  components/scream/src/share/field/field_utils.hpp
  components/scream/src/share/field/field_utils_impl.hpp
  components/scream/src/share/tests/CMakeLists.txt
  components/scream/src/share/tests/field_tests.cpp
  components/scream/src/share/tests/field_utils.cpp
Labels: enhancement, AT: AUTOMERGE

#1602 Fixing SCREAMv1 restart run from cime
  components/scream/src/share/io/scream_output_manager.cpp
  components/scream/src/share/io/tests/output_restart.cpp
Labels: AT: AUTOMERGE, bugfix

#1637 Initialize SHOC v1 turbulence consistent with v0
  components/scream/src/physics/shoc/atmosphere_macrophysics.cpp
Labels: Non-B4B, shoc, AT: AUTOMERGE, priority:high, SCREAMv1

#1629 Use grid-mean condensate for cloud optics
  components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp
  components/scream/src/physics/rrtmgp/atmosphere_radiation.hpp
  components/scream/src/physics/rrtmgp/scream_rrtmgp_interface.hpp
Labels: Non-B4B, radiation, CIME, SCREAMv1

#1634 dtime updates
  driver-mct/cime_config/config_component_e3sm.xml
Labels: AT: RETEST, AT: AUTOMERGE, CIME, AT: Skip Stand-Alone Testing

#1642 Create scream high resolution test suite
  cime_config/tests.py
Labels: AT: Integrate Without Testing

#1645 Add scream/cmake/machine-files/chrysalis.cmake.
  components/scream/cmake/machine-files/chrysalis.cmake
Labels: Machine File, AT: AUTOMERGE, AT: Integrate Without Testing

#1630 Make "all or nothing" ice cloud fraction default in SCREAMv0 compsets
  components/eam/bld/namelist_files/namelist_defaults_eam.xml
  components/eam/bld/namelist_files/use_cases/2010_scream_hr.xml
  components/eam/bld/namelist_files/use_cases/2010_scream_hr_dyamond2.xml
  components/eam/bld/namelist_files/use_cases/2010_scream_lr.xml
  components/eam/bld/namelist_files/use_cases/2010_scream_lr_dyamond2.xml
  components/eam/bld/namelist_files/use_cases/dpscream_arm97.xml
Labels: AT: AUTOMERGE, priority:low, CIME, Cloud Fraction, SCREAMv0, AT: Skip Stand-Alone Testing, AT: Skip v1 Testing

#1643 Adjust the scream-scorpio interface freeing pio decomp memory when not needed
  components/scream/src/control/atmosphere_driver.cpp
  components/scream/src/dynamics/homme/tests/dyn_grid_io.cpp
  components/scream/src/physics/spa/atmosphere_prescribed_aerosol.cpp
  components/scream/src/physics/spa/spa_functions_impl.hpp
  components/scream/src/share/atm_process/atmosphere_process_group.cpp
  components/scream/src/share/io/scream_scorpio_interface.F90
Labels: enhancement, B4B, I/O, AT: AUTOMERGE, priority:high, CIME, SPA

#1652 Fix memory access error in unflatten_idx util
  components/scream/src/share/util/scream_array_utils.hpp
Labels: AT: AUTOMERGE, bugfix, valgrind / cuda-memcheck

#1655 Fix usage of parallel reduce in field property checks
  components/scream/src/share/property_checks/field_nan_check.cpp
  components/scream/src/share/property_checks/field_within_interval_check.cpp
  components/scream/src/share/tests/field_utils.cpp
Labels: AT: AUTOMERGE, bugfix, CUDA

#1619 Trim list of scream tests for CIME
  cime_config/tests.py
  components/scream/cime_config/buildnml
  components/scream/cime_config/config_compsets.xml
  components/scream/cime_config/eamxx_buildnml_impl.py
  components/scream/cime_config/namelist_defaults_scream.xml
  components/scream/data/scream_default_output.yaml
  components/scream/scripts/jenkins/jenkins_common_impl.sh
  components/scream/src/control/atmosphere_driver.cpp
  components/scream/src/dynamics/homme/tests/dyn_grid_io.cpp
  components/scream/src/share/io/CMakeLists.txt
  components/scream/src/share/io/scream_io_utils.cpp
  components/scream/src/share/io/scream_io_utils.hpp
  components/scream/src/share/io/scream_output_manager.cpp
  components/scream/src/share/io/scream_output_manager.hpp
  components/scream/src/share/io/tests/CMakeLists.txt
  components/scream/src/share/tests/utils_tests.cpp
  components/scream/src/share/util/scream_time_stamp.cpp
  components/scream/tests/coupled/dynamics_physics/model_restart/CMakeLists.txt
Labels: testing, AT: AUTOMERGE, SCREAMv0, SCREAMv1

#1658 SCREAM: run medres ERS test for 9 steps, not 9 days
  cime_config/tests.py
Labels: testing, AT: AUTOMERGE, AT: Integrate Without Testing

#1659 SCREAM: do not build diagnostics tests in CIME builds
  components/scream/src/diagnostics/CMakeLists.txt
Labels: cmake, AT: AUTOMERGE

#1667 Use YAKL_DEBUG for DEBUG builds
  components/scream/src/physics/rrtmgp/CMakeLists.txt
Labels: B4B, AT: AUTOMERGE, CIME

#1668 CIME fixes on Summit: Additional queues and explicit env vars
  cime_config/machines/config_batch.xml
  cime_config/machines/config_machines.xml
Labels: Machine File, AT: AUTOMERGE

#1649 Upstream merge 05 18 22
  cime_config/allactive/config_pesall.xml
  cime_config/machines/Depends.pm-cpu.gnu.cmake
  cime_config/machines/Depends.pm-cpu.nvidia.cmake
  cime_config/machines/Depends.pm-gpu.gnu.cmake
  cime_config/machines/Depends.pm-gpu.gnugpu.cmake
  cime_config/machines/Depends.pm-gpu.nvidia.cmake
  cime_config/machines/Depends.pm-gpu.nvidiagpu.cmake
  cime_config/machines/cmake_macros/amdclang_pm-cpu.cmake
  cime_config/machines/cmake_macros/crayclang_crusher.cmake
  cime_config/machines/cmake_macros/gnu_pm-cpu.cmake
  cime_config/machines/cmake_macros/gnu_pm-gpu.cmake
  cime_config/machines/cmake_macros/gnugpu_pm-gpu.cmake
  cime_config/machines/cmake_macros/nvidia.cmake
  cime_config/machines/cmake_macros/nvidia_pm-cpu.cmake
  cime_config/machines/cmake_macros/nvidia_pm-gpu.cmake
  cime_config/machines/cmake_macros/nvidiagpu_pm-gpu.cmake
  cime_config/machines/config_batch.xml
  cime_config/machines/config_machines.xml
  cime_config/tests.py
  components/eam/bld/configure
  components/eam/cime_config/config_component.xml
  components/eam/cime_config/config_compsets.xml
  components/eam/cime_config/config_pes.xml
  components/eam/cime_config/testdefs/testmods_dirs/eam/mmf_crmout/shell_commands
  components/eam/cime_config/testdefs/testmods_dirs/eam/mmf_samacc/shell_commands
  components/eam/cime_config/testdefs/testmods_dirs/eam/mmf_samomp/shell_commands
  components/eam/src/physics/cam/check_energy.F90
  components/eam/src/physics/cam/constituents.F90
  components/eam/src/physics/cam/physics_types.F90
  components/eam/src/physics/cam/physpkg.F90
  components/eam/src/physics/crm/physpkg.F90
  components/elm/cime_config/config_component.xml
  components/homme/utils/csm_share/shr_spfn_mod.F90
  components/mpas-albany-landice/src/mode_forward/mpas_li_core.F
  components/mpas-framework/src/framework/mpas_stream_manager.F
  components/mpas-ocean/cime_config/buildnml
  components/mpas-ocean/src/shared/mpas_ocn_tracer_ecosys.F
  components/mpas-ocean/src/tracer_groups/Registry_ecosys.xml
  driver-mct/main/cime_comp_mod.F90
Labels: e3sm-update, SCREAMv0, SCREAMv1

#1669 Fix atmosphere diagnostic class
  components/scream/src/diagnostics/tests/potential_temperature_test.cpp
  components/scream/src/share/atm_process/atmosphere_diagnostic.cpp
  components/scream/src/share/atm_process/atmosphere_diagnostic.hpp
  components/scream/src/share/io/scorpio_output.cpp
  components/scream/src/share/io/scorpio_output.hpp
  components/scream/src/share/io/tests/io.cpp
  components/scream/src/share/tests/atm_process_tests.cpp
Labels: infrastructure, AT: AUTOMERGE, bugfix

#1664 Fix v1 mac mic subcycles parameter
  components/scream/cime_config/namelist_defaults_scream.xml
  components/scream/src/physics/shoc/atmosphere_macrophysics.cpp
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/CMakeLists.txt
  components/scream/tests/coupled/dynamics_physics/model_restart/input_baseline.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_initial.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_restarted.yaml
  components/scream/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/input.yaml
  components/scream/tests/uncoupled/shoc/CMakeLists.txt
  components/scream/tests/uncoupled/shoc/input.yaml
Labels: Non-B4B, bugfix, SCREAMv1

#1672 Change machine names for Perlmutter
  components/scream/cmake/machine-files/pm-cpu.cmake
  components/scream/cmake/machine-files/pm-gpu.cmake
Labels: AT: AUTOMERGE, SCREAMv1, Perlmutter, pm-gpu

#1675 Remove ne30 aquaplanet test from medres test suite
  cime_config/tests.py
  components/scream/cime_config/namelist_defaults_scream.xml
Labels: AT: AUTOMERGE, AT: Skip Stand-Alone Testing

#1673 SCREAM: add cmake checks for SCREAM_INPUT_ROOT
  components/scream/CMakeLists.txt
Labels: cmake, AT: AUTOMERGE, AT: Skip mappy, AT: Skip weaver

#1679 Use -O1 on SCREAM_MACHINE cori-knl for some SHOC files.
  components/scream/src/physics/shoc/CMakeLists.txt
Labels: bug, infrastructure

#1647 Fix nccn in P3, F90 interface has conversion not in cpp version.
  components/eam/src/physics/cam/micro_p3.F90
  components/eam/src/physics/cam/micro_p3_interface.F90
  components/scream/cime_config/namelist_defaults_scream.xml
  components/scream/data/scream_default_output.yaml
  components/scream/src/physics/cld_fraction/cld_fraction_main_impl.hpp
  components/scream/src/physics/p3/atmosphere_microphysics.cpp
  components/scream/src/physics/p3/p3_functions_f90.cpp
  components/scream/src/physics/p3/p3_main_impl_part1.hpp
  components/scream/src/physics/p3/tests/p3_main_unit_tests.cpp
  components/scream/src/physics/spa/atmosphere_prescribed_aerosol.cpp
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/homme_shoc_cld_p3_rrtmgp_output.yaml
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/homme_shoc_cld_spa_p3_rrtmgp_output.yaml
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/CMakeLists.txt
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/homme_shoc_cld_spa_p3_rrtmgp_128levels_output.yaml
  components/scream/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/input.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/CMakeLists.txt
  components/scream/tests/coupled/dynamics_physics/model_restart/input_baseline.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_initial.yaml
  components/scream/tests/coupled/dynamics_physics/model_restart/input_restarted.yaml
  components/scream/tests/coupled/physics_only/atm_proc_subcycling/CMakeLists.txt
  components/scream/tests/coupled/physics_only/atm_proc_subcycling/input.yaml
  components/scream/tests/coupled/physics_only/atm_proc_subcycling/output.yaml
  components/scream/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/shoc_cld_p3_rrtmgp_output.yaml
  components/scream/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/scream/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/input.yaml
  components/scream/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/shoc_cld_spa_p3_rrtmgp_output.yaml
  components/scream/tests/uncoupled/cld_fraction/CMakeLists.txt
  components/scream/tests/uncoupled/homme/CMakeLists.txt
  components/scream/tests/uncoupled/homme/input.yaml
  components/scream/tests/uncoupled/p3/CMakeLists.txt
  components/scream/tests/uncoupled/p3/input.yaml
  components/scream/tests/uncoupled/p3/p3_standalone_output.yaml
  components/scream/tests/uncoupled/rrtmgp/CMakeLists.txt
  components/scream/tests/uncoupled/rrtmgp/input.yaml
  components/scream/tests/uncoupled/shoc/CMakeLists.txt
  components/scream/tests/uncoupled/shoc/input.yaml
  components/scream/tests/uncoupled/spa/CMakeLists.txt
  components/scream/tests/uncoupled/spa/input.yaml
  components/scream/tests/uncoupled/spa/spa_standalone_output.yaml
  components/scream/tests/uncoupled/zm/CMakeLists.txt
Labels: Non-B4B, p3, AT: AUTOMERGE, bugfix, priority:high, CIME

#1693 This commit fixes the restart_vs_monolithic unit test.
  components/scream/tests/coupled/dynamics_physics/model_restart/input_restarted.yaml
Labels: bug, B4B, AT: AUTOMERGE, AT: Skip v1 Testing

#1684 Add configuration for ne256np4_oRRS18to6v3 v0 grid
  cime_config/config_grids.xml
  components/eam/bld/config_files/horiz_grid.xml
  components/eam/bld/namelist_files/namelist_defaults_eam.xml
  components/eam/bld/namelist_files/use_cases/2010_scream_hr.xml
  components/eam/bld/namelist_files/use_cases/2010_scream_hr_dyamond2.xml
  components/eam/bld/namelist_files/use_cases/aquaplanet_SCREAM-HR.xml
  components/elm/bld/namelist_files/namelist_defaults.xml
  components/elm/bld/namelist_files/namelist_definition.xml
Labels: B4B, AT: AUTOMERGE, CIME, SCREAMv0, AT: Skip Stand-Alone Testing
