Repository E3SM-Project/scream, pull requests merged in 2023-09, with the labels that each got.

#2500 Fix leap year logic in EAMxx
  components/eamxx/src/mct_coupling/atm_comp_mct.F90
  components/eamxx/src/mct_coupling/scream_cxx_f90_interface.cpp
  components/eamxx/src/mct_coupling/scream_f2c_mod.F90
  components/eamxx/src/share/io/scream_output_manager.cpp
  components/eamxx/src/share/scream_config.cpp
  components/eamxx/src/share/scream_config.hpp
  components/eamxx/src/share/tests/eamxx_time_interpolation_tests.cpp
  components/eamxx/src/share/tests/utils_tests.cpp
  components/eamxx/src/share/util/eamxx_time_interpolation.cpp
  components/eamxx/src/share/util/scream_time_stamp.cpp
Labels: AT: AUTOMERGE, bugfix, CIME

#2467 SHOC warmT fix
  components/eam/bld/build-namelist
  components/eam/bld/namelist_files/namelist_defaults_eam.xml
  components/eam/bld/namelist_files/namelist_definition.xml
  components/eam/src/physics/cam/shoc.F90
  components/eam/src/physics/cam/shoc_intr.F90
  components/eamxx/src/physics/shoc/CMakeLists.txt
  components/eamxx/src/physics/shoc/disp/shoc_compute_shoc_temperature_disp.cpp
  components/eamxx/src/physics/shoc/disp/shoc_tke_disp.cpp
  components/eamxx/src/physics/shoc/eamxx_shoc_process_interface.cpp
  components/eamxx/src/physics/shoc/eamxx_shoc_process_interface.hpp
  components/eamxx/src/physics/shoc/eti/shoc_compute_shoc_temperature.cpp
  components/eamxx/src/physics/shoc/impl/shoc_compute_shoc_temperature_impl.hpp
  components/eamxx/src/physics/shoc/impl/shoc_eddy_diffusivities_impl.hpp
  components/eamxx/src/physics/shoc/impl/shoc_main_impl.hpp
  components/eamxx/src/physics/shoc/impl/shoc_tke_impl.hpp
  components/eamxx/src/physics/shoc/shoc_functions.hpp
  components/eamxx/src/physics/shoc/shoc_functions_f90.cpp
  components/eamxx/src/physics/shoc/shoc_functions_f90.hpp
  components/eamxx/src/physics/shoc/shoc_iso_c.f90
  components/eamxx/src/physics/shoc/shoc_iso_f.f90
  components/eamxx/src/physics/shoc/tests/CMakeLists.txt
  components/eamxx/src/physics/shoc/tests/shoc_compute_shoc_temperature_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_eddy_diffusivities_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_tke_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_unit_tests_common.hpp
Labels: help wanted, Non-B4B, shoc, SCREAMv0, SCREAMv1

#2504 Use bfb math functions in TMS F90 code
  components/eam/src/physics/cam/trb_mtn_stress.F90
  components/eamxx/src/physics/tms/impl/compute_tms_impl.hpp
Labels: AT: AUTOMERGE

#2507 Fix bug in coarsening remapper
  components/eamxx/src/dynamics/homme/eamxx_homme_process_interface.cpp
  components/eamxx/src/share/field/field_utils_impl.hpp
  components/eamxx/src/share/grid/remap/coarsening_remapper.cpp
Labels: I/O, AT: AUTOMERGE, bugfix, MPI

#2508 Fix cloud diagnostics when using chunks
  components/eamxx/src/physics/rrtmgp/eamxx_rrtmgp_process_interface.cpp
Labels: radiation, AT: AUTOMERGE, bugfix

#2512 Fix bug in how we parse rpointer file
  components/eamxx/src/share/io/scream_io_utils.cpp
  components/eamxx/src/share/io/scream_output_manager.cpp
  components/eamxx/src/share/io/scream_output_manager.hpp
  components/eamxx/src/share/io/tests/CMakeLists.txt
  components/eamxx/src/share/io/tests/io_utils.cpp
  components/eamxx/src/share/io/tests/output_restart.cpp
Labels: I/O, AT: AUTOMERGE, bugfix

#2510 Change in atm proc group specification, and upgrade to atmchange
  .gitignore
  components/eamxx/cime_config/eamxx_buildnml.py
  components/eamxx/cime_config/eamxx_buildnml_impl.py
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/docs/common/eamxx_params.md
  components/eamxx/scripts/atm_manip.py
  components/eamxx/scripts/cime-nml-tests
  components/eamxx/src/control/tests/ad_tests.cpp
  components/eamxx/src/control/tests/ad_tests.yaml
  components/eamxx/src/share/atm_process/atmosphere_process_group.cpp
  components/eamxx/src/share/tests/CMakeLists.txt
  components/eamxx/src/share/tests/atm_process_tests.cpp
  components/eamxx/src/share/tests/atm_process_tests_named_procs.yaml
  components/eamxx/src/share/tests/atm_process_tests_parse_list.yaml
  components/eamxx/src/share/tests/field_tests.cpp
  components/eamxx/src/share/tests/property_checks.cpp
Labels: enhancement, infrastructure, AT: AUTOMERGE, scripts, CIME, AT: Skip Stand-Alone Testing

#2516 Fix input file for standalone driver tests
  components/eamxx/tests/coupled/dynamics_physics/homme_mam4xx_pg2/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_pg2/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/model_restart/input_baseline.yaml
  components/eamxx/tests/coupled/dynamics_physics/model_restart/input_initial.yaml
  components/eamxx/tests/coupled/dynamics_physics/model_restart/input_restarted.yaml
  components/eamxx/tests/coupled/physics_only/atm_proc_subcycling/input.yaml
  components/eamxx/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/input.yaml
  components/eamxx/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/input.yaml
  components/eamxx/tests/uncoupled/cld_fraction/input.yaml
  components/eamxx/tests/uncoupled/cosp/input.yaml
  components/eamxx/tests/uncoupled/homme/input.yaml
  components/eamxx/tests/uncoupled/mam4/input.yaml
  components/eamxx/tests/uncoupled/ml_correction/input.yaml
  components/eamxx/tests/uncoupled/p3/input.yaml
  components/eamxx/tests/uncoupled/rrtmgp/input.yaml
  components/eamxx/tests/uncoupled/rrtmgp/input_unit.yaml
  components/eamxx/tests/uncoupled/shoc/input.yaml
  components/eamxx/tests/uncoupled/spa/input.yaml
  components/eamxx/tests/uncoupled/surface_coupling/input.yaml
  components/eamxx/tests/uncoupled/zm/input.yaml
Labels: testing, AT: AUTOMERGE, bugfix, AT: Skip v1 Testing

#2513 Add support for FieldAtHeight in I/O
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/tests/uncoupled/p3/p3_standalone_output.yaml
Labels: I/O, AT: AUTOMERGE

#2517 Fix cmake problems with V0
  cime_config/machines/config_machines.xml
  components/eamxx/scripts/machines_specs.py
Labels: AT: AUTOMERGE, AT: Skip weaver

#2515 Add a few debug/trace logging calls in some infrastructure classes.
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/share/atm_process/atmosphere_process.cpp
  components/eamxx/src/share/io/scream_output_manager.cpp
Labels: AT: AUTOMERGE, code usability

#2514 EAMxx: fix bug in scorpio output
  components/eamxx/src/diagnostics/liquid_water_path.hpp
  components/eamxx/src/diagnostics/precip_surf_mass_flux.cpp
  components/eamxx/src/diagnostics/tests/precip_liq_surf_mass_flux_tests.cpp
  components/eamxx/src/diagnostics/tests/precip_total_surf_mass_flux_tests.cpp
  components/eamxx/src/diagnostics/vapor_water_path.hpp
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/tests/coupled/dynamics_physics/model_restart/model_output.yaml
  components/eamxx/tests/coupled/dynamics_physics/model_restart/model_restart_output.yaml
Labels: I/O, AT: AUTOMERGE, bugfix

#2518 Removing old PIO modules in EAMXX
  components/eamxx/src/share/io/scream_scorpio_interface.F90
Labels: B4B, I/O, AT: AUTOMERGE

#2502 Add evp-patch module to pm-cpu and pm-gpu
  cime_config/machines/config_machines.xml
  components/eamxx/scripts/machines_specs.py
Labels: Machine File, AT: AUTOMERGE, pm-gpu, pm-cpu

#2526 minor fixes and formatting in output docs
  .github/workflows/gh-pages.yml
  components/eamxx/docs/user/model_output.md
Labels: AT: AUTOMERGE, documentation, AT: Integrate Without Testing

#2521 Frontier machine enviroment optimizations (rebase to master)
  cime_config/machines/Depends.frontier-scream-gpu.crayclang-scream.cmake
  cime_config/machines/cmake_macros/crayclang-scream.cmake
  cime_config/machines/cmake_macros/crayclang-scream_frontier-scream-gpu.cmake
  cime_config/machines/config_batch.xml
  cime_config/machines/config_machines.xml
Labels: Machine File, AT: AUTOMERGE, Frontier

#2529 Some mods to FieldHeader interface and storage
  components/eamxx/src/diagnostics/field_at_pressure_level.cpp
  components/eamxx/src/diagnostics/tests/field_at_pressure_level_tests.cpp
  components/eamxx/src/share/field/field_header.cpp
  components/eamxx/src/share/field/field_header.hpp
  components/eamxx/src/share/field/field_impl.hpp
  components/eamxx/src/share/grid/remap/coarsening_remapper.cpp
  components/eamxx/src/share/grid/remap/vertical_remapper.cpp
  components/eamxx/src/share/tests/field_tests.cpp
Labels: enhancement, infrastructure, AT: AUTOMERGE

#2540 Fix TMS race condition and remove packs form TMSFunctions
  components/eamxx/src/physics/share/CMakeLists.txt
  components/eamxx/src/physics/tms/CMakeLists.txt
  components/eamxx/src/physics/tms/eamxx_tms_process_interface.cpp
  components/eamxx/src/physics/tms/eamxx_tms_process_interface.hpp
  components/eamxx/src/physics/tms/impl/compute_tms_impl.hpp
  components/eamxx/src/physics/tms/tests/tms_unit_tests_common.hpp
  components/eamxx/src/physics/tms/tms_functions.hpp
  components/eamxx/src/physics/tms/tms_functions_f90.cpp
Labels: bugfix, GPU

#2531 add p3_sk_test and fix the bfb bug in nightly test
  components/eamxx/src/physics/p3/disp/p3_main_impl_disp.cpp
  components/eamxx/src/physics/p3/disp/p3_main_impl_part2_disp.cpp
  components/eamxx/src/physics/p3/impl/p3_get_latent_heat_impl.hpp
  components/eamxx/src/physics/p3/p3_functions.hpp
  components/eamxx/src/physics/p3/tests/CMakeLists.txt
Labels: AT: AUTOMERGE

#2544 Fix relative humidity units
  components/eamxx/src/diagnostics/relative_humidity.cpp
Labels: AT: AUTOMERGE, bugfix, diagnostic

#2535 Improve ML correction performance
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/src/physics/ml_correction/eamxx_ml_correction_process_interface.cpp
  components/eamxx/src/physics/ml_correction/eamxx_ml_correction_process_interface.hpp
  components/eamxx/src/physics/ml_correction/ml_correction.py
Labels: AT: AUTOMERGE, machine learning

#2545 Update ML correction unit test
  components/eamxx/src/physics/ml_correction/eamxx_ml_correction_process_interface.cpp
  components/eamxx/src/physics/ml_correction/eamxx_ml_correction_process_interface.hpp
  components/eamxx/src/physics/ml_correction/ml_correction.py
  components/eamxx/tests/uncoupled/ml_correction/ml_correction_standalone.cpp
Labels: AT: AUTOMERGE, machine learning

#2549 Crusher: Point to cprnc rather than build it.
  cime_config/machines/config_machines.xml
Labels: AT: Integrate Without Testing

#2546 Allow locally-empty layouts in AtmosphereInput
  components/eamxx/src/share/io/scorpio_input.cpp
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/io/tests/io_basic.cpp
  components/eamxx/src/share/io/tests/output_restart.cpp
Labels: I/O, AT: AUTOMERGE, bugfix

#2522 Fixes an inconsistency between standard IO and vertical remap files.
  components/eamxx/src/share/grid/remap/vertical_remapper.cpp
  components/eamxx/src/share/io/tests/io_remap_test.cpp
  components/eamxx/src/share/tests/vertical_remapper_tests.cpp
Labels: B4B, AT: AUTOMERGE

#2547 add calls to enable PBL diagnostic output (v0)
  components/eam/src/physics/cam/shoc_intr.F90
Labels: B4B, AT: AUTOMERGE, AT: Skip mappy, AT: Skip blake, SCREAMv0, AT: Skip v1 Testing

#2550 Ensure IO decomp tags do not clash
  components/eamxx/src/share/grid/abstract_grid.cpp
  components/eamxx/src/share/grid/abstract_grid.hpp
  components/eamxx/src/share/grid/remap/coarsening_remapper.cpp
  components/eamxx/src/share/grid/remap/horizontal_remap_utility.cpp
  components/eamxx/src/share/grid/remap/vertical_remapper.cpp
  components/eamxx/src/share/io/scorpio_input.cpp
  components/eamxx/src/share/io/scorpio_output.cpp
Labels: I/O, AT: AUTOMERGE, bugfix

#2484 Update nudging process in EAMxx to be more flexible
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/docs/developer/processes.md
  components/eamxx/src/physics/nudging/eamxx_nudging_process_interface.cpp
  components/eamxx/src/physics/nudging/eamxx_nudging_process_interface.hpp
  components/eamxx/src/physics/nudging/nudging_functions.hpp
  components/eamxx/src/physics/nudging/tests/nudging_tests.cpp
  components/eamxx/src/physics/shoc/eamxx_shoc_process_interface.cpp
  components/eamxx/src/share/field/field_impl.hpp
  components/eamxx/src/share/io/scream_scorpio_interface.F90
  components/eamxx/src/share/util/eamxx_time_interpolation.cpp
  components/eamxx/tests/coupled/physics_only/CMakeLists.txt
  components/eamxx/tests/coupled/physics_only/shoc_p3_nudging/CMakeLists.txt
  components/eamxx/tests/coupled/physics_only/shoc_p3_nudging/create_vert_remap.cpp
  components/eamxx/tests/coupled/physics_only/shoc_p3_nudging/input_nudging.yaml
  components/eamxx/tests/coupled/physics_only/shoc_p3_nudging/input_source_data.yaml
  components/eamxx/tests/coupled/physics_only/shoc_p3_nudging/output.yaml
  components/eamxx/tests/coupled/physics_only/shoc_p3_nudging/output_remapped.yaml
  components/eamxx/tests/coupled/physics_only/shoc_p3_nudging/shoc_p3_nudging.cpp
Labels: AT: AUTOMERGE, nudging

#2530 Add effective radius of rain and rain precipitation fraction outputs
  components/eam/src/physics/p3/scream/micro_p3.F90
  components/eam/src/physics/p3/scream/micro_p3_interface.F90
  components/eamxx/data/scream_default_output.yaml
  components/eamxx/data/scream_default_remap.yaml
  components/eamxx/src/physics/p3/disp/p3_main_impl_disp.cpp
  components/eamxx/src/physics/p3/disp/p3_main_impl_part3_disp.cpp
  components/eamxx/src/physics/p3/eamxx_p3_process_interface.cpp
  components/eamxx/src/physics/p3/eamxx_p3_process_interface.hpp
  components/eamxx/src/physics/p3/impl/p3_main_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_main_impl_part3.hpp
  components/eamxx/src/physics/p3/p3_f90.cpp
  components/eamxx/src/physics/p3/p3_f90.hpp
  components/eamxx/src/physics/p3/p3_functions.hpp
  components/eamxx/src/physics/p3/p3_functions_f90.cpp
  components/eamxx/src/physics/p3/p3_functions_f90.hpp
  components/eamxx/src/physics/p3/p3_iso_c.f90
  components/eamxx/src/physics/p3/p3_main_wrap.cpp
  components/eamxx/src/physics/p3/tests/p3_main_unit_tests.cpp
  components/eamxx/src/physics/p3/tests/p3_tests.cpp
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/homme_shoc_cld_p3_rrtmgp_output.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/homme_shoc_cld_spa_p3_rrtmgp_output.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/homme_shoc_cld_spa_p3_rrtmgp_128levels_output.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_pg2/homme_shoc_cld_spa_p3_rrtmgp_pg2_output.yaml
  components/eamxx/tests/coupled/dynamics_physics/model_restart/model_output.yaml
  components/eamxx/tests/coupled/dynamics_physics/model_restart/model_restart_output.yaml
  components/eamxx/tests/coupled/physics_only/atm_proc_subcycling/output.yaml
  components/eamxx/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/shoc_cld_p3_rrtmgp_output.yaml
  components/eamxx/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/shoc_cld_spa_p3_rrtmgp_output.yaml
  components/eamxx/tests/uncoupled/p3/p3_standalone_output.yaml
Labels: BFB, p3

#2551 More cess-production additions.
  components/eamxx/src/share/grid/abstract_grid.cpp
  components/eamxx/src/share/grid/abstract_grid.hpp
  components/eamxx/src/share/grid/remap/coarsening_remapper.cpp
  components/eamxx/src/share/grid/remap/horizontal_remap_utility.cpp
  components/eamxx/src/share/grid/remap/vertical_remapper.cpp
  components/eamxx/src/share/io/scorpio_input.cpp
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/io/tests/io_basic.cpp
  components/eamxx/src/share/io/tests/io_remap_test.cpp
  components/eamxx/src/share/io/tests/output_restart.cpp
  components/eamxx/src/share/tests/vertical_remapper_tests.cpp
Labels: simulation Cess 2023

#2552 TOSS4 Intel mkl update
  cime_config/machines/cmake_macros/intel_quartz.cmake
  cime_config/machines/cmake_macros/intel_ruby.cmake
  components/eamxx/cmake/machine-files/quartz-intel.cmake
  components/eamxx/cmake/machine-files/quartz.cmake
  components/eamxx/cmake/machine-files/ruby-intel.cmake
  components/eamxx/cmake/machine-files/ruby.cmake
Labels: cmake, Machine File, AT: AUTOMERGE, AT: Integrate Without Testing

#2527 fix shoc energy fixer
  components/eam/src/physics/cam/physpkg.F90
  components/eam/src/physics/cam/shoc.F90
  components/eam/src/physics/cam/shoc_intr.F90
  components/eamxx/src/physics/shoc/impl/shoc_energy_fixer_impl.hpp
  components/eamxx/src/physics/shoc/shoc_f90.cpp
  components/eamxx/src/physics/shoc/shoc_functions_f90.cpp
  components/eamxx/src/physics/shoc/shoc_functions_f90.hpp
  components/eamxx/src/physics/shoc/shoc_iso_c.f90
  components/eamxx/src/physics/shoc/tests/shoc_energy_total_fixer_tests.cpp
Labels: Non-B4B

#2555 Set default macmic=6 for ne256 and macmic=2 for ne512
  components/eamxx/cime_config/namelist_defaults_scream.xml
Labels: p3, shoc, AT: AUTOMERGE, AT: Skip Stand-Alone Testing, namelist

#2553 Add special "io: string attributes" field extra data, which IO will write to file
  components/eamxx/src/diagnostics/field_at_height.cpp
  components/eamxx/src/diagnostics/field_at_height.hpp
  components/eamxx/src/diagnostics/field_at_level.cpp
  components/eamxx/src/diagnostics/field_at_level.hpp
  components/eamxx/src/diagnostics/field_at_pressure_level.cpp
  components/eamxx/src/diagnostics/field_at_pressure_level.hpp
  components/eamxx/src/share/field/field_header.cpp
  components/eamxx/src/share/field/field_header.hpp
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/io/scream_scorpio_interface.F90
  components/eamxx/src/share/io/scream_scorpio_interface.cpp
  components/eamxx/src/share/io/scream_scorpio_interface.hpp
  components/eamxx/src/share/io/scream_scorpio_interface_iso_c2f.F90
  components/eamxx/src/share/io/tests/io_basic.cpp
  components/eamxx/src/share/io/tests/io_remap_test.cpp
Labels: enhancement, I/O

#2559 quick fix to ensure the proper units are added to netCDF metadata
  components/eamxx/src/share/io/scorpio_output.cpp
Labels: BFB, I/O, AT: AUTOMERGE, bugfix

#2554 Add runtime options to control shoc - isotropic_ts
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/src/physics/share/physics_constants.hpp
  components/eamxx/src/physics/shoc/disp/shoc_tke_disp.cpp
  components/eamxx/src/physics/shoc/eamxx_shoc_process_interface.cpp
  components/eamxx/src/physics/shoc/eamxx_shoc_process_interface.hpp
  components/eamxx/src/physics/shoc/impl/shoc_isotropic_ts_impl.hpp
  components/eamxx/src/physics/shoc/impl/shoc_main_impl.hpp
  components/eamxx/src/physics/shoc/impl/shoc_tke_impl.hpp
  components/eamxx/src/physics/shoc/shoc_functions.hpp
  components/eamxx/src/physics/shoc/shoc_functions_f90.cpp
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_pg2/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/model_restart/input_baseline.yaml
  components/eamxx/tests/coupled/dynamics_physics/model_restart/input_initial.yaml
  components/eamxx/tests/coupled/dynamics_physics/model_restart/input_restarted.yaml
  components/eamxx/tests/coupled/physics_only/atm_proc_subcycling/input.yaml
  components/eamxx/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/input.yaml
  components/eamxx/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/input.yaml
  components/eamxx/tests/coupled/physics_only/shoc_p3_nudging/Testing/Temporary/CTestCostData.txt
  components/eamxx/tests/coupled/physics_only/shoc_p3_nudging/input_nudging.yaml
  components/eamxx/tests/coupled/physics_only/shoc_p3_nudging/input_source_data.yaml
  components/eamxx/tests/uncoupled/shoc/input.yaml
Labels: BFB, shoc, AT: AUTOMERGE
