Repository E3SM-Project/scream, pull requests merged in 2023-03, with the labels that each got.

#2205 Fix config_archive.xml
  cime_config/config_archive.xml
Labels: AT: Integrate Without Testing, CIME

#2206 Must use FORCE to set cache vars that have already been set
  components/eamxx/cmake/machine-files/ascent.cmake
  components/eamxx/cmake/machine-files/compy.cmake
  components/eamxx/cmake/machine-files/summit.cmake
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2209 Fix baseline gen on weaver
  components/eamxx/src/physics/p3/tests/CMakeLists.txt
  components/eamxx/src/physics/shoc/tests/CMakeLists.txt
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2207 Allow CIME to use ${mach}-${compiler}.cmake machine files
  components/cmake/build_eamxx.cmake
  components/eamxx/cmake/machine-files/README.md
Labels: AT: AUTOMERGE, AT: Skip mappy, AT: Skip blake

#2208 Improve jenkins output when things fail.
  components/eamxx/scripts/jenkins/jenkins_common_impl.sh
Labels: AT: AUTOMERGE

#2210 Add EKAT standalone tests to nightly test-all-scream runs
  components/eamxx/scripts/jenkins/jenkins_common_impl.sh
  components/eamxx/tests/generic/fail_check/CMakeLists.txt
Labels: AT: AUTOMERGE, AT: Skip v1 Testing

#2211 Update some comments related to output code
  components/eamxx/data/scream_default_output.yaml
  components/eamxx/src/share/io/scorpio_output.hpp
Labels: code quality, AT: AUTOMERGE, AT: Skip mappy, AT: Skip weaver, AT: Skip blake

#2218 Fix test-all-scream on quartz
  components/eamxx/scripts/test_all_scream.py
Labels: AT: AUTOMERGE, scripts, AT: Skip v1 Testing

#2214 Eamxx big buildnml refresh
  components/eamxx/cime_config/buildnml
  components/eamxx/cime_config/config_component.xml
  components/eamxx/cime_config/eamxx_buildnml.py
  components/eamxx/cime_config/eamxx_buildnml_impl.py
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/scream_example_testmod_atmchange/shell_commands
  components/eamxx/scripts/atm_manip.py
  components/eamxx/scripts/atmchange
  components/eamxx/scripts/atmquery
  components/eamxx/scripts/cime-nml-tests
  components/eamxx/scripts/jenkins/jenkins_common_impl.sh
  components/eamxx/scripts/scripts-tests
  components/eamxx/scripts/utils.py
Labels: scripts

#2220 test-all-scream: Explicitly set CTEST_SITE.
  components/eamxx/CTestConfig.cmake
  components/eamxx/scripts/test-all-scream
  components/eamxx/scripts/test_all_scream.py
Labels: AT: AUTOMERGE, scripts, AT: Skip v1 Testing

#2204 Add subfield attributes to output of field groups - add more control over netCDF metadata
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/data/scream_default_output.yaml
  components/eamxx/data/scream_default_remap.yaml
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/dynamics/homme/tests/dyn_grid_io.cpp
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/io/scorpio_output.hpp
  components/eamxx/src/share/io/scream_output_manager.cpp
  components/eamxx/src/share/io/scream_scorpio_interface.F90
  components/eamxx/src/share/io/scream_scorpio_interface.hpp
  components/eamxx/src/share/io/scream_scorpio_interface_iso_c2f.F90
  components/eamxx/src/share/io/tests/io_basic.cpp
  components/eamxx/src/share/io/tests/io_diags.cpp
  components/eamxx/src/share/io/tests/io_packed.cpp
  components/eamxx/src/share/io/tests/io_remap_test.cpp
  components/eamxx/src/share/io/tests/io_test_restart.yaml
  components/eamxx/src/share/io/tests/io_test_restart_check.yaml
  components/eamxx/src/share/io/tests/io_test_se_grid.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/homme_shoc_cld_p3_rrtmgp_output.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/homme_shoc_cld_spa_p3_rrtmgp_diagnostics.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/homme_shoc_cld_spa_p3_rrtmgp_output.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/homme_shoc_cld_spa_p3_rrtmgp_128levels_output.yaml
  components/eamxx/tests/coupled/dynamics_physics/model_restart/input_initial.yaml
  components/eamxx/tests/coupled/dynamics_physics/model_restart/model_output.yaml
  components/eamxx/tests/coupled/dynamics_physics/model_restart/model_restart_output.yaml
  components/eamxx/tests/coupled/physics_only/atm_proc_subcycling/output.yaml
  components/eamxx/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/shoc_cld_p3_rrtmgp_output.yaml
  components/eamxx/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/shoc_cld_spa_p3_rrtmgp_output.yaml
  components/eamxx/tests/uncoupled/homme/homme_standalone_output.yaml
  components/eamxx/tests/uncoupled/p3/p3_standalone_output.yaml
  components/eamxx/tests/uncoupled/rrtmgp/rrtmgp_standalone_output.yaml
  components/eamxx/tests/uncoupled/shoc/shoc_standalone_output.yaml
  components/eamxx/tests/uncoupled/spa/spa_standalone_output.yaml
  components/eamxx/tests/uncoupled/surface_coupling/surface_coupling_output.yaml
Labels: enhancement, B4B, I/O, AT: AUTOMERGE

#2223 Fix valgrind error in scream_scorpio_interface.F90
  components/eamxx/src/share/io/scream_scorpio_interface.F90
Labels: AT: AUTOMERGE

#2231 Fix FieldAtLevel diagnostic
  components/eamxx/src/diagnostics/field_at_level.cpp
  components/eamxx/src/diagnostics/tests/field_at_level_tests.cpp
Labels: AT: AUTOMERGE, bugfix, diagnostic

#2232 Add scream dockerfile
  cime_config/machines/cmake_macros/gnu_docker.cmake
  components/eamxx/cmake/machine-files/docker.cmake
  components/eamxx/docker/Dockerfile
  components/eamxx/docker/README.md
Labels: enhancement, cmake, B4B, AT: AUTOMERGE

#2217 Add new field to track ice cld frac for output
  components/eamxx/data/scream_default_output.yaml
  components/eamxx/src/diagnostics/CMakeLists.txt
  components/eamxx/src/diagnostics/ice_cloud_mask.cpp
  components/eamxx/src/diagnostics/ice_cloud_mask.hpp
  components/eamxx/src/diagnostics/register_diagnostics.hpp
  components/eamxx/src/diagnostics/tests/CMakeLists.txt
  components/eamxx/src/diagnostics/tests/ice_cloud_mask_tests.cpp
  components/eamxx/src/physics/cld_fraction/atmosphere_cld_fraction.cpp
  components/eamxx/src/physics/cld_fraction/atmosphere_cld_fraction.hpp
  components/eamxx/src/physics/cld_fraction/cld_fraction_functions.hpp
  components/eamxx/src/physics/cld_fraction/cld_fraction_main_impl.hpp
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/homme_shoc_cld_spa_p3_rrtmgp_diagnostics.yaml
  components/eamxx/tests/uncoupled/cld_fraction/cld_fraction_standalone.cpp
  components/eamxx/tests/uncoupled/cld_fraction/input.yaml
Labels: B4B, bugfix, Cloud Fraction

#2227 atmchange: Add support for empty lists, reset option
  components/eamxx/cime_config/buildnml
  components/eamxx/cime_config/eamxx_buildnml.py
  components/eamxx/cime_config/eamxx_buildnml_impl.py
  components/eamxx/scripts/atmchange
  components/eamxx/scripts/cime-nml-tests
Labels: AT: AUTOMERGE, scripts

#2159 Adding nudging capability for fields
  components/eamxx/src/mct_coupling/CMakeLists.txt
  components/eamxx/src/physics/CMakeLists.txt
  components/eamxx/src/physics/nudging/CMakeLists.txt
  components/eamxx/src/physics/nudging/atmosphere_nudging.cpp
  components/eamxx/src/physics/nudging/atmosphere_nudging.hpp
  components/eamxx/src/physics/nudging/nudging_functions.hpp
  components/eamxx/src/physics/nudging/tests/CMakeLists.txt
  components/eamxx/src/physics/nudging/tests/nudging_tests.cpp
  components/eamxx/src/physics/register_physics.hpp
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/CMakeLists.txt
  components/eamxx/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
Labels: enhancement, B4B, AT: AUTOMERGE

#2229 Print the name of the IC/restart/topo files from where we read fields
  components/eamxx/src/control/atmosphere_driver.cpp
Labels: enhancement, AT: AUTOMERGE

#2237 Only use np4pg2 topography files
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/model_restart/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/model_restart/input_baseline.yaml
  components/eamxx/tests/coupled/dynamics_physics/model_restart/input_initial.yaml
  components/eamxx/tests/coupled/physics_only/atm_proc_subcycling/CMakeLists.txt
  components/eamxx/tests/coupled/physics_only/atm_proc_subcycling/input.yaml
  components/eamxx/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/CMakeLists.txt
  components/eamxx/tests/coupled/physics_only/shoc_cld_p3_rrtmgp/input.yaml
  components/eamxx/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/eamxx/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/input.yaml
  components/eamxx/tests/uncoupled/homme/CMakeLists.txt
  components/eamxx/tests/uncoupled/homme/input.yaml
  components/eamxx/tests/uncoupled/shoc/CMakeLists.txt
  components/eamxx/tests/uncoupled/shoc/input.yaml
  components/eamxx/tests/uncoupled/surface_coupling/CMakeLists.txt
  components/eamxx/tests/uncoupled/surface_coupling/input.yaml
Labels: B4B, AT: AUTOMERGE, bugfix, CIME

#2239 EAMxx: fix test-all-scream report of failed tests
  components/eamxx/scripts/test_all_scream.py
Labels: testing, AT: AUTOMERGE, scripts, AT: Skip weaver, AT: Skip blake, AT: Skip v1 Testing

#2216 Allow atm processes to compute tendencies of updated fields
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/scripts/check-tendencies
  components/eamxx/scripts/check_tendencies.py
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/diagnostics/field_at_level.hpp
  components/eamxx/src/dynamics/homme/atmosphere_dynamics.hpp
  components/eamxx/src/mct_coupling/scream_cxx_f90_interface.cpp
  components/eamxx/src/physics/cld_fraction/atmosphere_cld_fraction.hpp
  components/eamxx/src/physics/p3/atmosphere_microphysics.hpp
  components/eamxx/src/physics/rrtmgp/atmosphere_radiation.hpp
  components/eamxx/src/physics/shoc/atmosphere_macrophysics.hpp
  components/eamxx/src/physics/spa/atmosphere_prescribed_aerosol.hpp
  components/eamxx/src/share/atm_process/atmosphere_process.cpp
  components/eamxx/src/share/atm_process/atmosphere_process.hpp
  components/eamxx/src/share/atm_process/atmosphere_process_group.cpp
  components/eamxx/src/share/atm_process/atmosphere_process_group.hpp
  components/eamxx/src/share/field/field.cpp
  components/eamxx/src/share/field/field.hpp
  components/eamxx/src/share/field/field_identifier.hpp
  components/eamxx/src/share/field/field_impl.hpp
  components/eamxx/src/share/field/field_utils.hpp
  components/eamxx/src/share/grid/remap/coarsening_remapper.hpp
  components/eamxx/src/share/grid/remap/vertical_remapper.hpp
  components/eamxx/src/share/io/tests/io_se_grid.cpp
  components/eamxx/src/share/property_checks/mass_and_energy_column_conservation_check.hpp
  components/eamxx/src/share/tests/column_ops.cpp
  components/eamxx/src/share/tests/field_tests.cpp
  components/eamxx/src/share/util/scream_combine_ops.hpp
  components/eamxx/src/share/util/scream_data_type.hpp
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/homme_shoc_cld_spa_p3_rrtmgp_128levels_output.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/input.yaml
  components/eamxx/tests/uncoupled/p3/CMakeLists.txt
  components/eamxx/tests/uncoupled/p3/input.yaml
  components/eamxx/tests/uncoupled/p3/p3_standalone_output.yaml
  components/eamxx/tests/uncoupled/shoc/CMakeLists.txt
  components/eamxx/tests/uncoupled/shoc/input.yaml
  components/eamxx/tests/uncoupled/shoc/shoc_standalone_output.yaml
Labels: infrastructure, I/O, Atmosphere Driver

#2248 Fix atmchange for array data with commas
  components/eamxx/scripts/atmchange
  components/eamxx/scripts/cime-nml-tests
Labels: AT: AUTOMERGE, scripts, AT: Skip weaver, AT: Skip blake, AT: Skip v1 Testing

#2238 Fix all instances of .get<Real> to be .get<double>
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/diagnostics/field_at_pressure_level.cpp
  components/eamxx/src/diagnostics/tests/field_at_pressure_level_tests.cpp
  components/eamxx/src/dynamics/homme/atmosphere_dynamics_rayleigh_friction.cpp
  components/eamxx/src/physics/rrtmgp/atmosphere_radiation.cpp
  components/eamxx/src/share/io/scorpio_output.cpp
Labels: B4B, AT: AUTOMERGE, bugfix

#2251 EAMxx: fix timestamp of FV fields for Initial run in HommeDynamics
  components/eamxx/src/dynamics/homme/atmosphere_dynamics_fv_phys.cpp
  components/eamxx/src/share/atm_process/atmosphere_process.cpp
  components/eamxx/src/share/field/field_impl.hpp
  components/eamxx/src/share/io/scorpio_output.cpp
Labels: AT: AUTOMERGE, bugfix

#2255 Fix input file path
  components/eamxx/src/physics/rrtmgp/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/input.yaml
  components/eamxx/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/eamxx/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/input.yaml
  components/eamxx/tests/uncoupled/spa/CMakeLists.txt
  components/eamxx/tests/uncoupled/spa/input.yaml
Labels: bug, B4B, AT: AUTOMERGE

#2254 ML nudging template and unit test
  components/eamxx/CMakeLists.txt
  components/eamxx/docker/Dockerfile
  components/eamxx/docker/requirements.txt
  components/eamxx/src/physics/CMakeLists.txt
  components/eamxx/src/physics/ml_nudge/CMakeLists.txt
  components/eamxx/src/physics/ml_nudge/atmosphere_ml_nudging.cpp
  components/eamxx/src/physics/ml_nudge/atmosphere_ml_nudging.hpp
  components/eamxx/tests/uncoupled/CMakeLists.txt
  components/eamxx/tests/uncoupled/ml_nudge/CMakeLists.txt
  components/eamxx/tests/uncoupled/ml_nudge/input.yaml
  components/eamxx/tests/uncoupled/ml_nudge/ml_nudge_standalone.cpp
  components/eamxx/tests/uncoupled/ml_nudge/test_nudge.py
Labels: enhancement, B4B, AT: AUTOMERGE, machine learning

#2261 add vtheta_thresh as homme parameter to eamxx namelist
  components/eamxx/cime_config/namelist_defaults_scream.xml
Labels: enhancement, B4B, AT: AUTOMERGE, AT: Skip Stand-Alone Testing

#2266 Fix utility str_to_time_stamp
  components/eamxx/src/share/io/scream_scorpio_interface.F90
  components/eamxx/src/share/tests/utils_tests.cpp
  components/eamxx/src/share/util/scream_time_stamp.cpp
Labels: AT: AUTOMERGE, bugfix

#2267 Enable ML nudge test on quartz
  components/eamxx/CMakeLists.txt
  components/eamxx/cmake/machine-files/docker.cmake
  components/eamxx/cmake/machine-files/quartz-intel.cmake
  components/eamxx/tests/uncoupled/CMakeLists.txt
  components/eamxx/tests/uncoupled/ml_nudge/CMakeLists.txt
Labels: B4B, AT: RETEST, AT: AUTOMERGE, nudging, machine learning

#2270 Add logic to write output progress to atm.log file
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/share/io/scream_output_manager.cpp
  components/eamxx/src/share/io/scream_output_manager.hpp
Labels: enhancement, B4B, I/O, AT: AUTOMERGE

#2259 Fix restart with radiation super-stepping
  cime_config/tests.py
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/rad_frequency_2/shell_commands
  components/eamxx/src/physics/rrtmgp/atmosphere_radiation.cpp
Labels: Non-B4B, radiation

#2273 Fix ml-nudge unit test on quartz
  components/eamxx/scripts/machines_specs.py
Labels: bug, B4B, AT: AUTOMERGE, AT: Skip Stand-Alone Testing, AT: Skip v1 Testing
