Repository E3SM-Project/scream, pull requests merged in 2023-02, with the labels that each got.

#2140 Add a getter to IO interface to grab the timestamp of a file.
  components/eamxx/src/share/io/scream_scorpio_interface.F90
  components/eamxx/src/share/io/scream_scorpio_interface.hpp
  components/eamxx/src/share/io/scream_scorpio_interface_iso_c2f.F90
  components/eamxx/src/share/io/tests/io.cpp
Labels: enhancement, B4B, I/O, AT: AUTOMERGE

#2150 Homme: Fix SCREAM-side discrepancies in Homme, including a bug fix.
  components/homme/src/share/namelist_mod.F90
Labels: homme, AT: AUTOMERGE, SCREAMv0

#2141 RRM glue and test
  cime_config/tests.py
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/src/dynamics/homme/CMakeLists.txt
  components/eamxx/src/dynamics/homme/homme_grids_manager.cpp
  components/eamxx/src/dynamics/homme/interface/homme_params_mod.F90
Labels: AT: AUTOMERGE, RRM-SCREAM

#2153 EAMxx: Use type annotation in mesh_file entry.
  components/eamxx/cime_config/namelist_defaults_scream.xml
Labels: testing, AT: AUTOMERGE, RRM-SCREAM

#2155 EAMxx: PE layouts for RRM nightly test.
  cime_config/allactive/config_pesall.xml
Labels: testing, AT: AUTOMERGE, AT: Integrate Without Testing, RRM-SCREAM

#2157 Upstream merge.
  cime_config/machines/config_batch.xml
  cime_config/machines/config_machines.xml
  components/homme/src/share/cxx/mpi/BoundaryExchange.hpp
  driver-mct/cime_config/config_component.xml
  driver-moab/cime_config/config_component.xml
Labels: B4B, AT: RETEST, AT: AUTOMERGE, pm-gpu

#2158 Testing: Add PE Layout for ERP CONUS RRM test for quartz.
  cime_config/allactive/config_pesall.xml
Labels: testing, B4B, AT: Skip weaver, AT: Skip blake, RRM-SCREAM

#2154 Allow using non-integer timestep inside atmosphere processes
  components/eamxx/src/control/atmosphere_surface_coupling_exporter.cpp
  components/eamxx/src/control/atmosphere_surface_coupling_exporter.hpp
  components/eamxx/src/control/atmosphere_surface_coupling_importer.cpp
  components/eamxx/src/control/atmosphere_surface_coupling_importer.hpp
  components/eamxx/src/control/tests/dummy_atm_proc.hpp
  components/eamxx/src/dynamics/homme/atmosphere_dynamics.cpp
  components/eamxx/src/dynamics/homme/atmosphere_dynamics.hpp
  components/eamxx/src/dynamics/homme/atmosphere_dynamics_rayleigh_friction.cpp
  components/eamxx/src/physics/cld_fraction/atmosphere_cld_fraction.cpp
  components/eamxx/src/physics/cld_fraction/atmosphere_cld_fraction.hpp
  components/eamxx/src/physics/p3/atmosphere_microphysics.hpp
  components/eamxx/src/physics/p3/atmosphere_microphysics_run.cpp
  components/eamxx/src/physics/rrtmgp/atmosphere_radiation.cpp
  components/eamxx/src/physics/rrtmgp/atmosphere_radiation.hpp
  components/eamxx/src/physics/shoc/atmosphere_macrophysics.cpp
  components/eamxx/src/physics/shoc/atmosphere_macrophysics.hpp
  components/eamxx/src/physics/spa/atmosphere_prescribed_aerosol.cpp
  components/eamxx/src/physics/spa/atmosphere_prescribed_aerosol.hpp
  components/eamxx/src/physics/spa/tests/spa_main_test.cpp
  components/eamxx/src/physics/zm/atmosphere_deep_convection.cpp
  components/eamxx/src/physics/zm/atmosphere_deep_convection.hpp
  components/eamxx/src/share/atm_process/atmosphere_diagnostic.cpp
  components/eamxx/src/share/atm_process/atmosphere_diagnostic.hpp
  components/eamxx/src/share/atm_process/atmosphere_process.cpp
  components/eamxx/src/share/atm_process/atmosphere_process.hpp
  components/eamxx/src/share/atm_process/atmosphere_process_group.cpp
  components/eamxx/src/share/atm_process/atmosphere_process_group.hpp
  components/eamxx/src/share/grid/remap/vertical_remapper.cpp
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/tests/atm_process_tests.cpp
  components/eamxx/src/share/util/scream_time_stamp.cpp
  components/eamxx/src/share/util/scream_time_stamp.hpp
  components/eamxx/src/share/util/scream_vertical_interpolation_impl.hpp
Labels: enhancement, infrastructure

#2170 EAMxx: Fix build error.
  components/eamxx/src/share/util/scream_vertical_interpolation_impl.hpp
Labels: AT: Integrate Without Testing

#2156 Add ne120pg2 and ne256pg2 monogrids
  cime_config/config_grids.xml
  components/elm/bld/namelist_files/namelist_defaults.xml
  components/elm/bld/namelist_files/namelist_definition.xml
  driver-mct/cime_config/namelist_definition_drv.xml
Labels: B4B, AT: AUTOMERGE

#2135 Add vertical + horizontal remapping as an option for output
  components/eamxx/src/control/atmosphere_surface_coupling_importer.cpp
  components/eamxx/src/diagnostics/exner.cpp
  components/eamxx/src/diagnostics/field_at_level.cpp
  components/eamxx/src/diagnostics/field_at_pressure_level.cpp
  components/eamxx/src/diagnostics/field_at_pressure_level.hpp
  components/eamxx/src/diagnostics/tests/field_at_pressure_level_tests.cpp
  components/eamxx/src/physics/cld_fraction/atmosphere_cld_fraction.cpp
  components/eamxx/src/physics/p3/atmosphere_microphysics.cpp
  components/eamxx/src/physics/shoc/atmosphere_macrophysics.cpp
  components/eamxx/src/share/grid/remap/abstract_remapper.cpp
  components/eamxx/src/share/grid/remap/coarsening_remapper.cpp
  components/eamxx/src/share/grid/remap/coarsening_remapper.hpp
  components/eamxx/src/share/grid/remap/vertical_remapper.cpp
  components/eamxx/src/share/grid/remap/vertical_remapper.hpp
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/io/scorpio_output.hpp
  components/eamxx/src/share/io/tests/CMakeLists.txt
  components/eamxx/src/share/io/tests/io_remap_test.cpp
  components/eamxx/src/share/tests/coarsening_remapper_tests.cpp
  components/eamxx/src/share/tests/vertical_remapper_tests.cpp
Labels: enhancement, B4B, I/O, AT: AUTOMERGE

#2177 Swap function descriptions for psl functions
  components/eamxx/src/share/util/scream_common_physics_functions.hpp
Labels: AT: AUTOMERGE, documentation, AT: Skip mappy, AT: Skip weaver, AT: Skip blake

#2176 Add default IC for ne120 with 128 vertical levels
  components/eamxx/cime_config/namelist_defaults_scream.xml
Labels: B4B, AT: AUTOMERGE

#2179 Remove duplicate spock and crusher xml tags
  cime_config/machines/config_batch.xml
Labels: B4B, AT: AUTOMERGE, AT: Skip weaver, AT: Skip blake

#2182 update-all-pip: New script for updating pip packages
  components/eamxx/scripts/update-all-pip
Labels: AT: Integrate Without Testing

#2189 create_test calls need --wait on mappy now that it's a batch machine
  components/eamxx/scripts/jenkins/jenkins_common_impl.sh
Labels: AT: AUTOMERGE, CIME, AT: Skip weaver, AT: Skip blake

#2188 Better handle accumulated fields
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/control/atmosphere_driver.hpp
  components/eamxx/src/control/atmosphere_surface_coupling_exporter.cpp
  components/eamxx/src/diagnostics/precip_ice_surf_mass_flux.cpp
  components/eamxx/src/diagnostics/precip_liq_surf_mass_flux.cpp
  components/eamxx/src/diagnostics/tests/precip_ice_surf_mass_flux_tests.cpp
  components/eamxx/src/diagnostics/tests/precip_liq_surf_mass_flux_tests.cpp
  components/eamxx/src/physics/p3/atmosphere_microphysics.cpp
  components/eamxx/src/share/field/field_tracking.cpp
  components/eamxx/src/share/field/field_tracking.hpp
  components/eamxx/tests/uncoupled/surface_coupling/surface_coupling.cpp
Labels: enhancement, AT: AUTOMERGE

#2198 EAMxx: Remove cosmetic use of rearth, anticipating its upstream removal.
  components/eamxx/src/dynamics/homme/atmosphere_dynamics.cpp
Labels: B4B, AT: AUTOMERGE, Atmosphere Driver

#2174 Save initial state, to adjust timestamp/content of files for postprocessing
  cime_config/config_archive.xml
  components/eam/src/physics/cam/shoc.F90
  components/eamxx/cime_config/buildnml
  components/eamxx/data/scream_default_output.yaml
  components/eamxx/src/share/atm_process/atmosphere_diagnostic.cpp
  components/eamxx/src/share/field/field_utils_impl.hpp
  components/eamxx/src/share/grid/remap/coarsening_remapper.cpp
  components/eamxx/src/share/grid/remap/coarsening_remapper.hpp
  components/eamxx/src/share/grid/remap/vertical_remapper.cpp
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/io/scorpio_output.hpp
  components/eamxx/src/share/io/scream_io_utils.hpp
  components/eamxx/src/share/io/scream_output_manager.cpp
  components/eamxx/src/share/io/scream_output_manager.hpp
  components/eamxx/src/share/io/scream_scorpio_interface.F90
  components/eamxx/src/share/io/scream_scorpio_interface.cpp
  components/eamxx/src/share/io/scream_scorpio_interface.hpp
  components/eamxx/src/share/io/tests/CMakeLists.txt
  components/eamxx/src/share/io/tests/io.cpp
  components/eamxx/src/share/io/tests/io_basic.cpp
  components/eamxx/src/share/io/tests/io_diags.cpp
  components/eamxx/src/share/io/tests/io_packed.cpp
  components/eamxx/src/share/io/tests/io_remap_test.cpp
  components/eamxx/src/share/io/tests/io_test_control.yaml
  components/eamxx/src/share/io/tests/io_test_multisnap.yaml
  components/eamxx/src/share/io/tests/io_test_template.yaml
  components/eamxx/src/share/tests/utils_tests.cpp
  components/eamxx/src/share/tests/vertical_remapper_tests.cpp
  components/eamxx/src/share/util/scream_setup_random_test.hpp
  components/eamxx/src/share/util/scream_time_stamp.cpp
  components/eamxx/src/share/util/scream_time_stamp.hpp
  components/eamxx/tests/uncoupled/surface_coupling/surface_coupling_output.yaml
Labels: enhancement, I/O
