Repository E3SM-Project/scream, pull requests merged in 2023-06, with the labels that each got.

#2355 Update mvapich2 version on quartz and ruby
  cime_config/machines/config_machines.xml
  components/eamxx/scripts/machines_specs.py
Labels: Machine File, AT: AUTOMERGE, AT: Skip Stand-Alone Testing, AT: Skip v1 Testing

#2358 Update PG2 standalone test IC files
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_pg2/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_pg2/input.yaml
Labels: AT: AUTOMERGE, bugfix

#2357 Bugfix to TimeInterpolation that was introduced by recent changes to IO
  components/eamxx/src/share/io/scream_scorpio_interface.F90
  components/eamxx/src/share/tests/eamxx_time_interpolation_tests.cpp
  components/eamxx/src/share/util/eamxx_time_interpolation.cpp
  components/eamxx/src/share/util/eamxx_time_interpolation.hpp
  components/eamxx/tests/uncoupled/ml_correction/ml_correction_standalone.cpp
Labels: B4B, AT: AUTOMERGE, bugfix

#2356 Bug fix in v0 P3 interface (remove gravit constant in dz calculation)
  components/eam/src/physics/p3/scream/micro_p3_interface.F90
Labels: bug, p3, AT: AUTOMERGE, bugfix, priority:high

#2351 Add geopotential height diagnostic
  components/eamxx/src/diagnostics/CMakeLists.txt
  components/eamxx/src/diagnostics/register_diagnostics.hpp
  components/eamxx/src/diagnostics/tests/CMakeLists.txt
  components/eamxx/src/diagnostics/tests/vertical_layer_midpoint_test.cpp
  components/eamxx/src/diagnostics/tests/vertical_layer_tests.cpp
  components/eamxx/src/diagnostics/tests/vertical_layer_thickness_test.cpp
  components/eamxx/src/diagnostics/vertical_layer.cpp
  components/eamxx/src/diagnostics/vertical_layer.hpp
  components/eamxx/src/diagnostics/vertical_layer_interface.cpp
  components/eamxx/src/diagnostics/vertical_layer_interface.hpp
  components/eamxx/src/diagnostics/vertical_layer_midpoint.cpp
  components/eamxx/src/diagnostics/vertical_layer_midpoint.hpp
  components/eamxx/src/diagnostics/vertical_layer_thickness.cpp
  components/eamxx/src/diagnostics/vertical_layer_thickness.hpp
  components/eamxx/src/dynamics/homme/eamxx_homme_process_interface.hpp
  components/eamxx/src/dynamics/homme/eamxx_homme_rayleigh_friction.cpp
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/homme_shoc_cld_spa_p3_rrtmgp_output.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_pg2/homme_shoc_cld_spa_p3_rrtmgp_pg2_output.yaml
  components/eamxx/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/shoc_cld_spa_p3_rrtmgp_output.yaml
Labels: enhancement, AT: AUTOMERGE

#2363 Only test np{SCREAM_TEST_MAX_RANKS} for model_restart
  components/eamxx/tests/coupled/dynamics_physics/model_restart/CMakeLists.txt
Labels: AT: AUTOMERGE, bugfix

#2364 Use parallel-netcdf on TOSS4 machines
  cime_config/machines/cmake_macros/intel_quartz.cmake
  cime_config/machines/cmake_macros/intel_ruby.cmake
  cime_config/machines/config_machines.xml
  cime_config/machines/config_pio.xml
  components/eamxx/scripts/machines_specs.py
Labels: AT: AUTOMERGE

#2348 Add capability to set surface export values via data from file(s)
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/src/control/atmosphere_driver.hpp
  components/eamxx/src/control/atmosphere_surface_coupling_exporter.cpp
  components/eamxx/src/control/atmosphere_surface_coupling_exporter.hpp
  components/eamxx/src/share/CMakeLists.txt
  components/eamxx/src/share/util/eamxx_time_interpolation.cpp
  components/eamxx/src/share/util/eamxx_time_interpolation.hpp
  components/eamxx/tests/uncoupled/surface_coupling/surface_coupling.cpp
Labels: enhancement, AT: AUTOMERGE, Surface Coupling

#2365 Remove host copy of uninitialized device memory
  components/eamxx/src/physics/rrtmgp/simple_netcdf.hpp
  components/eamxx/tests/uncoupled/rrtmgp/rrtmgp_standalone_unit.cpp
Labels: AT: AUTOMERGE

#2367 EAMxx: allow CoarseningRemapper to handle strided subfields
  components/eamxx/src/share/field/field_impl.hpp
  components/eamxx/src/share/grid/remap/coarsening_remapper.cpp
Labels: AT: AUTOMERGE, bugfix

#2369 Update nudging atm process member variables
  components/eamxx/src/physics/nudging/eamxx_nudging_process_interface.cpp
  components/eamxx/src/physics/nudging/eamxx_nudging_process_interface.hpp
Labels: AT: AUTOMERGE

#2371 Add chrysalis setup
  components/eamxx/scripts/jenkins/chrysalis_setup
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2379 Update compute-sanitizer tests
  components/eamxx/scripts/jenkins/jenkins_common_impl.sh
  components/eamxx/scripts/scripts-tests
  components/eamxx/scripts/test_all_scream.py
Labels: testing, AT: AUTOMERGE

#2383 test-all-scream: Fix nested quoting
  components/eamxx/scripts/test_all_scream.py
Labels: AT: AUTOMERGE, AT: Skip v1 Testing

#2385 Minor fixes for scripts-tests on weaver
  components/eamxx/scripts/gather_all_data.py
  components/eamxx/scripts/scripts-tests
Labels: AT: Integrate Without Testing

#2384 Add a new scream test suite specifically for AT
  cime_config/machines/config_batch.xml
  cime_config/tests.py
  components/eamxx/scripts/jenkins/jenkins_common_impl.sh
Labels: AT: AUTOMERGE, AT: Skip weaver, AT: Skip blake, AT: Skip Stand-Alone Testing

#2393 EAMxx: Use heap rather than stack allocation in set_dof_c2f.
  components/eamxx/src/share/io/scream_scorpio_interface_iso_c2f.F90
Labels: I/O, AT: AUTOMERGE

#2395 EAMxx: fix dependency calculation in atm DAG utility
  components/eamxx/src/share/atm_process/atmosphere_process_dag.cpp
  components/eamxx/src/share/atm_process/atmosphere_process_dag.hpp
Labels: AT: AUTOMERGE, Atmosphere Driver

#2400 Some minor fixes to the AtmosphereDriver
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/share/atm_process/atmosphere_process_group.cpp
  components/eamxx/src/share/atm_process/atmosphere_process_group.hpp
  components/eamxx/src/share/util/eamxx_fv_phys_rrtmgp_active_gases_workaround.cpp
Labels: B4B, AT: AUTOMERGE, Atmosphere Driver

#2402 EAMxx: Add namelist entry for Hxx's internal_diagnostics_level.
  components/eamxx/cime_config/namelist_defaults_scream.xml
Labels: infrastructure, testing, AT: AUTOMERGE

#2409 Fix surface coupling unit tests
  components/eamxx/tests/uncoupled/surface_coupling/surface_coupling.cpp
Labels: testing, AT: AUTOMERGE, bugfix, Surface Coupling

#2401 Fix initialization of accumulated fields
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/control/atmosphere_surface_coupling_exporter.cpp
  components/eamxx/src/diagnostics/CMakeLists.txt
  components/eamxx/src/diagnostics/precip_ice_surf_mass_flux.cpp
  components/eamxx/src/diagnostics/precip_ice_surf_mass_flux.hpp
  components/eamxx/src/diagnostics/precip_liq_surf_mass_flux.cpp
  components/eamxx/src/diagnostics/precip_liq_surf_mass_flux.hpp
  components/eamxx/src/diagnostics/precip_surf_mass_flux.cpp
  components/eamxx/src/diagnostics/precip_surf_mass_flux.hpp
  components/eamxx/src/diagnostics/precip_total_surf_mass_flux.cpp
  components/eamxx/src/diagnostics/precip_total_surf_mass_flux.hpp
  components/eamxx/src/diagnostics/register_diagnostics.hpp
  components/eamxx/src/diagnostics/tests/precip_ice_surf_mass_flux_tests.cpp
  components/eamxx/src/diagnostics/tests/precip_liq_surf_mass_flux_tests.cpp
  components/eamxx/src/diagnostics/tests/precip_total_surf_mass_flux_tests.cpp
  components/eamxx/src/physics/p3/eamxx_p3_process_interface.hpp
  components/eamxx/src/physics/shoc/eamxx_shoc_process_interface.cpp
  components/eamxx/src/share/atm_process/atmosphere_diagnostic.cpp
  components/eamxx/src/share/field/field_tracking.cpp
  components/eamxx/src/share/field/field_tracking.hpp
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/util/eamxx_time_interpolation.cpp
  components/eamxx/tests/coupled/dynamics_physics/model_restart/model_output.yaml
  components/eamxx/tests/coupled/dynamics_physics/model_restart/model_restart_output.yaml
Labels: B4B, AT: AUTOMERGE, Atmosphere Driver, bugfix

#2388 Add field at height diagnostic
  components/eamxx/src/diagnostics/CMakeLists.txt
  components/eamxx/src/diagnostics/field_at_height.cpp
  components/eamxx/src/diagnostics/field_at_height.hpp
  components/eamxx/src/diagnostics/field_at_level.hpp
  components/eamxx/src/diagnostics/field_at_pressure_level.cpp
  components/eamxx/src/diagnostics/field_at_pressure_level.hpp
  components/eamxx/src/diagnostics/register_diagnostics.hpp
  components/eamxx/src/diagnostics/tests/CMakeLists.txt
  components/eamxx/src/diagnostics/tests/field_at_height_tests.cpp
  components/eamxx/src/share/field/field_impl.hpp
  components/eamxx/src/share/field/field_utils_impl.hpp
Labels: AT: AUTOMERGE, diagnostic

#2407 Fix handling of mask fields in CoarseningRemapper
  components/eamxx/src/share/grid/remap/coarsening_remapper.cpp
Labels: bugfix

#2415 Prefer HINTS to PATHS when looking for tpls
  components/eamxx/cmake/tpls/CsmShare.cmake
  components/eamxx/cmake/tpls/GPTL.cmake
  components/eamxx/cmake/tpls/GetNetcdfLibs.cmake
  components/eamxx/cmake/tpls/Mct.cmake
  components/eamxx/cmake/tpls/Scorpio.cmake
Labels: cmake, B4B, AT: AUTOMERGE, bugfix
