Repository E3SM-Project/scream, pull requests merged in 2023-05, with the labels that each got.

#2316 Crusher: Re-enable ADIOS.
  cime_config/machines/cmake_macros/crayclang-scream_crusher-scream-gpu.cmake
  cime_config/machines/config_machines.xml
Labels: AT: Integrate Without Testing, crusher-gpu

#2317 Add compute sanitizer tests to weaver nightlies
  components/eamxx/scripts/jenkins/jenkins_common_impl.sh
Labels: AT: Integrate Without Testing

#2309 A few mods related to IO
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/control/atmosphere_driver.hpp
  components/eamxx/src/dynamics/homme/atmosphere_dynamics.cpp
  components/eamxx/src/dynamics/homme/homme_grids_manager.cpp
  components/eamxx/src/share/field/field.cpp
  components/eamxx/src/share/field/field.hpp
  components/eamxx/src/share/field/field_header.cpp
  components/eamxx/src/share/field/field_header.hpp
  components/eamxx/src/share/field/field_identifier.cpp
  components/eamxx/src/share/field/field_identifier.hpp
  components/eamxx/src/share/field/field_layout.cpp
  components/eamxx/src/share/field/field_manager.cpp
  components/eamxx/src/share/field/field_tag.hpp
  components/eamxx/src/share/grid/abstract_grid.hpp
  components/eamxx/src/share/io/scorpio_input.cpp
  components/eamxx/src/share/io/scorpio_input.hpp
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/io/scream_scorpio_interface.hpp
Labels: I/O, AT: AUTOMERGE

#2320 Fix cmake arg quoting
  components/eamxx/scripts/test_all_scream.py
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2321 EAMxx: State hasher to track BFBness in production simulations.
  cime_config/tests.py
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/bfbhash/shell_commands
  components/eamxx/src/dynamics/homme/atmosphere_dynamics.cpp
  components/eamxx/src/dynamics/homme/atmosphere_dynamics.hpp
  components/eamxx/src/share/CMakeLists.txt
  components/eamxx/src/share/atm_process/atmosphere_process.hpp
  components/eamxx/src/share/atm_process/atmosphere_process_hash.cpp
Labels: enhancement

#2193 fix wet-dry issues, conservation
  components/eam/src/physics/cam/shoc_intr.F90
  components/eam/src/physics/cam/wv_sat_scream.F90
  components/eam/src/physics/p3/scream/micro_p3.F90
  components/eam/src/physics/p3/scream/micro_p3_interface.F90
  components/eamxx/src/diagnostics/relative_humidity.cpp
  components/eamxx/src/diagnostics/tests/relative_humidity_tests.cpp
  components/eamxx/src/physics/p3/atmosphere_microphysics.cpp
  components/eamxx/src/physics/p3/atmosphere_microphysics.hpp
  components/eamxx/src/physics/p3/impl/p3_ice_cldliq_wet_growth_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_ice_melting_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_main_impl_part1.hpp
  components/eamxx/src/physics/p3/impl/p3_prevent_liq_supersaturation_impl.hpp
  components/eamxx/src/physics/p3/tests/p3_prevent_liq_supersaturation_tests.cpp
  components/eamxx/src/physics/share/physics_functions.hpp
  components/eamxx/src/physics/share/physics_saturation_impl.hpp
  components/eamxx/src/physics/share/tests/physics_saturation_run_and_cmp.cpp
  components/eamxx/src/physics/shoc/atmosphere_macrophysics.cpp
  components/eamxx/src/physics/shoc/atmosphere_macrophysics.hpp
  components/eamxx/src/share/util/scream_common_physics_functions.hpp
  components/eamxx/src/share/util/scream_common_physics_functions_impl.hpp
Labels: AT: Skip mappy

#2279 frontier config
  cime_config/allactive/config_pesall.xml
  cime_config/machines/Depends.frontier-gpu.crayclang.cmake
  cime_config/machines/cmake_macros/crayclang-scream.cmake
  cime_config/machines/cmake_macros/crayclang-scream_frontier-scream-gpu.cmake
  cime_config/machines/cmake_macros/crayclang-scream_frontier-scream.cmake
  cime_config/machines/cmake_macros/crayclang_frontier.cmake
  cime_config/machines/config_batch.xml
  cime_config/machines/config_machines.xml
  components/eamxx/cmake/machine-files/frontier-scream-gpu.cmake
Labels: B4B, Machine File, AT: AUTOMERGE, AT: Integrate Without Testing, AT: Skip Stand-Alone Testing, AT: Skip v1 Testing

#2329 EAMxx nightly: Increase hashing frequency to every physics time step.
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/bfbhash/shell_commands
Labels: testing, AT: Integrate Without Testing

#2331 Update weaver mach file and mach specs to adapt to new system modules
  components/eamxx/cmake/machine-files/weaver.cmake
  components/eamxx/scripts/jenkins/weaver_setup
  components/eamxx/scripts/machines_specs.py
  components/eamxx/src/physics/p3/tests/p3_main_unit_tests.cpp
Labels: Machine File, AT: WIP

#2336 EAMxx: workaround to make testing work on weaver
  components/eamxx/scripts/jenkins/weaver_setup
Labels: testing, AT: Integrate Without Testing, scripts

#2334 Upgrades to atmquery/atmchange
  components/eamxx/cime_config/eamxx_buildnml.py
  components/eamxx/scripts/atm_manip.py
  components/eamxx/scripts/atmchange
  components/eamxx/scripts/atmquery
  components/eamxx/scripts/cime-nml-tests
  components/eamxx/scripts/scripts-tests
Labels: AT: AUTOMERGE, scripts, AT: Skip Stand-Alone Testing

#2339 EAMxx: add new gpu flag to bsub on weaver
  components/eamxx/scripts/machines_specs.py
Labels: Machine File, AT: RETEST, AT: AUTOMERGE, AT: Skip mappy, AT: Skip blake, AT: Skip v1 Testing

#2342 More weaver fixes
  components/eamxx/scripts/machines_specs.py
  components/eamxx/scripts/update-all-pip
Labels: AT: AUTOMERGE, AT: Skip mappy, AT: Skip blake

#2315 Small fix to VerticalRemapper
  components/eamxx/src/share/grid/remap/vertical_remapper.cpp
Labels: I/O, AT: AUTOMERGE, bugfix

#2333 EAMxx: Add BFB hasher with internal_diagnostics_level control.
  cime_config/tests.py
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/internal_diagnostics_level/shell_commands
  components/eamxx/src/dynamics/homme/eamxx_homme_process_interface.cpp
  components/eamxx/src/share/CMakeLists.txt
  components/eamxx/src/share/atm_process/atmosphere_process.cpp
  components/eamxx/src/share/atm_process/atmosphere_process.hpp
  components/eamxx/src/share/atm_process/atmosphere_process_hash.cpp
  components/eamxx/src/share/util/scream_bfbhash.cpp
  components/eamxx/src/share/util/scream_bfbhash.hpp
  components/eamxx/tests/generic/CMakeLists.txt
  components/eamxx/tests/generic/bfbhash/CMakeLists.txt
  components/eamxx/tests/generic/bfbhash/bfbhash.cpp
  components/eamxx/tests/postrun/check_hashes_ers.py
Labels: AT: AUTOMERGE, AT: PRE-TEST INSPECTED

#2345 Fix compute sanitizer tests on weaver when submitting
  components/eamxx/scripts/test_all_scream.py
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2343 Update machine config for Ruby TOSS4
  cime_config/machines/cmake_macros/intel_ruby.cmake
  cime_config/machines/config_machines.xml
  cime_config/machines/config_pio.xml
  components/eamxx/cmake/machine-files/ruby-intel.cmake
  components/eamxx/cmake/machine-files/ruby.cmake
  components/eamxx/scripts/machines_specs.py
Labels: B4B, Machine File, AT: AUTOMERGE, AT: Integrate Without Testing

#2340 Some small simplifications to FieldManager
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/share/field/field_manager.cpp
  components/eamxx/src/share/field/field_manager.hpp
  components/eamxx/src/share/io/scorpio_input.cpp
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/io/tests/io_basic.cpp
  components/eamxx/src/share/io/tests/io_diags.cpp
  components/eamxx/src/share/io/tests/io_packed.cpp
  components/eamxx/src/share/property_checks/mass_and_energy_column_conservation_check.cpp
  components/eamxx/src/share/property_checks/mass_and_energy_column_conservation_check.hpp
Labels: infrastructure, AT: AUTOMERGE

#2322 Fix issues with GLL output for PG2 CIME cases
  components/eamxx/data/scream_default_output.yaml
  components/eamxx/src/dynamics/homme/eamxx_homme_process_interface.cpp
  components/eamxx/src/share/grid/grids_manager.hpp
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/io/scorpio_output.hpp
  components/eamxx/src/share/io/scream_output_manager.cpp
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/homme_shoc_cld_p3_rrtmgp_output.yaml
Labels: enhancement

#2349 EAMxx: Add a tolerance on #diff lines in exxhash checker.
  components/eamxx/tests/postrun/check_hashes_ers.py
Labels: AT: Integrate Without Testing

#2338 Add a time interpolation utility to EAMxx
  components/eamxx/src/share/CMakeLists.txt
  components/eamxx/src/share/io/scorpio_input.cpp
  components/eamxx/src/share/io/scorpio_input.hpp
  components/eamxx/src/share/io/scream_scorpio_interface.cpp
  components/eamxx/src/share/io/scream_scorpio_interface.hpp
  components/eamxx/src/share/tests/CMakeLists.txt
  components/eamxx/src/share/tests/eamxx_time_interpolation_tests.cpp
  components/eamxx/src/share/util/eamxx_time_interpolation.cpp
  components/eamxx/src/share/util/eamxx_time_interpolation.hpp
Labels: enhancement, B4B, AT: AUTOMERGE

#2354 [WIP] EAMxx: Add more robustness to the exxhash post-run checker.
  components/eamxx/tests/postrun/check_hashes_ers.py
Labels: testing, AT: Integrate Without Testing
