Repository E3SM-Project/scream, pull requests merged in 2023-08, with the labels that each got.

#2418 Add check_flux_state_consistency to shoc interface
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/src/physics/shoc/eamxx_shoc_process_interface.cpp
  components/eamxx/src/physics/shoc/eamxx_shoc_process_interface.hpp
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/input.yaml
Labels: enhancement

#2428 Add missing metadata to eamxx output files
  components/eamxx/CMakeLists.txt
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/control/atmosphere_driver.hpp
  components/eamxx/src/mct_coupling/atm_comp_mct.F90
  components/eamxx/src/mct_coupling/scream_cxx_f90_interface.cpp
  components/eamxx/src/mct_coupling/scream_f2c_mod.F90
  components/eamxx/src/scream_config.h.in
  components/eamxx/src/share/io/scream_output_manager.cpp
  components/eamxx/src/share/io/scream_output_manager.hpp
Labels: I/O, AT: AUTOMERGE

#2441 Default energy fixer to off
  components/eamxx/cime_config/namelist_defaults_scream.xml
Labels: AT: Integrate Without Testing

#2437 Update vertical interpolation to allow for x_src as a 1D view
  components/eamxx/src/share/tests/vertical_interp_tests.cpp
  components/eamxx/src/share/util/scream_vertical_interpolation.hpp
  components/eamxx/src/share/util/scream_vertical_interpolation_impl.hpp
Labels: enhancement, B4B, AT: AUTOMERGE

#2444 Chrysalis: Exclude chr-0512 for one test.
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/small_kernels/shell_commands
Labels: AT: Integrate Without Testing

#2445 Fixes a segfault in the finalization of F90 SCORPIO system in certain cases
  components/eamxx/src/share/io/scream_scorpio_interface.F90
Labels: code quality, AT: AUTOMERGE

#2451 Add more info at bottom of jenkins script in case of failure
  components/eamxx/scripts/jenkins/jenkins_common_impl.sh
Labels: enhancement, testing, AT: AUTOMERGE, scripts

#2456 Initialize char variable to fix valgrind error
  components/eamxx/src/physics/dp/dp_functions_f90.cpp
Labels: AT: AUTOMERGE, bugfix

#2457 DP-SCREAM (v0): Add wind nudging options
  components/eam/bld/namelist_files/namelist_definition.xml
  components/eam/src/control/iop_data_mod.F90
  components/eam/src/control/runtime_opts.F90
  components/eam/src/dynamics/se/se_iop_intr_mod.F90
Labels: B4B, AT: AUTOMERGE, DP-SCREAM

#2458 Autogenerate markdown documentation file for all the atmchange-able parameters of EAMxx
  components/eamxx/cime_config/eamxx_buildnml.py
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/scripts/eamxx-params-docs-autogen
Labels: AT: AUTOMERGE, documentation, AT: Integrate Without Testing, scripts, code usability

#2454 EAMxx: revamped some mkdocs stuff, moved into eamxx folder
  .gitignore
  components/eamxx/docs/mkdocs/docs/common/installation.md
  components/eamxx/docs/mkdocs/docs/dev/ci_nightly.md
  components/eamxx/docs/mkdocs/docs/dev/cime_testing.md
  components/eamxx/docs/mkdocs/docs/dev/field.md
  components/eamxx/docs/mkdocs/docs/dev/grid.md
  components/eamxx/docs/mkdocs/docs/dev/index.md
  components/eamxx/docs/mkdocs/docs/dev/io.md
  components/eamxx/docs/mkdocs/docs/dev/kokkos_ekat.md
  components/eamxx/docs/mkdocs/docs/dev/managers.md
  components/eamxx/docs/mkdocs/docs/dev/processes.md
  components/eamxx/docs/mkdocs/docs/dev/standalone_testing.md
  components/eamxx/docs/mkdocs/docs/dev/style_guide.md
  components/eamxx/docs/mkdocs/docs/index.md
  components/eamxx/docs/mkdocs/docs/user/index.md
  components/eamxx/docs/mkdocs/mkdocs.yml
Labels: AT: AUTOMERGE, documentation, AT: Integrate Without Testing

#2460 Get eamxx to build on lassen.
  components/eamxx/cmake/machine-files/lassen.cmake
  components/eamxx/scripts/machines_specs.py
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2462 EAMxx: revert change in xml defaults
  components/eamxx/cime_config/namelist_defaults_scream.xml
Labels: bugfix, CIME

#2461 Add some documentation on how to request model output
  components/eamxx/docs/mkdocs/docs/user/model_output.md
  components/eamxx/docs/mkdocs/mkdocs.yml
Labels: AT: AUTOMERGE, documentation, AT: Integrate Without Testing

#2448 Move extra RRTMGP temporary arrays to scratch buffer
  components/eamxx/src/physics/rrtmgp/eamxx_rrtmgp_process_interface.cpp
  components/eamxx/src/physics/rrtmgp/eamxx_rrtmgp_process_interface.hpp
Labels: radiation, AT: AUTOMERGE

#2465 Add workflow to run Mkdocs at every master updated
  .github/workflows/gh-pages.yml
Labels: AT: AUTOMERGE, documentation, AT: Integrate Without Testing

#2464 EANxx: add autogenerated eamxx params to mkdocs
  components/eamxx/docs/mkdocs/docs/common/eamxx_params.md
  components/eamxx/docs/mkdocs/docs/user/model_input.md
  components/eamxx/docs/mkdocs/mkdocs.yml
Labels: documentation, AT: Integrate Without Testing

#2463 More lassen: trying to get CIME cases to work
  cime_config/machines/cmake_macros/gnugpu_lassen.cmake
  cime_config/machines/config_batch.xml
  cime_config/machines/config_machines.xml
  components/eamxx/cmake/machine-files/lassen.cmake
  components/eamxx/scripts/machines_specs.py
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2469 buildnml: Use correct version of parse_input
  components/eamxx/cime_config/buildnml
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2472 DP: convert advance_iop_forcing
  components/eamxx/src/physics/dp/dp_functions.hpp
  components/eamxx/src/physics/dp/dp_functions_f90.cpp
  components/eamxx/src/physics/dp/dp_functions_f90.hpp
  components/eamxx/src/physics/dp/impl/dp_advance_iop_forcing_impl.hpp
  components/eamxx/src/physics/dp/tests/dp_advance_iop_forcing_tests.cpp
Labels: AT: AUTOMERGE

#2474 EAMxx: Add a few missing HOMME_ENABLE_COMPOSE symbols.
  components/eamxx/src/dynamics/homme/CMakeLists.txt
  components/eamxx/src/dynamics/homme/eamxx_homme_process_interface.cpp
  components/eamxx/src/dynamics/homme/interface/homme_driver_mod.F90
Labels: cmake

#2435 Add COSP to EAMxx
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/src/mct_coupling/CMakeLists.txt
  components/eamxx/src/physics/CMakeLists.txt
  components/eamxx/src/physics/cosp/CMakeLists.txt
  components/eamxx/src/physics/cosp/cosp_c2f.F90
  components/eamxx/src/physics/cosp/cosp_functions.hpp
  components/eamxx/src/physics/cosp/eamxx_cosp.cpp
  components/eamxx/src/physics/cosp/eamxx_cosp.hpp
  components/eamxx/src/physics/register_physics.hpp
  components/eamxx/src/physics/rrtmgp/eamxx_rrtmgp_process_interface.cpp
  components/eamxx/src/physics/rrtmgp/eamxx_rrtmgp_process_interface.hpp
  components/eamxx/src/physics/rrtmgp/scream_rrtmgp_interface.cpp
  components/eamxx/src/physics/rrtmgp/scream_rrtmgp_interface.hpp
  components/eamxx/src/physics/rrtmgp/tests/generate_baseline.cpp
  components/eamxx/src/physics/rrtmgp/tests/rrtmgp_tests.cpp
  components/eamxx/src/share/field/field_tag.hpp
  components/eamxx/tests/uncoupled/CMakeLists.txt
  components/eamxx/tests/uncoupled/cosp/CMakeLists.txt
  components/eamxx/tests/uncoupled/cosp/cosp_standalone.cpp
  components/eamxx/tests/uncoupled/cosp/cosp_standalone_output.yaml
  components/eamxx/tests/uncoupled/cosp/input.yaml
Labels: enhancement, B4B, radiation, AT: AUTOMERGE, diagnostic

#2481 Convert advance_iop_subsidence
  components/eamxx/src/physics/dp/dp_functions.hpp
  components/eamxx/src/physics/dp/dp_functions_f90.cpp
  components/eamxx/src/physics/dp/dp_functions_f90.hpp
  components/eamxx/src/physics/dp/impl/dp_advance_iop_forcing_impl.hpp
  components/eamxx/src/physics/dp/impl/dp_advance_iop_subsidence_impl.hpp
  components/eamxx/src/physics/dp/tests/dp_advance_iop_forcing_tests.cpp
  components/eamxx/src/physics/dp/tests/dp_advance_iop_subsidence_tests.cpp
Labels: AT: AUTOMERGE

#2475 Add property check ability to output column data from fields
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/control/atmosphere_driver.hpp
  components/eamxx/src/share/atm_process/atmosphere_process.hpp
  components/eamxx/src/share/atm_process/atmosphere_process_group.cpp
  components/eamxx/src/share/atm_process/atmosphere_process_group.hpp
  components/eamxx/src/share/property_checks/field_nan_check.cpp
  components/eamxx/src/share/property_checks/field_within_interval_check.cpp
  components/eamxx/src/share/property_checks/mass_and_energy_column_conservation_check.cpp
  components/eamxx/src/share/property_checks/property_check.cpp
  components/eamxx/src/share/property_checks/property_check.hpp
  components/eamxx/src/share/tests/property_checks.cpp
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/input.yaml
Labels: enhancement, AT: AUTOMERGE

#2483 Touched up build and testing documentation, fixed some links, etc
  components/eamxx/docs/common/build.md
  components/eamxx/docs/common/installation.md
  components/eamxx/docs/developer/index.md
  components/eamxx/docs/developer/source-tree.md
  components/eamxx/docs/developer/source_tree.md
  components/eamxx/docs/developer/standalone_testing.md
  components/eamxx/docs/index.md
  components/eamxx/mkdocs.yml
Labels: AT: AUTOMERGE, documentation, AT: Integrate Without Testing

#2486 rework the github actions logic with some improvements
  .github/workflows/gh-pages.yml
  components/eamxx/docs/index.md
  components/eamxx/scripts/eamxx-params-docs-autogen
Labels: AT: AUTOMERGE, documentation, AT: Integrate Without Testing

#2374 Adds an EAMXX fully coupled compset
  cime_config/allactive/config_compsets.xml
  cime_config/config_files.xml
  components/eamxx/cime_config/config_component.xml
  components/elm/cime_config/config_component.xml
  driver-mct/cime_config/config_component_e3sm.xml
Labels: B4B, AT: AUTOMERGE, SCREAMv1

#2442 Add implementaion for ML correction
  cime_config/machines/config_machines.xml
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/cmake/machine-files/mappy.cmake
  components/eamxx/cmake/machine-files/quartz-intel.cmake
  components/eamxx/scripts/machines_specs.py
  components/eamxx/src/mct_coupling/CMakeLists.txt
  components/eamxx/src/physics/ml_correction/CMakeLists.txt
  components/eamxx/src/physics/ml_correction/eamxx_ml_correction_process_interface.cpp
  components/eamxx/src/physics/ml_correction/eamxx_ml_correction_process_interface.hpp
  components/eamxx/src/physics/ml_correction/ml_correction.py
  components/eamxx/src/physics/register_physics.hpp
  components/eamxx/tests/uncoupled/ml_correction/input.yaml
  components/eamxx/tests/uncoupled/ml_correction/ml_correction_standalone.cpp
  components/eamxx/tests/uncoupled/ml_correction/test_correction.py
Labels: AT: AUTOMERGE, machine learning

#2488 Split up some long f90 lines
  components/eamxx/src/physics/dp/dp_iso_c.f90
Labels: AT: AUTOMERGE

#2489 More improvements to gh-pages docs workflow
  .github/workflows/gh-pages.yml
Labels: AT: AUTOMERGE, documentation, AT: Integrate Without Testing

#2459 Add TurbulentMountainStress AtmosphereProcess
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/control/atmosphere_driver.hpp
  components/eamxx/src/mct_coupling/CMakeLists.txt
  components/eamxx/src/physics/register_physics.hpp
  components/eamxx/src/physics/shoc/eamxx_shoc_process_interface.cpp
  components/eamxx/src/physics/shoc/eamxx_shoc_process_interface.hpp
  components/eamxx/src/physics/tms/CMakeLists.txt
  components/eamxx/src/physics/tms/eamxx_tms_process_interface.cpp
  components/eamxx/src/physics/tms/eamxx_tms_process_interface.hpp
  components/eamxx/src/share/atm_process/atmosphere_process.hpp
  components/eamxx/src/share/atm_process/atmosphere_process_group.cpp
  components/eamxx/src/share/atm_process/atmosphere_process_group.hpp
  components/eamxx/tests/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_pg2/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_pg2/input.yaml
Labels: enhancement, AT: AUTOMERGE

#2491 Allow to preview the docs pages from a PR
  .github/workflows/gh-pages.yml
  .gitignore
Labels: enhancement, AT: AUTOMERGE, documentation, AT: Integrate Without Testing

#2490 Remove member access from kernels in scorpio_output.cpp
  components/eamxx/src/share/io/scorpio_output.cpp
Labels: AT: AUTOMERGE, bugfix, valgrind / cuda-memcheck

#2480 DP: Port advance_iop_nudging
  components/eamxx/src/physics/dp/dp_constants.hpp
  components/eamxx/src/physics/dp/dp_functions.hpp
  components/eamxx/src/physics/dp/dp_functions_f90.cpp
  components/eamxx/src/physics/dp/dp_functions_f90.hpp
  components/eamxx/src/physics/dp/impl/dp_advance_iop_nudging_impl.hpp
  components/eamxx/src/physics/dp/tests/dp_advance_iop_nudging_tests.cpp
Labels: AT: AUTOMERGE, DP-SCREAM

#2494 EAMxx: better handle enabling/disabling ml_correction
  components/eamxx/CMakeLists.txt
  components/eamxx/cmake/machine-files/docker-scream.cmake
  components/eamxx/cmake/machine-files/quartz-intel.cmake
  components/eamxx/src/mct_coupling/CMakeLists.txt
  components/eamxx/src/physics/CMakeLists.txt
  components/eamxx/tests/uncoupled/CMakeLists.txt
Labels: AT: AUTOMERGE, bugfix, machine learning

#2499 Minor tweaks to gh-pages workflow
  .github/workflows/gh-pages.yml
Labels: AT: AUTOMERGE, documentation, AT: Integrate Without Testing
