Repository E3SM-Project/scream, pull requests merged in 2023-12, with the labels that each got.

#2594 Add ML surface fluxes override
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/src/physics/ml_correction/eamxx_ml_correction_process_interface.cpp
  components/eamxx/src/physics/ml_correction/eamxx_ml_correction_process_interface.hpp
  components/eamxx/src/physics/ml_correction/ml_correction.py
Labels: AT: AUTOMERGE, machine learning

#2623 EAMxx: Add missing header guard.
  components/eamxx/src/share/util/scream_bfbhash.hpp
Labels: code quality, AT: AUTOMERGE, bugfix

#2625 Update MLcorrection unit test
  components/eamxx/tests/uncoupled/ml_correction/input.yaml
Labels: AT: AUTOMERGE, machine learning

#2634 Ascent: Add -forward-unknown-to-host-compiler, which may resolve the recent nondeterminism.
  cime_config/machines/cmake_macros/gnugpu_ascent.cmake
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2581 add clean-clear-sky and clean-sky radiation calls
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/docs/technical/clean_clear_sky.md
  components/eamxx/mkdocs.yml
  components/eamxx/src/physics/rrtmgp/eamxx_rrtmgp_process_interface.cpp
  components/eamxx/src/physics/rrtmgp/eamxx_rrtmgp_process_interface.hpp
  components/eamxx/src/physics/rrtmgp/scream_rrtmgp_interface.cpp
  components/eamxx/src/physics/rrtmgp/scream_rrtmgp_interface.hpp
  components/eamxx/src/physics/rrtmgp/tests/generate_baseline.cpp
  components/eamxx/src/physics/rrtmgp/tests/rrtmgp_tests.cpp
  components/eamxx/src/physics/rrtmgp/tests/rrtmgp_unit_tests.cpp
Labels: radiation, AT: AUTOMERGE

#2613 nudging from coarse data
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/docs/user/coarse_nudging.md
  components/eamxx/mkdocs.yml
  components/eamxx/src/physics/nudging/eamxx_nudging_process_interface.cpp
  components/eamxx/src/physics/nudging/eamxx_nudging_process_interface.hpp
Labels: AT: AUTOMERGE, nudging

#2638 Change STOP_N for rad_frequency_2 cime test
  cime_config/tests.py
Labels: testing, radiation, AT: Skip Stand-Alone Testing

#2640 Add "append" attribute to namelist defaults
  components/eamxx/cime_config/buildlib_cmake
  components/eamxx/cime_config/eamxx_buildnml.py
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/scripts/cime-nml-tests
Labels: AT: AUTOMERGE, scripts, CIME, AT: Skip Stand-Alone Testing, Quality of Life

#2643 Update `ruby` machine files to work with ML corrected run
  cime_config/machines/config_machines.xml
  components/eamxx/cmake/machine-files/ruby-intel.cmake
  components/eamxx/scripts/machines_specs.py
Labels: Machine File, AT: AUTOMERGE

#2644 Allow to construct a Field from a pre-existing view
  components/eamxx/src/share/field/field.hpp
  components/eamxx/src/share/field/field_impl.hpp
  components/eamxx/src/share/tests/field_tests.cpp
Labels: infrastructure, AT: AUTOMERGE, code usability

#2642 Avoid expensive and pointless stuff in VerticalRemapper constructor
  components/eamxx/src/dynamics/homme/physics_dynamics_remapper.cpp
  components/eamxx/src/physics/nudging/eamxx_nudging_process_interface.cpp
  components/eamxx/src/share/field/field_layout.cpp
  components/eamxx/src/share/field/field_layout.hpp
  components/eamxx/src/share/field/field_manager.cpp
  components/eamxx/src/share/field/field_tag.hpp
  components/eamxx/src/share/grid/abstract_grid.cpp
  components/eamxx/src/share/grid/abstract_grid.hpp
  components/eamxx/src/share/grid/remap/abstract_remapper.cpp
  components/eamxx/src/share/grid/remap/abstract_remapper.hpp
  components/eamxx/src/share/grid/remap/do_nothing_remapper.hpp
  components/eamxx/src/share/grid/remap/horiz_interp_remapper_base.cpp
  components/eamxx/src/share/grid/remap/identity_remapper.hpp
  components/eamxx/src/share/grid/remap/vertical_remapper.cpp
  components/eamxx/src/share/grid/remap/vertical_remapper.hpp
Labels: BFB, AT: AUTOMERGE, code cleanup, performance

#2648 EAMxx: See if removing --fmad=false fixes nondeterminism in pm-gpu nightlies.
  components/eamxx/src/dynamics/homme/CMakeLists.txt
  components/eamxx/src/physics/rrtmgp/CMakeLists.txt
Labels: AT: AUTOMERGE, pm-gpu, GPU
