Repository E3SM-Project/scream, pull requests merged in 2023-11, with the labels that each got.

#2580 regional nudging using user provided nudging weights
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/src/physics/nudging/eamxx_nudging_process_interface.cpp
  components/eamxx/src/physics/nudging/eamxx_nudging_process_interface.hpp
  components/eamxx/src/physics/nudging/tests/nudging_tests.cpp
  components/eamxx/tests/coupled/physics_only/shoc_p3_nudging/CMakeLists.txt
  components/eamxx/tests/coupled/physics_only/shoc_p3_nudging/create_vert_remap.cpp
  components/eamxx/tests/coupled/physics_only/shoc_p3_nudging/create_vert_remap_and_weights.cpp
  components/eamxx/tests/coupled/physics_only/shoc_p3_nudging/input_nudging.yaml
Labels: enhancement, AT: AUTOMERGE, RRM-SCREAM, nudging

#2590 Changes needed for creating, allocating, and deepcpoying rank-0 fields
  components/eamxx/src/physics/p3/CMakeLists.txt
  components/eamxx/src/physics/p3/impl/p3_get_latent_heat_impl.hpp
  components/eamxx/src/share/field/field.cpp
  components/eamxx/src/share/field/field_alloc_prop.cpp
  components/eamxx/src/share/field/field_alloc_prop.hpp
  components/eamxx/src/share/field/field_header.cpp
  components/eamxx/src/share/field/field_identifier.cpp
  components/eamxx/src/share/field/field_identifier.hpp
  components/eamxx/src/share/field/field_impl.hpp
  components/eamxx/src/share/field/field_layout.cpp
  components/eamxx/src/share/field/field_layout.hpp
  components/eamxx/src/share/field/field_manager.cpp
  components/eamxx/src/share/field/field_utils_impl.hpp
  components/eamxx/src/share/tests/field_tests.cpp
Labels: AT: AUTOMERGE, Atmosphere Driver

#2595 MPAS-SEAICE fixes for fully coupled compset and some grid configurations
  cime_config/config_grids.xml
  components/mpas-seaice/src/shared/mpas_seaice_advection_incremental_remap.F
Labels: BFB, AT: AUTOMERGE, bugfix, e3sm-update, CIME, SCREAMv1

#2596 EAMxx: fix setting of FillValue based on fp precision
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/io/scream_output_manager.cpp
  components/eamxx/src/share/io/tests/io_basic.cpp
Labels: I/O, AT: AUTOMERGE, bugfix

#2598 Fixes scream case builds on a couple systems
  cime_config/machines/cmake_macros/gnugpu_ascent.cmake
  cime_config/machines/cmake_macros/gnugpu_pm-gpu.cmake
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2599 Disable snan init for cice
  cime_config/machines/cmake_macros/intel.cmake
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2587 DP-SCREAM: Add IOP class and unit test
  components/eamxx/src/control/CMakeLists.txt
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/control/atmosphere_driver.hpp
  components/eamxx/src/control/intensive_observation_period.cpp
  components/eamxx/src/control/intensive_observation_period.hpp
  components/eamxx/src/dynamics/homme/tests/theta-dp.nl
  components/eamxx/src/share/field/field_impl.hpp
  components/eamxx/src/share/io/scream_scorpio_interface.cpp
  components/eamxx/src/share/io/scream_scorpio_interface.hpp
  components/eamxx/tests/coupled/dynamics_physics/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_dp/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_dp/homme_shoc_cld_spa_p3_rrtmgp_dp.cpp
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_dp/homme_shoc_cld_spa_p3_rrtmgp_dp_output.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_dp/input.yaml
Labels: AT: AUTOMERGE, DP-SCREAM

#2600 Fix chrysalis cmake macro to fix DIFFs
  cime_config/machines/cmake_macros/intel_chrysalis.cmake
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2606 EAMxx: rename cxx_blah wrapper to avoid conflict with Homme
  components/eam/src/physics/cam/bfb_math.inc
  components/eam/src/physics/cam/shoc.F90
  components/eam/src/physics/cam/trb_mtn_stress.F90
  components/eam/src/physics/cam/wv_sat_scream.F90
  components/eam/src/physics/p3/eam/micro_p3.F90
  components/eam/src/physics/p3/scream/micro_p3.F90
  components/eamxx/src/physics/share/physics_share.cpp
  components/eamxx/src/physics/share/physics_share.hpp
  components/eamxx/src/physics/share/physics_share_f2c.F90
Labels: bugfix, SCREAMv0, SCREAMv1

#2605 Modifies CMAKE to send SCREAM CMAKE info to HAERO/MAM4xx
  components/eamxx/cmake/machine-files/compy.cmake
  components/eamxx/tpls/CMakeLists.txt
Labels: cmake, BFB, AT: AUTOMERGE, AT: Skip mappy, EAGLES

#2610 fix pm-gpu machine in eamxx scripts
  components/eamxx/scripts/machines_specs.py
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2588 ML correction for `u` and `v`
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/src/physics/ml_correction/eamxx_ml_correction_process_interface.cpp
  components/eamxx/src/physics/ml_correction/eamxx_ml_correction_process_interface.hpp
  components/eamxx/src/physics/ml_correction/ml_correction.py
  components/eamxx/tests/uncoupled/ml_correction/input.yaml
  components/eamxx/tests/uncoupled/ml_correction/ml_correction_standalone.cpp
  components/eamxx/tests/uncoupled/ml_correction/test_correction.py
Labels: AT: AUTOMERGE, machine learning

#2597 Revert "For NERSC CPU machines (and GCP), use the serial kokkos backe…
  components/eamxx/cmake/machine-files/alvarez.cmake
  components/eamxx/cmake/machine-files/cori-knl.cmake
  components/eamxx/cmake/machine-files/crusher-scream-gpu.cmake
  components/eamxx/cmake/machine-files/gcp.cmake
  components/eamxx/cmake/machine-files/pm-cpu.cmake
Labels: AT: STALE, AT: AUTOMERGE, AT: Integrate Without Testing

#2618 EAMxx: fix fixtures logic in shoc standalone tests
  components/eamxx/tests/uncoupled/shoc/CMakeLists.txt
Labels: cmake, AT: AUTOMERGE, bugfix
