Repository E3SM-Project/scream, pull requests merged in 2024-07, with the labels that each got.

#2882 Add scorpio reader to fill single-column fields with closest column in input file
  components/eamxx/src/physics/nudging/eamxx_nudging_process_interface.cpp
  components/eamxx/src/share/grid/mesh_free_grids_manager.cpp
  components/eamxx/src/share/grid/remap/vertical_remapper.cpp
  components/eamxx/src/share/io/CMakeLists.txt
  components/eamxx/src/share/io/scorpio_input.hpp
  components/eamxx/src/share/io/scorpio_scm_input.cpp
  components/eamxx/src/share/io/scorpio_scm_input.hpp
  components/eamxx/src/share/io/tests/CMakeLists.txt
  components/eamxx/src/share/io/tests/io_scm_reader.cpp
  components/eamxx/src/share/iop/intensive_observation_period.cpp
  components/eamxx/src/share/util/eamxx_time_interpolation.cpp
Labels: enhancement, I/O, AT: AUTOMERGE

#2810 add hacky atm "back tend" diag
  components/eamxx/src/diagnostics/CMakeLists.txt
  components/eamxx/src/diagnostics/atm_backtend.cpp
  components/eamxx/src/diagnostics/atm_backtend.hpp
  components/eamxx/src/diagnostics/register_diagnostics.hpp
  components/eamxx/src/diagnostics/tests/CMakeLists.txt
  components/eamxx/src/diagnostics/tests/atm_backtend_test.cpp
  components/eamxx/src/share/io/scorpio_output.cpp
Labels: AT: AUTOMERGE, priority:low, diagnostic

#2886 Adds description for top_lev and adds its value for 128 levs
  components/eamxx/cime_config/namelist_defaults_scream.xml
Labels: AT: AUTOMERGE, AT: Integrate Without Testing, EAGLES

#2887 Add P3 vars to FM
  components/eamxx/src/physics/p3/disp/p3_main_impl_disp.cpp
  components/eamxx/src/physics/p3/eamxx_p3_process_interface.cpp
  components/eamxx/src/physics/p3/impl/p3_main_impl.hpp
  components/eamxx/src/physics/p3/p3_functions.hpp
  components/eamxx/src/physics/p3/p3_functions_f90.cpp
Labels: BFB, p3, AT: AUTOMERGE, AT: PRE-TEST INSPECTED

#2893 Update module versions on pm-gpu
  cime_config/machines/config_machines.xml
Labels: Non-B4B, Machine File, AT: AUTOMERGE, pm-gpu

#2861 DPxx - Use consistent formulation of vtheta_dp
  components/eamxx/src/dynamics/homme/eamxx_homme_iop.cpp
Labels: AT: AUTOMERGE, DP-SCREAM

#2857 generalize table reading in p3_iso_c
  components/eamxx/src/physics/p3/p3_iso_c.f90
Labels: BFB, p3, AT: AUTOMERGE

#2904 fix a minor warning in hasher
  components/eamxx/src/share/atm_process/atmosphere_process_hash.cpp
Labels: infrastructure, AT: AUTOMERGE, diagnostic

#2899 Fix ThreadVectorRange -> TeamVectorRange in DPxx
  components/eamxx/src/dynamics/homme/eamxx_homme_iop.cpp
Labels: BFB, AT: AUTOMERGE, bugfix, DP-SCREAM

#2902 Fix bug in io with registering avg_cnt vars in Append mode.
  components/eamxx/src/share/io/scorpio_output.cpp
Labels: I/O, AT: AUTOMERGE, bugfix

#2903 DPxx: IOP pressure level fix and fix to lat/lon relative error checking
  components/eamxx/src/share/iop/intensive_observation_period.cpp
Labels: Non-B4B, AT: AUTOMERGE, bugfix, SCREAMv1, DP-SCREAM

#2912 fix capture this warning in mam micro
  components/eamxx/src/physics/mam/eamxx_mam_microphysics_process_interface.cpp
Labels: AT: AUTOMERGE, MAM

#2915 Frontier: Post-maintenance updates.
  cime_config/machines/cmake_macros/crayclang-scream_frontier-scream-gpu.cmake
  cime_config/machines/config_machines.xml
  components/eamxx/src/share/io/scream_scorpio_types.hpp
Labels: cmake, Machine File, Frontier

#2913 add output variable for rain effective diameter
  components/eam/src/physics/p3/scream/micro_p3_interface.F90
Labels: AT: AUTOMERGE, diagnostic

#2908 Add ustar and obklen to FM
  components/eamxx/src/physics/shoc/eamxx_shoc_process_interface.cpp
  components/eamxx/src/physics/shoc/eamxx_shoc_process_interface.hpp
  components/eamxx/src/physics/shoc/impl/shoc_main_impl.hpp
  components/eamxx/src/physics/shoc/shoc_functions.hpp
  components/eamxx/src/physics/shoc/shoc_functions_f90.cpp
Labels: BFB, shoc, AT: AUTOMERGE

#2917 Fix how IOP reads time
  components/eamxx/src/share/iop/intensive_observation_period.cpp
Labels: BFB, AT: AUTOMERGE, bugfix, DP-SCREAM

#2916 filter aodvis by day indices
  components/eamxx/src/diagnostics/aodvis.cpp
  components/eamxx/src/diagnostics/tests/aodvis_test.cpp
Labels: AT: AUTOMERGE, bugfix, AT: PRE-TEST INSPECTED, diagnostic

#2905 pyscream 0.0.2 (misc fixes, reorg)
  components/eamxx/src/python/CMakeLists.txt
  components/eamxx/src/python/libpyscream/CMakeLists.txt
  components/eamxx/src/python/libpyscream/pyatmproc.hpp
  components/eamxx/src/python/libpyscream/pyfield.hpp
  components/eamxx/src/python/libpyscream/pygrid.hpp
  components/eamxx/src/python/libpyscream/pyparamlist.hpp
  components/eamxx/src/python/libpyscream/pyscream_ext.cpp
  components/eamxx/src/python/libpyscream/pyscream_ext.hpp
  components/eamxx/src/python/libpyscream/pyutils.hpp
  components/eamxx/src/python/pyeamxx/__init__.py
  components/eamxx/src/python/pyproject.toml
  components/eamxx/src/python/pyscream/__init__.py
  components/eamxx/src/python/readme
  components/eamxx/tests/python/pyp3/CMakeLists.txt
  components/eamxx/tests/python/pyp3/p3_standalone_py
Labels: AT: AUTOMERGE, bugfix, python

#2923 Frontier: Additional post-maintenance updates
  cime_config/machines/cmake_macros/crayclang-scream_frontier-scream-gpu.cmake
  cime_config/machines/config_machines.xml
  components/eamxx/src/mct_coupling/atm_comp_mct.F90
  components/eamxx/src/mct_coupling/scream_cxx_f90_interface.cpp
  components/eamxx/src/mct_coupling/scream_f2c_mod.F90
  driver-mct/main/cime_comp_mod.F90
Labels: cmake, Machine File, Frontier

#2919 Add runtime and buildnml-time checks on output frequency
  components/eamxx/cime_config/eamxx_buildnml.py
  components/eamxx/src/share/io/scream_output_manager.cpp
Labels: BFB, I/O, AT: AUTOMERGE, code usability

#2926 add pyatmproc list field methods
  components/eamxx/src/python/libpyscream/pyatmproc.hpp
Labels: AT: AUTOMERGE, Quality of Life, python

#2927 fix dev/host warnings in shoc
  components/eamxx/src/physics/shoc/impl/shoc_assumed_pdf_impl.hpp
Labels: code quality, BFB, shoc, AT: AUTOMERGE, Quality of Life
