Repository E3SM-Project/scream, pull requests merged in 2024-01, with the labels that each got.

#2649 EAMxx: Specialize --fmad=false workaround to just Ascent and pm-gpu.
  components/eamxx/src/dynamics/homme/CMakeLists.txt
  components/eamxx/src/physics/rrtmgp/CMakeLists.txt
Labels: GPU

#2647 Cache the result of AbstractGrid::is_unique
  components/eamxx/src/share/grid/abstract_grid.cpp
  components/eamxx/src/share/grid/abstract_grid.hpp
Labels: infrastructure, AT: AUTOMERGE, performance

#2659 Avoid pointless work in FieldWithinIntervalCheck
  components/eamxx/src/share/atm_process/atmosphere_process.cpp
  components/eamxx/src/share/property_checks/field_within_interval_check.cpp
  components/eamxx/src/share/tests/property_checks.cpp
Labels: AT: AUTOMERGE, performance

#2631 Utility for applying random perturbation to IC
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/control/intensive_observation_period.cpp
  components/eamxx/src/share/field/field.hpp
  components/eamxx/src/share/field/field_impl.hpp
  components/eamxx/src/share/field/field_utils.hpp
  components/eamxx/src/share/field/field_utils_impl.hpp
  components/eamxx/src/share/tests/field_tests.cpp
  components/eamxx/src/share/tests/field_utils.cpp
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_dp/input.yaml
Labels: AT: AUTOMERGE, DP-SCREAM

#2660 Remove unused and buggy constructors for FieldLayout
  components/eamxx/src/control/intensive_observation_period.cpp
  components/eamxx/src/share/field/field_layout.cpp
  components/eamxx/src/share/field/field_layout.hpp
  components/eamxx/src/share/grid/remap/do_nothing_remapper.hpp
  components/eamxx/src/share/tests/field_tests.cpp
Labels: AT: AUTOMERGE, bugfix, code cleanup

#2664 Fix handling of accum fields to avoid errors with t=0 INSTANT output
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/mct_coupling/scream_cxx_f90_interface.cpp
Labels: AT: AUTOMERGE, bugfix

#2665 Fix handling of avg count in scorpio output
  components/eamxx/src/dynamics/homme/eamxx_homme_fv_phys.cpp
  components/eamxx/src/share/io/scorpio_output.cpp
Labels: I/O, AT: AUTOMERGE, bugfix

#2670 return early in layout validity check to avoid segfault(s)
  components/eamxx/src/share/grid/abstract_grid.cpp
Labels: AT: AUTOMERGE, bugfix

#2672 in scorpio interface, only access array when it is not empty
  components/eamxx/src/share/io/scream_scorpio_interface.cpp
Labels: AT: AUTOMERGE, bugfix

#2673 forbid using weighted nudging from coarse data
  components/eamxx/src/physics/nudging/eamxx_nudging_process_interface.cpp
Labels: AT: AUTOMERGE, nudging

#2668 Some fixes/upgrades to avg count logic in output classes
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/io/scorpio_output.hpp
  components/eamxx/src/share/io/tests/io_filled.cpp
Labels: enhancement, I/O, code cleanup

#2646 Refactor of SPA data structures
  cime_config/tests.py
  components/eamxx/cime_config/eamxx_buildnml.py
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/spa_remap/shell_commands
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/physics/spa/eamxx_spa_process_interface.cpp
  components/eamxx/src/physics/spa/eamxx_spa_process_interface.hpp
  components/eamxx/src/physics/spa/spa_functions.hpp
  components/eamxx/src/physics/spa/spa_functions_impl.hpp
  components/eamxx/src/physics/spa/tests/spa_main_test.cpp
  components/eamxx/src/physics/spa/tests/spa_one_to_one_remap_test.cpp
  components/eamxx/src/physics/spa/tests/spa_read_data_from_file_test.cpp
  components/eamxx/src/share/CMakeLists.txt
  components/eamxx/src/share/grid/remap/abstract_remapper.cpp
  components/eamxx/src/share/grid/remap/abstract_remapper.hpp
  components/eamxx/src/share/grid/remap/coarsening_remapper.cpp
  components/eamxx/src/share/grid/remap/coarsening_remapper.hpp
  components/eamxx/src/share/grid/remap/horiz_interp_remapper_base.cpp
  components/eamxx/src/share/grid/remap/horizontal_remap_utility.cpp
  components/eamxx/src/share/grid/remap/horizontal_remap_utility.hpp
  components/eamxx/src/share/grid/remap/identity_remapper.hpp
  components/eamxx/src/share/io/scorpio_input.cpp
  components/eamxx/src/share/io/scorpio_input.hpp
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/tests/CMakeLists.txt
  components/eamxx/src/share/tests/horizontal_remap_test.cpp
  components/eamxx/tests/coupled/dynamics_physics/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp_dp/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp_dp/homme_shoc_cld_p3_rrtmgp_dp.cpp
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp_dp/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp_dp/output.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp_pg2/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp_pg2/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp_pg2/output.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/input.yaml
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/input.yaml
  components/eamxx/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/eamxx/tests/coupled/physics_only/shoc_cld_spa_p3_rrtmgp/input.yaml
  components/eamxx/tests/uncoupled/spa/input.yaml
Labels: performance, SPA

#2655 expose p3 parameters
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/src/physics/p3/disp/p3_ice_sed_impl_disp.cpp
  components/eamxx/src/physics/p3/disp/p3_main_impl_disp.cpp
  components/eamxx/src/physics/p3/disp/p3_main_impl_part1_disp.cpp
  components/eamxx/src/physics/p3/disp/p3_main_impl_part2_disp.cpp
  components/eamxx/src/physics/p3/disp/p3_main_impl_part3_disp.cpp
  components/eamxx/src/physics/p3/disp/p3_rain_sed_impl_disp.cpp
  components/eamxx/src/physics/p3/eamxx_p3_process_interface.cpp
  components/eamxx/src/physics/p3/eamxx_p3_process_interface.hpp
  components/eamxx/src/physics/p3/eamxx_p3_run.cpp
  components/eamxx/src/physics/p3/impl/p3_autoconversion_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_cldliq_imm_freezing_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_cloud_rain_acc_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_dsd2_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_ice_collection_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_ice_nucleation_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_ice_sed_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_main_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_main_impl_part1.hpp
  components/eamxx/src/physics/p3/impl/p3_main_impl_part2.hpp
  components/eamxx/src/physics/p3/impl/p3_main_impl_part3.hpp
  components/eamxx/src/physics/p3/impl/p3_rain_imm_freezing_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_rain_sed_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_rain_self_collection_impl.hpp
  components/eamxx/src/physics/p3/p3_functions.hpp
  components/eamxx/src/physics/p3/p3_functions_f90.cpp
  components/eamxx/src/physics/p3/tests/p3_autoconversion_unit_tests.cpp
  components/eamxx/src/physics/p3/tests/p3_cldliq_imm_freezing_unit_tests.cpp
  components/eamxx/src/physics/p3/tests/p3_cloud_rain_acc_unit_tests.cpp
  components/eamxx/src/physics/p3/tests/p3_dsd2_unit_tests.cpp
  components/eamxx/src/physics/p3/tests/p3_ice_collection_unit_tests.cpp
  components/eamxx/src/physics/p3/tests/p3_ice_nucleation_unit_tests.cpp
  components/eamxx/src/physics/p3/tests/p3_ice_sed_unit_tests.cpp
  components/eamxx/src/physics/p3/tests/p3_rain_imm_freezing_unit_tests.cpp
  components/eamxx/src/physics/p3/tests/p3_rain_sed_unit_tests.cpp
  components/eamxx/src/physics/p3/tests/p3_rain_self_collection_tests.cpp
  components/eamxx/src/physics/share/physics_constants.hpp
  components/eamxx/src/physics/share/tests/physics_saturation_run_and_cmp.cpp
Labels: enhancement, Non-B4B, p3, namelist

#2681 EAMxx: fix typo in spa_remap testmod
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/spa_remap/shell_commands
Labels: testing, AT: AUTOMERGE, AT: Integrate Without Testing

#2682 add inputdata unit test
  .github/workflows/eamxx_default_files.yml
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/cime_config/tests/eamxx_default_files.py
Labels: enhancement, testing, AT: AUTOMERGE, AT: Integrate Without Testing, input file, Quality of Life, notify-file-gh-action

#2658 DP-SCREAM v0 diagnostic coordinate fix
  components/eam/src/dynamics/se/stepon.F90
Labels: BFB, AT: AUTOMERGE, bugfix, SCREAMv0, DP-SCREAM
