Repository E3SM-Project/scream, pull requests merged in 2024-08, with the labels that each got.

#2934 Update Livermore Computing machine config files
  cime_config/machines/cmake_macros/intel_dane.cmake
  cime_config/machines/config_machines.xml
Labels: BFB, Machine File, AT: AUTOMERGE, AT: Integrate Without Testing, AT: PRE-TEST INSPECTED

#2935 Frontier: use cpe/22.12 in the post-maintenance configuration
  cime_config/machines/config_machines.xml
Labels: Machine File, AT: AUTOMERGE, AT: Integrate Without Testing, Frontier

#2933 Remove multiprocess tests for compute sanitizer
  components/eamxx/tests/CMakeLists.txt
Labels: AT: AUTOMERGE

#2930 DPxx compset modifications + add RCE case + more expansive testing
  cime_config/tests.py
  components/eamxx/cime_config/config_component.xml
  components/eamxx/cime_config/config_compsets.xml
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/dpxx/arm97/shell_commands
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/dpxx/comble/shell_commands
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/dpxx/dycomsrf01/shell_commands
  components/eamxx/cime_config/usermods_dirs/rcemip/user_nl_cpl
Labels: testing, BFB, SCREAMv1, DP-SCREAM

#2940 Update DPxx tests to run with PG2 grid
  cime_config/tests.py
  components/eamxx/cime_config/config_compsets.xml
Labels: AT: AUTOMERGE, DP-SCREAM

#2932 Port shoc_assumed_pdf functions individually (like in shoc.F90)
  components/eamxx/src/physics/shoc/impl/shoc_assumed_pdf_compute_buoyancy_flux_impl.hpp
  components/eamxx/src/physics/shoc/impl/shoc_assumed_pdf_compute_cloud_liquid_variance_impl.hpp
  components/eamxx/src/physics/shoc/impl/shoc_assumed_pdf_compute_liquid_water_flux_impl.hpp
  components/eamxx/src/physics/shoc/impl/shoc_assumed_pdf_compute_qs_impl.hpp
  components/eamxx/src/physics/shoc/impl/shoc_assumed_pdf_compute_s_impl.hpp
  components/eamxx/src/physics/shoc/impl/shoc_assumed_pdf_compute_sgs_liquid_impl.hpp
  components/eamxx/src/physics/shoc/impl/shoc_assumed_pdf_compute_temperature_impl.hpp
  components/eamxx/src/physics/shoc/impl/shoc_assumed_pdf_impl.hpp
  components/eamxx/src/physics/shoc/impl/shoc_assumed_pdf_inplume_correlations_impl.hpp
  components/eamxx/src/physics/shoc/impl/shoc_assumed_pdf_qw_parameters_impl.hpp
  components/eamxx/src/physics/shoc/impl/shoc_assumed_pdf_thl_parameters_impl.hpp
  components/eamxx/src/physics/shoc/impl/shoc_assumed_pdf_tilde_to_real_impl.hpp
  components/eamxx/src/physics/shoc/impl/shoc_assumed_pdf_vv_parameters_impl.hpp
  components/eamxx/src/physics/shoc/shoc_functions.hpp
Labels: BFB, shoc, AT: AUTOMERGE

#2929 Fix a couple of issues in history restart
  components/eamxx/src/share/io/scream_output_manager.cpp
  components/eamxx/src/share/io/scream_scorpio_interface.cpp
  components/eamxx/src/share/io/scream_scorpio_interface.hpp
Labels: BFB, I/O, AT: AUTOMERGE, bugfix

#2920 Add support for ne512pg2 bi-grid
  cime_config/config_grids.xml
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/elm/bld/namelist_files/namelist_defaults.xml
  components/elm/bld/namelist_files/namelist_definition.xml
  driver-mct/cime_config/namelist_definition_drv.xml
Labels: AT: AUTOMERGE

#2943 Frontier: disable hipInit before MPI_Init
  cime_config/machines/cmake_macros/crayclang-scream_frontier-scream-gpu.cmake
Labels: cmake, AT: AUTOMERGE, AT: Integrate Without Testing, Frontier

#2950 move pyscream to nb
  components/eamxx/CMakeLists.txt
  components/eamxx/src/CMakeLists.txt
  components/eamxx/src/python/libpyscream/CMakeLists.txt
  components/eamxx/src/python/libpyscream/pyatmproc.hpp
  components/eamxx/src/python/libpyscream/pyfield.hpp
  components/eamxx/src/python/libpyscream/pygrid.hpp
  components/eamxx/src/python/libpyscream/pyparamlist.hpp
  components/eamxx/src/python/libpyscream/pyscream_ext.cpp
  components/eamxx/src/python/libpyscream/pyutils.hpp
  components/eamxx/tests/CMakeLists.txt
Labels: AT: AUTOMERGE, python

#2952 disable gh testing for now
  .github/workflows/e3sm-gh-ci-cime-tests.yml
  .github/workflows/e3sm-gh-ci-w-cime-tests.yml
  .github/workflows/eamxx_default_files.yml
Labels: AT: Integrate Without Testing

#2954 fix errors and warning in rrtmgp-k
  components/eamxx/src/physics/rrtmgp/eamxx_rrtmgp_process_interface.cpp
  components/eamxx/src/physics/rrtmgp/rrtmgp_utils.hpp
  components/eamxx/src/physics/rrtmgp/scream_rrtmgp_interface.hpp
Labels: radiation, AT: AUTOMERGE, CUDA, pm-gpu

#2955 Limit compute-sanitizer racecheck resources
  components/eamxx/scripts/test_all_scream.py
  components/eamxx/scripts/test_factory.py
Labels: testing, AT: AUTOMERGE, bugfix

#2956 Use C++ in shoc property tests
  components/eamxx/src/physics/shoc/tests/shoc_assumed_pdf_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_brunt_length_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_check_length_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_check_tke_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_clip_third_moms_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_compute_diag_third_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_compute_shoc_temperature_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_compute_shoc_vapor_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_diag_obklen_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_diag_second_mom_srf_test.cpp
  components/eamxx/src/physics/shoc/tests/shoc_diag_second_mom_ubycond_test.cpp
  components/eamxx/src/physics/shoc/tests/shoc_diag_second_moments_lbycond_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_diag_second_moments_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_diag_second_shoc_moments_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_diag_third_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_eddy_diffusivities_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_energy_fixer_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_energy_integral_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_energy_update_dse_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_grid_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_impli_comp_tmpi_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_impli_dp_inverse_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_l_inf_length_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_length_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_linear_interp_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_main_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_mix_length_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_pblintd_check_pblh_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_pblintd_cldcheck_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_pblintd_height_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_pblintd_init_pot_test.cpp
  components/eamxx/src/physics/shoc/tests/shoc_pblintd_surf_temp_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_pblintd_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_tke_adv_sgs_tke_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_tke_column_stab_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_tke_isotropic_ts_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_tke_shr_prod_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_tke_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_update_prognostics_implicit_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_varorcovar_tests.cpp
  components/eamxx/src/physics/shoc/tests/shoc_vertflux_tests.cpp
Labels: BFB, shoc, AT: AUTOMERGE

#2957 Fix hist regex for scream
  cime_config/config_archive.xml
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/output/diags/shell_commands
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/output/phys/shell_commands
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/output/phys_dyn/shell_commands
Labels: AT: AUTOMERGE

#2971 Add libfabric/1.15.2.0 module to frontier-scream-gpu.
  cime_config/machines/config_machines.xml
Labels: AT: AUTOMERGE

#2972 Pm-cpu: do static libc++ linking
  cime_config/machines/cmake_macros/gnu_pm-cpu.cmake
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2977 EAMxx: use portable format for unsigned std::int64_t in printf
  components/eamxx/src/share/atm_process/atmosphere_process_hash.cpp
Labels: code quality, BFB, AT: AUTOMERGE
