Repository E3SM-Project/scream, pull requests merged in 2024-09, with the labels that each got.

#2978 EAMxx: Fix PRIx64 usage to include width 16.
  components/eamxx/src/share/atm_process/atmosphere_process_hash.cpp
Labels: AT: AUTOMERGE

#2965 options to build sk p3 and shoc separately
  cime_config/tests.py
  components/eamxx/CMakeLists.txt
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/small_kernels_p3/shell_commands
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/small_kernels_shoc/shell_commands
  components/eamxx/src/physics/p3/CMakeLists.txt
  components/eamxx/src/physics/p3/impl/p3_main_impl.hpp
  components/eamxx/src/physics/p3/p3_functions.hpp
  components/eamxx/src/physics/p3/tests/CMakeLists.txt
  components/eamxx/src/physics/shoc/CMakeLists.txt
  components/eamxx/src/physics/shoc/eamxx_shoc_process_interface.cpp
  components/eamxx/src/physics/shoc/eamxx_shoc_process_interface.hpp
  components/eamxx/src/physics/shoc/impl/shoc_main_impl.hpp
  components/eamxx/src/physics/shoc/shoc_functions.hpp
  components/eamxx/src/physics/shoc/shoc_functions_f90.cpp
  components/eamxx/src/physics/shoc/tests/CMakeLists.txt
  components/eamxx/src/scream_config.h.in
Labels: cmake, BFB, p3, shoc, AT: AUTOMERGE

#2983 Fix frontier builds
  components/eamxx/src/physics/mam/srf_emission_impl.hpp
Labels: AT: AUTOMERGE

#2975 SHOC related diagnostic output
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/src/physics/shoc/eamxx_shoc_process_interface.cpp
Labels: BFB, shoc

#2982 Homme: Fix planar-mode pgN get_latlon routines.
  components/homme/src/share/cxx/utilities/InternalDiagnostics.cpp
  components/homme/src/share/gllfvremap_mod.F90
Labels: DP-SCREAM

#2988 DPxx: Remove unused use_moisture line.
  components/eamxx/src/dynamics/homme/eamxx_homme_iop.cpp
Labels: AT: AUTOMERGE

#2980 View alloc fixes for P3
  components/eamxx/src/physics/p3/CMakeLists.txt
  components/eamxx/src/physics/p3/disp/p3_ice_sed_impl_disp.cpp
  components/eamxx/src/physics/p3/disp/p3_main_impl_disp.cpp
  components/eamxx/src/physics/p3/disp/p3_main_impl_part1_disp.cpp
  components/eamxx/src/physics/p3/disp/p3_main_impl_part2_disp.cpp
  components/eamxx/src/physics/p3/disp/p3_main_impl_part3_disp.cpp
  components/eamxx/src/physics/p3/eamxx_p3_process_interface.cpp
  components/eamxx/src/physics/p3/eamxx_p3_process_interface.hpp
  components/eamxx/src/physics/p3/eamxx_p3_run.cpp
  components/eamxx/src/physics/p3/eti/p3_get_latent_heat.cpp
  components/eamxx/src/physics/p3/impl/p3_evaporate_rain_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_get_latent_heat_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_get_time_space_phys_variables_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_ice_cldliq_wet_growth_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_ice_melting_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_ice_sed_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_ice_supersat_conservation_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_main_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_main_impl_part1.hpp
  components/eamxx/src/physics/p3/impl/p3_main_impl_part2.hpp
  components/eamxx/src/physics/p3/impl/p3_main_impl_part3.hpp
  components/eamxx/src/physics/p3/impl/p3_prevent_liq_supersaturation_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_update_prognostics_impl.hpp
  components/eamxx/src/physics/p3/p3_functions.hpp
  components/eamxx/src/physics/p3/p3_functions_f90.cpp
  components/eamxx/src/physics/p3/p3_functions_f90.hpp
  components/eamxx/src/physics/p3/tests/CMakeLists.txt
  components/eamxx/src/physics/p3/tests/p3_evaporate_rain_unit_tests.cpp
  components/eamxx/src/physics/p3/tests/p3_get_latent_heat_unit_tests.cpp
  components/eamxx/src/physics/p3/tests/p3_ice_cldliq_wet_growth_unit_tests.cpp
  components/eamxx/src/physics/p3/tests/p3_ice_melting_unit_tests.cpp
  components/eamxx/src/physics/p3/tests/p3_ice_sed_unit_tests.cpp
  components/eamxx/src/physics/p3/tests/p3_ice_supersat_conservation_tests.cpp
  components/eamxx/src/physics/p3/tests/p3_main_unit_tests.cpp
  components/eamxx/src/physics/p3/tests/p3_prevent_liq_supersaturation_tests.cpp
  components/eamxx/src/physics/p3/tests/p3_unit_tests.cpp
Labels: p3, AT: AUTOMERGE

#2991 EAMxx: Improve rrtmgp frequency err msg in buildnml.py
  components/eamxx/cime_config/eamxx_buildnml.py
Labels: code quality, radiation, AT: AUTOMERGE, namelist, Quality of Life

#2993 Make rrtmgp explicitly find kokkos
  components/eamxx/src/physics/rrtmgp/CMakeLists.txt
Labels: cmake, radiation, AT: AUTOMERGE, bugfix

#2995 Sync lat/lon to host in rrtmgp interface for IOP
  components/eamxx/src/physics/rrtmgp/eamxx_rrtmgp_process_interface.cpp
Labels: radiation, bugfix, DP-SCREAM

#3003 Add machine files to use with SNL-hosted containers
  components/eamxx/cmake/machine-files/ghci-snl-openmp.cmake
  components/eamxx/cmake/machine-files/ghci-snl.cmake
  components/eamxx/scripts/machines_specs.py
Labels: BFB, Machine File, AT: AUTOMERGE, AT: Integrate Without Testing

#3002 Add checks on permissions for input files at buildnml time
  components/eamxx/cime_config/eamxx_buildnml.py
Labels: AT: AUTOMERGE, CIME, AT: Skip Stand-Alone Testing, code usability

#3008 Fix ghci-snl-openmp mach file
  components/eamxx/cmake/machine-files/ghci-snl-openmp.cmake
Labels: testing, cmake, bugfix

#2999 MAM4xx: Fix of mam4_constituent_fluxes_standalone_np1
  components/eamxx/src/physics/mam/eamxx_mam_constituent_fluxes_interface.cpp
Labels: AT: AUTOMERGE, bugfix, AT: PRE-TEST INSPECTED, EAGLES, MAM

#2984 Call MPI_Abort in CIME runs when an exception is thrown inside EAMxx
  components/eamxx/src/mct_coupling/scream_cxx_f90_interface.cpp
Labels: AT: AUTOMERGE, AT: Skip weaver, AT: Skip v1 Testing, code usability, MPI

#2997 Bug fix when defining gsize in DP mode
  share/streams/shr_dmodel_mod.F90
Labels: AT: AUTOMERGE, bugfix, SCREAMv0, SCREAMv1, DP-SCREAM

#3012 Explicitly source the sems modules init script on mappy
  components/eamxx/scripts/machines_specs.py
Labels: testing, AT: AUTOMERGE, AT: Skip weaver, AT: Skip v1 Testing

#3015 Revert Kokkos rrtmgp
  components/eamxx/CMakeLists.txt
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#3014 Change handling of multiple matches in atmchange/atmquery
  components/eamxx/cime_config/eamxx_buildnml.py
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/internal_diagnostics_level/shell_commands
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/small_kernels/shell_commands
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/small_kernels_p3/shell_commands
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/small_kernels_shoc/shell_commands
  components/eamxx/docs/user/model_input.md
  components/eamxx/scripts/atm_manip.py
  components/eamxx/scripts/atmchange
  components/eamxx/scripts/atmquery
  components/eamxx/scripts/cime-nml-tests
Labels: enhancement, AT: AUTOMERGE, scripts

#3016 remove DPxx dt_remap_factor setting
  components/eamxx/cime_config/namelist_defaults_scream.xml
Labels: Non-B4B, AT: AUTOMERGE, DP-SCREAM
