Repository E3SM-Project/scream, pull requests merged in 2024-03, with the labels that each got.

#2730 Add F20TR-SCREAMv1 compset
  cime_config/config_grids.xml
  components/eamxx/cime_config/config_compsets.xml
  components/elm/bld/namelist_files/namelist_defaults.xml
  components/elm/bld/namelist_files/use_cases/20thC_CMIP6_transient.xml
  components/elm/bld/namelist_files/use_cases/20thC_transient.xml
Labels: AT: AUTOMERGE

#2734 Update machine config for Livermore Computing machines
  cime_config/machines/config_machines.xml
  components/eamxx/cmake/machine-files/lassen.cmake
  components/eamxx/cmake/machine-files/quartz-intel.cmake
  components/eamxx/cmake/machine-files/quartz.cmake
  components/eamxx/cmake/machine-files/ruby-intel.cmake
  components/eamxx/cmake/machine-files/ruby.cmake
  components/eamxx/cmake/machine-files/syrah.cmake
  components/eamxx/data/scream_default_remap.yaml
  components/eamxx/scripts/machines_specs.py
Labels: BFB, Machine File, AT: AUTOMERGE, AT: Skip Stand-Alone Testing, AT: Skip v1 Testing

#2735 set_string for some radiation diagnostics
  components/eamxx/src/diagnostics/longwave_cloud_forcing.cpp
  components/eamxx/src/diagnostics/shortwave_cloud_forcing.cpp
  components/eamxx/src/diagnostics/surf_upward_latent_heat_flux.cpp
Labels: radiation, AT: AUTOMERGE, diagnostic

#2741 check-hashes-ers: Bring in to eamxx/scripts ecosystem
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/internal_diagnostics_level/shell_commands
  components/eamxx/scripts/check-hashes-ers
  components/eamxx/tests/postrun/check_hashes_ers.py
Labels: AT: Integrate Without Testing

#2742 Make nudging log which file it's reading
  components/eamxx/src/physics/nudging/eamxx_nudging_process_interface.cpp
  components/eamxx/src/share/io/scorpio_input.cpp
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/util/eamxx_time_interpolation.cpp
  components/eamxx/src/share/util/eamxx_time_interpolation.hpp
Labels: enhancement, I/O, AT: AUTOMERGE, nudging

#2743 In buildnml, add map files needed for output to inputdata list
  components/eamxx/cime_config/buildnml
  components/eamxx/cime_config/eamxx_buildnml.py
Labels: AT: AUTOMERGE, scripts, CIME, AT: Skip v1 Testing

#2737 Fix handling of cloud fraction for COSP
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/src/physics/cosp/cosp_c2f.F90
  components/eamxx/src/physics/cosp/eamxx_cosp.cpp
  components/eamxx/src/physics/rrtmgp/eamxx_rrtmgp_process_interface.cpp
  components/eamxx/tests/uncoupled/cosp/input.yaml
Labels: AT: AUTOMERGE

#2746 Change Implementation of get_vector_dim() in FieldLayout
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/share/field/field.cpp
  components/eamxx/src/share/field/field_layout.cpp
  components/eamxx/src/share/field/field_layout.hpp
  components/eamxx/src/share/grid/abstract_grid.cpp
  components/eamxx/src/share/tests/field_tests.cpp
Labels: AT: AUTOMERGE

#2744 Fix how we read/write timestamp to file
  components/eamxx/src/share/io/scream_io_control.hpp
  components/eamxx/src/share/io/scream_output_manager.cpp
  components/eamxx/src/share/io/scream_scorpio_interface.cpp
  components/eamxx/src/share/io/scream_scorpio_interface.hpp
  components/eamxx/src/share/io/tests/io_utils.cpp
  components/eamxx/src/share/util/scream_time_stamp.hpp
Labels: I/O, AT: AUTOMERGE, bugfix

#2745 test-all-scream: Move baseline build dir
  components/eamxx/scripts/test_all_scream.py
Labels: AT: AUTOMERGE, scripts, AT: Skip v1 Testing

#2748 In time interp util, set logger in new reader when we shift file
  components/eamxx/src/share/util/eamxx_time_interpolation.cpp
Labels: AT: AUTOMERGE, bugfix

#2739 Changes for running through CIME
  cime_config/tests.py
  components/eamxx/cime_config/config_compsets.xml
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/control/atmosphere_driver.hpp
  components/eamxx/src/control/intensive_observation_period.cpp
  components/eamxx/src/control/intensive_observation_period.hpp
  components/eamxx/src/dynamics/homme/eamxx_homme_iop.cpp
  components/eamxx/src/dynamics/homme/eamxx_homme_process_interface.cpp
  components/eamxx/src/physics/spa/eamxx_spa_process_interface.cpp
  components/eamxx/src/share/atm_process/atmosphere_process.hpp
  components/eamxx/src/share/atm_process/atmosphere_process_group.hpp
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_dp/input.yaml
Labels: AT: AUTOMERGE, DP-SCREAM

#2749 Fix bug in IO when doing a restarted run without restarting history
  components/eamxx/src/share/io/scream_output_manager.cpp
  components/eamxx/src/share/util/scream_time_stamp.hpp
Labels: I/O, AT: AUTOMERGE, bugfix

#2752 check-hashes-ers: Minor change so works with multi-case tests like PEM
  components/eamxx/scripts/check-hashes-ers
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2740 Delete cmake files for 2 machines we don't support on LC.
  components/eamxx/cmake/machine-files/lassen.cmake
  components/eamxx/cmake/machine-files/syrah.cmake
Labels: BFB, Machine File, AT: STALE, AT: AUTOMERGE, AT: Skip Stand-Alone Testing, AT: Skip v1 Testing

#2757 test-all-scream: Get working on pm-gpu nightly
  components/eamxx/scripts/jenkins/jenkins_common_impl.sh
  components/eamxx/scripts/machines_specs.py
  components/eamxx/scripts/test_all_scream.py
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2727 Add a script to generate/edit output stream yaml files
  cime_config/tests.py
  components/eamxx/cime_config/eamxx_buildnml.py
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/output/README
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/output/diags/shell_commands
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/output/hremap_to_ne4/shell_commands
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/output/phys/shell_commands
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/output/phys_dyn/shell_commands
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/output/preset/1/shell_commands
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/output/preset/2/shell_commands
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/output/preset/3/shell_commands
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/output/preset/4/shell_commands
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/output/preset/5/shell_commands
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/output/preset/6/shell_commands
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/output/set_avg/shell_commands
  components/eamxx/cime_config/testdefs/testmods_dirs/scream/output/vremap/shell_commands
  components/eamxx/data/SCREAM_YAML_README
  components/eamxx/data/scream_default_output.yaml
  components/eamxx/data/scream_default_remap.yaml
  components/eamxx/scripts/atm_manip.py
  components/eamxx/scripts/edit-output-stream
  components/eamxx/scripts/edit_output_stream.py
  components/eamxx/src/share/io/scream_output_manager.cpp
Labels: AT: AUTOMERGE, scripts, Quality of Life

#2751 Use ctest to generate baselines
  components/eamxx/CMakeLists.txt
  components/eamxx/scripts/test-all-scream
  components/eamxx/scripts/test_all_scream.py
  components/eamxx/scripts/test_factory.py
  components/eamxx/src/physics/p3/tests/CMakeLists.txt
  components/eamxx/src/physics/rrtmgp/tests/CMakeLists.txt
  components/eamxx/src/physics/share/tests/CMakeLists.txt
  components/eamxx/src/physics/shoc/tests/CMakeLists.txt
  components/eamxx/tests/uncoupled/rrtmgp/CMakeLists.txt
Labels: testing, cmake, BFB, AT: AUTOMERGE, scripts

#2756 Do not run AT on dependabot PRs
  .github/dependabot.yml
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2758 Run e3sm gh action only if repo name is e3sm
  .github/workflows/e3sm-gh-ci-cime-tests.yml
  .github/workflows/e3sm-gh-pages.yml
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2753 Some changes to test-all-scream and scripts-tests
  components/eamxx/CMakeLists.txt
  components/eamxx/scripts/cime-nml-tests
  components/eamxx/scripts/git_utils.py
  components/eamxx/scripts/scripts-tests
  components/eamxx/scripts/test-all-scream
  components/eamxx/scripts/test_all_scream.py
  components/eamxx/tests/meta-tests/CMakeLists.txt
  components/eamxx/tests/meta-tests/build_fail.cpp
  components/eamxx/tests/meta-tests/resource_spread.cpp
  components/eamxx/tests/meta-tests/test_fail.cpp
  components/eamxx/tests/meta-tests/test_level_check/CMakeLists.txt
  components/eamxx/tests/meta-tests/test_level_check/at_unit.cpp
  components/eamxx/tests/meta-tests/test_level_check/experimental_unit.cpp
  components/eamxx/tests/meta-tests/test_level_check/nightly_unit.cpp
Labels: testing, scripts

#2750 Add baseline tests for EAMxx standalone ad tests
  components/eamxx/CMakeLists.txt
  components/eamxx/docs/developer/standalone_testing.md
  components/eamxx/scripts/git_utils.py
  components/eamxx/scripts/test_all_scream.py
  components/eamxx/src/control/tests/CMakeLists.txt
  components/eamxx/src/diagnostics/tests/CMakeLists.txt
  components/eamxx/src/dynamics/homme/tests/CMakeLists.txt
  components/eamxx/src/physics/nudging/tests/CMakeLists.txt
  components/eamxx/src/physics/p3/CMakeLists.txt
  components/eamxx/src/physics/p3/tests/CMakeLists.txt
  components/eamxx/src/physics/rrtmgp/tests/CMakeLists.txt
  components/eamxx/src/physics/share/tests/CMakeLists.txt
  components/eamxx/src/physics/shoc/CMakeLists.txt
  components/eamxx/src/physics/shoc/tests/CMakeLists.txt
  components/eamxx/src/physics/tms/tests/CMakeLists.txt
  components/eamxx/src/share/tests/CMakeLists.txt
  components/eamxx/tests/CMakeLists.txt
  components/eamxx/tests/coupled/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_mam4xx_pg2/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_p3_rrtmgp_pg2/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_128levels/CMakeLists.txt
  components/eamxx/tests/coupled/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_dp/CMakeLists.txt
  components/eamxx/tests/uncoupled/CMakeLists.txt
  components/eamxx/tests/uncoupled/cosp/CMakeLists.txt
  components/eamxx/tests/uncoupled/homme/CMakeLists.txt
  components/eamxx/tests/uncoupled/mam4/CMakeLists.txt
  components/eamxx/tests/uncoupled/p3/CMakeLists.txt
  components/eamxx/tests/uncoupled/rrtmgp/CMakeLists.txt
  components/eamxx/tests/uncoupled/shoc/CMakeLists.txt
  components/eamxx/tests/uncoupled/spa/CMakeLists.txt
Labels: testing, AT: AUTOMERGE, scripts

#2760 EAMxx: add possibility of auto-flushing the atm logger
  components/eamxx/cime_config/namelist_defaults_scream.xml
  components/eamxx/src/control/atmosphere_driver.cpp
Labels: infrastructure, AT: AUTOMERGE, code usability

#2764 buildnml: Write dbg XML when things fail
  components/eamxx/cime_config/eamxx_buildnml.py
Labels: AT: AUTOMERGE, AT: Skip weaver, AT: Skip Stand-Alone Testing

#2762 IOP fixes (shoc cell length and iop file read)
  cime_config/tests.py
  components/eamxx/src/control/intensive_observation_period.cpp
  components/eamxx/src/physics/shoc/eamxx_shoc_process_interface.cpp
Labels: DP-SCREAM

#2767 test-all-scream: Get scripts-tests working again
  components/eamxx/scripts/jenkins/jenkins_common_impl.sh
  components/eamxx/scripts/scripts-tests
  components/eamxx/scripts/test-all-scream
  components/eamxx/scripts/test_all_scream.py
Labels: AT: AUTOMERGE, scripts, AT: Skip v1 Testing

#2768 Add pnetcdf paths to config line when running test-all-scream
  components/eamxx/scripts/test_all_scream.py
Labels: testing, AT: AUTOMERGE, scripts, AT: Skip v1 Testing

#2769 test-all-scream: Fix force_baseline_regen
  components/eamxx/scripts/test_all_scream.py
  components/eamxx/scripts/utils.py
Labels: AT: AUTOMERGE, scripts, AT: Skip v1 Testing

#2771 test-all-scream: allow git symmetric diff to fail
  components/eamxx/scripts/git_utils.py
  components/eamxx/scripts/test_all_scream.py
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2772 Fix small bug in flushing file in scorpio interface
  components/eamxx/src/share/io/scream_output_manager.cpp
  components/eamxx/src/share/io/scream_scorpio_interface.F90
  components/eamxx/src/share/io/tests/output_restart.cpp
Labels: I/O, AT: AUTOMERGE, bugfix

#2592 Speed up `get_rain_dsd2` calculations.
  components/eam/src/physics/p3/scream/micro_p3.F90
  components/eamxx/src/physics/p3/impl/p3_dsd2_impl.hpp
  components/eamxx/src/physics/p3/impl/p3_main_impl_part2.hpp
  components/eamxx/src/physics/p3/impl/p3_main_impl_part3.hpp
  components/eamxx/src/physics/p3/impl/p3_rain_sed_impl.hpp
  components/eamxx/src/physics/p3/p3_functions.hpp
  components/eamxx/src/physics/p3/tests/p3_dsd2_unit_tests.cpp
Labels: Non-B4B, p3, performance

#2775 scripts-tests: Fix on weaver
  components/eamxx/scripts/jenkins/jenkins_common_impl.sh
Labels: AT: AUTOMERGE, AT: Integrate Without Testing
