Repository E3SM-Project/scream, pull requests merged in 2024-05, with the labels that each got.

#2796 move rad calls docs from tech to user, update nudging and aerocom docs
  .github/workflows/eamxx-gh-pages.yml
  components/eamxx/docs/refs/aerocom_cldtop.bib
  components/eamxx/docs/refs/general.bib
  components/eamxx/docs/technical/aerocom_cldtop.md
  components/eamxx/docs/technical/index.md
  components/eamxx/docs/user/clean_clear_sky.md
  components/eamxx/docs/user/coarse_nudging.md
  components/eamxx/docs/user/nudging.md
  components/eamxx/mkdocs.yml
  components/eamxx/src/physics/rrtmgp/eamxx_rrtmgp_process_interface.cpp
  components/eamxx/src/physics/rrtmgp/scream_rrtmgp_interface.cpp
  components/eamxx/src/physics/rrtmgp/scream_rrtmgp_interface.hpp
  components/eamxx/tests/multi-process/dynamics_physics/homme_shoc_cld_p3_rrtmgp_pg2/output.yaml
  components/eamxx/tests/single-process/rrtmgp/output.yaml
Labels: AT: AUTOMERGE, documentation, AT: Integrate Without Testing

#2806 A recent change to get_X_layout didn't make it to ML
  components/eamxx/src/physics/ml_correction/eamxx_ml_correction_process_interface.cpp
Labels: BFB, AT: AUTOMERGE, bugfix, AT: Skip Stand-Alone Testing, AT: Skip v1 Testing, machine learning

#2804 AeroComCldTop/Bot diagnostics
  components/eamxx/src/diagnostics/CMakeLists.txt
  components/eamxx/src/diagnostics/aerocom_cld.cpp
  components/eamxx/src/diagnostics/aerocom_cld.hpp
  components/eamxx/src/diagnostics/aerocom_cld_util.hpp
  components/eamxx/src/diagnostics/register_diagnostics.hpp
  components/eamxx/src/diagnostics/tests/CMakeLists.txt
  components/eamxx/src/diagnostics/tests/aerocom_cld_test.cpp
  components/eamxx/src/share/io/scorpio_output.cpp
Labels: AT: AUTOMERGE, diagnostic

#2805 Add documentation of how we can specify input parameters to EAMxx
  components/eamxx/docs/user/eamxx_cases.md
  components/eamxx/docs/user/index.md
  components/eamxx/docs/user/model_input.md
  components/eamxx/mkdocs.yml
Labels: AT: AUTOMERGE, documentation, AT: Integrate Without Testing

#2809 Bring more DPxx options out to namelist (nudging related)
  components/eamxx/cime_config/namelist_defaults_scream.xml
Labels: BFB, AT: AUTOMERGE, SCREAMv1, namelist, DP-SCREAM

#2801 Aarondonahue/io add longname metadata
  components/eamxx/src/dynamics/homme/homme_grids_manager.cpp
  components/eamxx/src/share/grid/mesh_free_grids_manager.cpp
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/io/scorpio_output.hpp
  components/eamxx/src/share/io/scream_io_utils.hpp
Labels: Non-B4B, New Variables, I/O, AT: AUTOMERGE

#2816 Improve model output documentation
  components/eamxx/docs/user/model_input.md
  components/eamxx/docs/user/model_output.md
Labels: AT: RETEST, AT: AUTOMERGE, documentation, AT: Integrate Without Testing

#2814 Fix for setting up lat/lon info in PG2 DP case
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/tests/multi-process/dynamics_physics/CMakeLists.txt
  components/eamxx/tests/multi-process/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_pg2_dp/CMakeLists.txt
  components/eamxx/tests/multi-process/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_pg2_dp/homme_shoc_cld_spa_p3_rrtmgp_pg2_dp.cpp
  components/eamxx/tests/multi-process/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_pg2_dp/input.yaml
  components/eamxx/tests/multi-process/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_pg2_dp/output.yaml
Labels: BFB, bugfix, DP-SCREAM

#2812 generalize diag potential temperature calc
  components/eamxx/src/diagnostics/potential_temperature.cpp
  components/eamxx/src/diagnostics/potential_temperature.hpp
  components/eamxx/src/diagnostics/tests/potential_temperature_test.cpp
  components/eamxx/src/physics/shoc/eamxx_shoc_process_interface.hpp
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/util/scream_common_physics_functions.hpp
  components/eamxx/src/share/util/scream_common_physics_functions_impl.hpp
Labels: BFB, AT: AUTOMERGE, priority:low, diagnostic

#2808 add a banner to scream
  components/eamxx/docs/overrides/main.html
  components/eamxx/mkdocs.yml
Labels: AT: AUTOMERGE, documentation, AT: Integrate Without Testing

#2815 Allow diags in IO to perform some ops at beginning of a timestep
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/share/atm_process/atmosphere_diagnostic.hpp
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/io/scorpio_output.hpp
  components/eamxx/src/share/io/scream_output_manager.cpp
  components/eamxx/src/share/io/scream_output_manager.hpp
  components/eamxx/src/share/io/tests/io_basic.cpp
  components/eamxx/src/share/io/tests/io_diags.cpp
  components/eamxx/src/share/io/tests/io_filled.cpp
  components/eamxx/src/share/io/tests/io_monthly.cpp
  components/eamxx/src/share/io/tests/io_packed.cpp
  components/eamxx/src/share/io/tests/io_remap_test.cpp
  components/eamxx/src/share/io/tests/io_se_grid.cpp
  components/eamxx/src/share/io/tests/output_restart.cpp
Labels: I/O

#2817 Add a precipitation adjustment to the ml-correction process.
  components/eamxx/src/physics/ml_correction/eamxx_ml_correction_process_interface.cpp
Labels: enhancement, AT: AUTOMERGE, machine learning

#2823 bind gpus to srun on pm-gpu
  components/eamxx/cmake/machine-files/pm-gpu.cmake
Labels: AT: AUTOMERGE, AT: Integrate Without Testing, pm-gpu, GPU

#2824 This commit addresses two fixes in Corrective-ML
  components/eamxx/src/physics/ml_correction/eamxx_ml_correction_process_interface.cpp
  components/eamxx/src/physics/ml_correction/ml_correction.py
Labels: AT: AUTOMERGE, bugfix, AT: Skip Stand-Alone Testing, AT: Skip v1 Testing, machine learning

#2829 EAMxx: fix weaver env setup for standalone testing
  components/eamxx/scripts/machines_specs.py
Labels: BFB, AT: AUTOMERGE, bugfix, AT: Skip mappy, AT: Skip v1 Testing

#2833 improve docs banner message
  components/eamxx/docs/overrides/main.html
Labels: AT: AUTOMERGE, documentation, AT: Integrate Without Testing

#2842 Fix generate_baseline test for RRTMGP
  components/eamxx/src/physics/rrtmgp/tests/generate_baseline.cpp
Labels: testing, BFB, radiation, AT: AUTOMERGE, bugfix, AT: Skip v1 Testing

#2846 Fix valgrind errors
  components/eamxx/scripts/CMakeLists.txt
  components/eamxx/scripts/jenkins/valgrind/mappy.supp
  components/eamxx/src/share/io/scream_scorpio_interface.cpp
  components/eamxx/src/share/io/tests/scorpio_interface_tests.cpp
Labels: AT: AUTOMERGE, bugfix, valgrind / cuda-memcheck

#2847 SHOC interface bug fix - TKE clipping
  components/eamxx/src/physics/shoc/eamxx_shoc_process_interface.hpp
Labels: Non-B4B, shoc, AT: AUTOMERGE, bugfix, SCREAMv1

#2837 Fix and cleanup vertical layer diagnostic
  components/eamxx/src/diagnostics/field_at_height.cpp
  components/eamxx/src/diagnostics/register_diagnostics.hpp
  components/eamxx/src/diagnostics/tests/field_at_height_tests.cpp
  components/eamxx/src/diagnostics/tests/vertical_layer_tests.cpp
  components/eamxx/src/diagnostics/vertical_layer.cpp
  components/eamxx/src/diagnostics/vertical_layer.hpp
  components/eamxx/src/share/io/scorpio_output.cpp
  components/eamxx/src/share/io/scream_io_utils.hpp
  components/eamxx/tests/single-process/p3/output.yaml
Labels: AT: AUTOMERGE, bugfix, diagnostic

#2819 Use IOP lat/lon in rrtmgp interface
  components/eamxx/src/control/atmosphere_driver.cpp
  components/eamxx/src/control/intensive_observation_period.hpp
  components/eamxx/src/physics/rrtmgp/eamxx_rrtmgp_process_interface.cpp
Labels: DP-SCREAM

#2840 Allow adding geo fields to grid objects, even if they are const
  components/eamxx/src/physics/rrtmgp/eamxx_rrtmgp_process_interface.cpp
  components/eamxx/src/share/field/field_layout.cpp
  components/eamxx/src/share/field/field_layout.hpp
  components/eamxx/src/share/grid/abstract_grid.cpp
  components/eamxx/src/share/grid/abstract_grid.hpp
  components/eamxx/src/share/grid/remap/horiz_interp_remapper_base.cpp
Labels: infrastructure, BFB, radiation, AT: AUTOMERGE

#2855 Add COSP user guide
  components/eamxx/docs/user/cosp.md
  components/eamxx/mkdocs.yml
Labels: AT: AUTOMERGE, documentation, AT: Integrate Without Testing

#2856 Move IOP from control/ to share/iop
  components/eamxx/src/control/CMakeLists.txt
  components/eamxx/src/control/atmosphere_driver.hpp
  components/eamxx/src/dynamics/homme/eamxx_homme_iop.cpp
  components/eamxx/src/physics/spa/spa_functions.hpp
  components/eamxx/src/physics/spa/tests/CMakeLists.txt
  components/eamxx/src/share/CMakeLists.txt
  components/eamxx/src/share/atm_process/atmosphere_process.hpp
  components/eamxx/src/share/iop/intensive_observation_period.cpp
  components/eamxx/src/share/iop/intensive_observation_period.hpp
Labels: cmake, BFB, AT: AUTOMERGE, bugfix, DP-SCREAM
