Repository E3SM-Project/scream, pull requests merged in 2024-04, with the labels that each got.

#2781 Fix rrtmgp valgrind tests
  cime_config/machines/config_machines.xml
  components/eamxx/scripts/machines_specs.py
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2789 Fixes to get valgrind working on mappy
  components/eamxx/scripts/jenkins/valgrind/mappy.supp
  components/eamxx/scripts/machines_specs.py
Labels: AT: AUTOMERGE, AT: Integrate Without Testing

#2790 Port remaining IOP functions and misc fixes
  components/eam/src/dynamics/se/se_iop_intr_mod.F90
  components/eamxx/src/control/intensive_observation_period.cpp
  components/eamxx/src/dynamics/homme/eamxx_homme_iop.cpp
  components/eamxx/src/dynamics/homme/eamxx_homme_process_interface.hpp
  components/eamxx/src/physics/share/physics_constants.hpp
  components/eamxx/tests/multi-process/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_dp/CMakeLists.txt
  components/eamxx/tests/multi-process/dynamics_physics/homme_shoc_cld_spa_p3_rrtmgp_dp/input.yaml
Labels: DP-SCREAM

#2791 EAMxx: subfield of read-only fields must be read-only
  components/eamxx/src/share/field/field.cpp
  components/eamxx/src/share/field/field.hpp
  components/eamxx/src/share/tests/field_tests.cpp
Labels: AT: AUTOMERGE, bugfix

#2792 docs: write top-level and tech doc overview; add .bib file
  components/eamxx/docs/index.md
  components/eamxx/docs/refs.bib
  components/eamxx/docs/technical/index.md
Labels: BFB, AT: AUTOMERGE, documentation, AT: Integrate Without Testing

#2799 For machine `frontier-scream-gpu`, upgrade to rocm 5.4
  cime_config/machines/config_machines.xml
Labels: Non-B4B, Machine File, AT: Integrate Without Testing, SCREAMv1, GPU, Frontier

#2800 add "NumberPath" diags
  components/eamxx/src/diagnostics/CMakeLists.txt
  components/eamxx/src/diagnostics/number_path.cpp
  components/eamxx/src/diagnostics/number_path.hpp
  components/eamxx/src/diagnostics/register_diagnostics.hpp
  components/eamxx/src/diagnostics/tests/CMakeLists.txt
  components/eamxx/src/diagnostics/tests/number_paths_tests.cpp
  components/eamxx/src/share/io/scorpio_output.cpp
Labels: AT: AUTOMERGE, diagnostic
